// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aura/wasm/v1beta1/wasm.proto

package v1beta1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AccessType defines permission levels for contract code operations
type AccessType int32

const (
	// ACCESS_TYPE_UNSPECIFIED placeholder for empty value
	AccessTypeUnspecified AccessType = 0
	// ACCESS_TYPE_NOBODY no one can execute this
	AccessTypeNobody AccessType = 1
	// ACCESS_TYPE_ONLY_ADDRESS only a specific address can execute
	AccessTypeOnlyAddress AccessType = 2
	// ACCESS_TYPE_EVERYBODY everyone can execute
	AccessTypeEverybody AccessType = 3
	// ACCESS_TYPE_ANY_OF_ADDRESSES any of the specified addresses can execute
	AccessTypeAnyOfAddresses AccessType = 4
)

var AccessType_name = map[int32]string{
	0: "ACCESS_TYPE_UNSPECIFIED",
	1: "ACCESS_TYPE_NOBODY",
	2: "ACCESS_TYPE_ONLY_ADDRESS",
	3: "ACCESS_TYPE_EVERYBODY",
	4: "ACCESS_TYPE_ANY_OF_ADDRESSES",
}

var AccessType_value = map[string]int32{
	"ACCESS_TYPE_UNSPECIFIED":      0,
	"ACCESS_TYPE_NOBODY":           1,
	"ACCESS_TYPE_ONLY_ADDRESS":     2,
	"ACCESS_TYPE_EVERYBODY":        3,
	"ACCESS_TYPE_ANY_OF_ADDRESSES": 4,
}

func (x AccessType) String() string {
	return proto.EnumName(AccessType_name, int32(x))
}

func (AccessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{0}
}

// ContractCodeHistoryOperationType is the type of code update
type ContractCodeHistoryOperationType int32

const (
	// CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED placeholder
	ContractCodeHistoryOperationTypeUnspecified ContractCodeHistoryOperationType = 0
	// CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT on contract instantiation
	ContractCodeHistoryOperationTypeInit ContractCodeHistoryOperationType = 1
	// CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE on contract migration
	ContractCodeHistoryOperationTypeMigrate ContractCodeHistoryOperationType = 2
	// CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS from genesis
	ContractCodeHistoryOperationTypeGenesis ContractCodeHistoryOperationType = 3
)

var ContractCodeHistoryOperationType_name = map[int32]string{
	0: "CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED",
	1: "CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT",
	2: "CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE",
	3: "CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS",
}

var ContractCodeHistoryOperationType_value = map[string]int32{
	"CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED": 0,
	"CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT":        1,
	"CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE":     2,
	"CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS":     3,
}

func (x ContractCodeHistoryOperationType) String() string {
	return proto.EnumName(ContractCodeHistoryOperationType_name, int32(x))
}

func (ContractCodeHistoryOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{1}
}

// AccessConfig defines access control configuration
type AccessConfig struct {
	Permission AccessType `protobuf:"varint,1,opt,name=permission,proto3,enum=aura.wasm.v1beta1.AccessType" json:"permission,omitempty"`
	// Address is only used when permission is AccessTypeOnlyAddress
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Addresses is only used when permission is AccessTypeAnyOfAddresses
	Addresses []string `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (m *AccessConfig) Reset()         { *m = AccessConfig{} }
func (m *AccessConfig) String() string { return proto.CompactTextString(m) }
func (*AccessConfig) ProtoMessage()    {}
func (*AccessConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{0}
}
func (m *AccessConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccessConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccessConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccessConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessConfig.Merge(m, src)
}
func (m *AccessConfig) XXX_Size() int {
	return m.Size()
}
func (m *AccessConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AccessConfig proto.InternalMessageInfo

func (m *AccessConfig) GetPermission() AccessType {
	if m != nil {
		return m.Permission
	}
	return AccessTypeUnspecified
}

func (m *AccessConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccessConfig) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// Params defines the parameters for the wasm module
type Params struct {
	// code_upload_access defines access control for code upload
	CodeUploadAccess AccessConfig `protobuf:"bytes,1,opt,name=code_upload_access,json=codeUploadAccess,proto3" json:"code_upload_access"`
	// instantiate_default_permission defines default permission for contract instantiation
	InstantiateDefaultPermission AccessType `protobuf:"varint,2,opt,name=instantiate_default_permission,json=instantiateDefaultPermission,proto3,enum=aura.wasm.v1beta1.AccessType" json:"instantiate_default_permission,omitempty"`
	// max_wasm_code_size defines maximum allowed wasm code size in bytes
	MaxWasmCodeSize uint64 `protobuf:"varint,3,opt,name=max_wasm_code_size,json=maxWasmCodeSize,proto3" json:"max_wasm_code_size,omitempty"`
	// max_gas_wasm_execution defines maximum gas for wasm execution
	MaxGasWasmExecution uint64 `protobuf:"varint,4,opt,name=max_gas_wasm_execution,json=maxGasWasmExecution,proto3" json:"max_gas_wasm_execution,omitempty"`
	// security_analysis_enabled enables on-chain security analysis
	SecurityAnalysisEnabled bool `protobuf:"varint,5,opt,name=security_analysis_enabled,json=securityAnalysisEnabled,proto3" json:"security_analysis_enabled,omitempty"`
	// require_admin_for_migrate requires admin to migrate contracts
	RequireAdminForMigrate bool `protobuf:"varint,6,opt,name=require_admin_for_migrate,json=requireAdminForMigrate,proto3" json:"require_admin_for_migrate,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCodeUploadAccess() AccessConfig {
	if m != nil {
		return m.CodeUploadAccess
	}
	return AccessConfig{}
}

func (m *Params) GetInstantiateDefaultPermission() AccessType {
	if m != nil {
		return m.InstantiateDefaultPermission
	}
	return AccessTypeUnspecified
}

func (m *Params) GetMaxWasmCodeSize() uint64 {
	if m != nil {
		return m.MaxWasmCodeSize
	}
	return 0
}

func (m *Params) GetMaxGasWasmExecution() uint64 {
	if m != nil {
		return m.MaxGasWasmExecution
	}
	return 0
}

func (m *Params) GetSecurityAnalysisEnabled() bool {
	if m != nil {
		return m.SecurityAnalysisEnabled
	}
	return false
}

func (m *Params) GetRequireAdminForMigrate() bool {
	if m != nil {
		return m.RequireAdminForMigrate
	}
	return false
}

// CodeInfo stores metadata about a WASM code
type CodeInfo struct {
	// code_hash is the SHA256 hash of the WASM bytecode
	CodeHash []byte `protobuf:"bytes,1,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	// creator is the address that uploaded the code
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// instantiate_config defines access control for instantiation
	InstantiateConfig AccessConfig `protobuf:"bytes,3,opt,name=instantiate_config,json=instantiateConfig,proto3" json:"instantiate_config"`
	// created_at is the block height when code was uploaded
	CreatedAt uint64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// source is optional URL to source code repository
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// builder is optional docker image used to build
	Builder string `protobuf:"bytes,6,opt,name=builder,proto3" json:"builder,omitempty"`
}

func (m *CodeInfo) Reset()         { *m = CodeInfo{} }
func (m *CodeInfo) String() string { return proto.CompactTextString(m) }
func (*CodeInfo) ProtoMessage()    {}
func (*CodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{2}
}
func (m *CodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeInfo.Merge(m, src)
}
func (m *CodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *CodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CodeInfo proto.InternalMessageInfo

func (m *CodeInfo) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *CodeInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CodeInfo) GetInstantiateConfig() AccessConfig {
	if m != nil {
		return m.InstantiateConfig
	}
	return AccessConfig{}
}

func (m *CodeInfo) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CodeInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CodeInfo) GetBuilder() string {
	if m != nil {
		return m.Builder
	}
	return ""
}

// ContractInfo stores metadata about a contract instance
type ContractInfo struct {
	// code_id references the code stored on chain
	CodeId uint64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// creator is the address that instantiated the contract
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// admin is the address that has admin privileges (can migrate/update)
	Admin string `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	// label is a human-readable name for the contract
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// created_at is the block height of instantiation
	CreatedAt uint64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ibc_port_id is the portID for IBC if enabled
	IbcPortId string `protobuf:"bytes,6,opt,name=ibc_port_id,json=ibcPortId,proto3" json:"ibc_port_id,omitempty"`
	// extension allows storing arbitrary metadata
	Extension []byte `protobuf:"bytes,7,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (m *ContractInfo) Reset()         { *m = ContractInfo{} }
func (m *ContractInfo) String() string { return proto.CompactTextString(m) }
func (*ContractInfo) ProtoMessage()    {}
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{3}
}
func (m *ContractInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractInfo.Merge(m, src)
}
func (m *ContractInfo) XXX_Size() int {
	return m.Size()
}
func (m *ContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContractInfo proto.InternalMessageInfo

func (m *ContractInfo) GetCodeId() uint64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *ContractInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ContractInfo) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *ContractInfo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ContractInfo) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ContractInfo) GetIbcPortId() string {
	if m != nil {
		return m.IbcPortId
	}
	return ""
}

func (m *ContractInfo) GetExtension() []byte {
	if m != nil {
		return m.Extension
	}
	return nil
}

// ContractHistoryEntry describes a single contract state change
type ContractHistoryEntry struct {
	// operation describes what triggered this entry
	Operation ContractCodeHistoryOperationType `protobuf:"varint,1,opt,name=operation,proto3,enum=aura.wasm.v1beta1.ContractCodeHistoryOperationType" json:"operation,omitempty"`
	// code_id is the code reference at this point
	CodeId uint64 `protobuf:"varint,2,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// updated_at is the block height of this update
	UpdatedAt uint64 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// msg contains the initialization/migration message
	Msg []byte `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *ContractHistoryEntry) Reset()         { *m = ContractHistoryEntry{} }
func (m *ContractHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*ContractHistoryEntry) ProtoMessage()    {}
func (*ContractHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{4}
}
func (m *ContractHistoryEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractHistoryEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractHistoryEntry.Merge(m, src)
}
func (m *ContractHistoryEntry) XXX_Size() int {
	return m.Size()
}
func (m *ContractHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContractHistoryEntry proto.InternalMessageInfo

func (m *ContractHistoryEntry) GetOperation() ContractCodeHistoryOperationType {
	if m != nil {
		return m.Operation
	}
	return ContractCodeHistoryOperationTypeUnspecified
}

func (m *ContractHistoryEntry) GetCodeId() uint64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *ContractHistoryEntry) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ContractHistoryEntry) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// Model represents a single key-value state entry
type Model struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{5}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Model.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return m.Size()
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Model) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// SecurityStats tracks security metrics for the WASM module
type SecurityStats struct {
	// total_codes_analyzed is the number of codes that passed security analysis
	TotalCodesAnalyzed uint64 `protobuf:"varint,1,opt,name=total_codes_analyzed,json=totalCodesAnalyzed,proto3" json:"total_codes_analyzed,omitempty"`
	// codes_rejected is the number of codes rejected by security analysis
	CodesRejected uint64 `protobuf:"varint,2,opt,name=codes_rejected,json=codesRejected,proto3" json:"codes_rejected,omitempty"`
	// contracts_paused is the current number of paused contracts
	ContractsPaused uint64 `protobuf:"varint,3,opt,name=contracts_paused,json=contractsPaused,proto3" json:"contracts_paused,omitempty"`
	// total_executions is the total number of contract executions
	TotalExecutions uint64 `protobuf:"varint,4,opt,name=total_executions,json=totalExecutions,proto3" json:"total_executions,omitempty"`
	// failed_executions is the number of failed executions
	FailedExecutions uint64 `protobuf:"varint,5,opt,name=failed_executions,json=failedExecutions,proto3" json:"failed_executions,omitempty"`
	// gas_consumed_total is the total gas consumed by wasm executions
	GasConsumedTotal uint64 `protobuf:"varint,6,opt,name=gas_consumed_total,json=gasConsumedTotal,proto3" json:"gas_consumed_total,omitempty"`
	// last_security_scan is the block height of last security scan
	LastSecurityScan uint64 `protobuf:"varint,7,opt,name=last_security_scan,json=lastSecurityScan,proto3" json:"last_security_scan,omitempty"`
}

func (m *SecurityStats) Reset()         { *m = SecurityStats{} }
func (m *SecurityStats) String() string { return proto.CompactTextString(m) }
func (*SecurityStats) ProtoMessage()    {}
func (*SecurityStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{6}
}
func (m *SecurityStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SecurityStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SecurityStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SecurityStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityStats.Merge(m, src)
}
func (m *SecurityStats) XXX_Size() int {
	return m.Size()
}
func (m *SecurityStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityStats.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityStats proto.InternalMessageInfo

func (m *SecurityStats) GetTotalCodesAnalyzed() uint64 {
	if m != nil {
		return m.TotalCodesAnalyzed
	}
	return 0
}

func (m *SecurityStats) GetCodesRejected() uint64 {
	if m != nil {
		return m.CodesRejected
	}
	return 0
}

func (m *SecurityStats) GetContractsPaused() uint64 {
	if m != nil {
		return m.ContractsPaused
	}
	return 0
}

func (m *SecurityStats) GetTotalExecutions() uint64 {
	if m != nil {
		return m.TotalExecutions
	}
	return 0
}

func (m *SecurityStats) GetFailedExecutions() uint64 {
	if m != nil {
		return m.FailedExecutions
	}
	return 0
}

func (m *SecurityStats) GetGasConsumedTotal() uint64 {
	if m != nil {
		return m.GasConsumedTotal
	}
	return 0
}

func (m *SecurityStats) GetLastSecurityScan() uint64 {
	if m != nil {
		return m.LastSecurityScan
	}
	return 0
}

// AbsoluteTxPosition is a unique transaction position in the blockchain
type AbsoluteTxPosition struct {
	// block_height is the block number
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// tx_index is the transaction index in the block
	TxIndex uint64 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
}

func (m *AbsoluteTxPosition) Reset()         { *m = AbsoluteTxPosition{} }
func (m *AbsoluteTxPosition) String() string { return proto.CompactTextString(m) }
func (*AbsoluteTxPosition) ProtoMessage()    {}
func (*AbsoluteTxPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_c765c617f2a5e87d, []int{7}
}
func (m *AbsoluteTxPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AbsoluteTxPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AbsoluteTxPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AbsoluteTxPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbsoluteTxPosition.Merge(m, src)
}
func (m *AbsoluteTxPosition) XXX_Size() int {
	return m.Size()
}
func (m *AbsoluteTxPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_AbsoluteTxPosition.DiscardUnknown(m)
}

var xxx_messageInfo_AbsoluteTxPosition proto.InternalMessageInfo

func (m *AbsoluteTxPosition) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *AbsoluteTxPosition) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("aura.wasm.v1beta1.AccessType", AccessType_name, AccessType_value)
	proto.RegisterEnum("aura.wasm.v1beta1.ContractCodeHistoryOperationType", ContractCodeHistoryOperationType_name, ContractCodeHistoryOperationType_value)
	proto.RegisterType((*AccessConfig)(nil), "aura.wasm.v1beta1.AccessConfig")
	proto.RegisterType((*Params)(nil), "aura.wasm.v1beta1.Params")
	proto.RegisterType((*CodeInfo)(nil), "aura.wasm.v1beta1.CodeInfo")
	proto.RegisterType((*ContractInfo)(nil), "aura.wasm.v1beta1.ContractInfo")
	proto.RegisterType((*ContractHistoryEntry)(nil), "aura.wasm.v1beta1.ContractHistoryEntry")
	proto.RegisterType((*Model)(nil), "aura.wasm.v1beta1.Model")
	proto.RegisterType((*SecurityStats)(nil), "aura.wasm.v1beta1.SecurityStats")
	proto.RegisterType((*AbsoluteTxPosition)(nil), "aura.wasm.v1beta1.AbsoluteTxPosition")
}

func init() { proto.RegisterFile("aura/wasm/v1beta1/wasm.proto", fileDescriptor_c765c617f2a5e87d) }

var fileDescriptor_c765c617f2a5e87d = []byte{
	// 1298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0x57, 0x3e, 0x3c, 0x4d, 0xdb, 0xed, 0x34, 0x6d, 0x1c, 0x93, 0xba, 0xa6, 0x02, 0x91,
	0x36, 0x25, 0x6e, 0x53, 0x51, 0x44, 0x25, 0x90, 0x36, 0xce, 0x36, 0x31, 0xa2, 0xb6, 0xd9, 0x75,
	0x29, 0x41, 0x42, 0xab, 0xf1, 0xee, 0xd8, 0x19, 0xba, 0xde, 0x31, 0x3b, 0xb3, 0xc5, 0xee, 0x99,
	0x43, 0xe5, 0x13, 0x47, 0x2e, 0x96, 0x40, 0x08, 0xfe, 0x02, 0x2e, 0x9c, 0xb8, 0xf6, 0x82, 0x54,
	0x71, 0xe2, 0x84, 0x50, 0x7b, 0xe1, 0xcf, 0x40, 0xf3, 0xb1, 0xf1, 0xd2, 0x96, 0x26, 0xe2, 0x36,
	0xf3, 0x7e, 0xef, 0xf7, 0x66, 0xde, 0xef, 0xbd, 0x37, 0xbb, 0x60, 0x0d, 0xc5, 0x11, 0xaa, 0x7d,
	0x85, 0xd8, 0xa0, 0xf6, 0xe0, 0x7a, 0x17, 0x73, 0x74, 0x5d, 0x6e, 0x36, 0x87, 0x11, 0xe5, 0x14,
	0x9e, 0x11, 0xe8, 0xa6, 0x34, 0x68, 0xb4, 0xbc, 0xdc, 0xa7, 0x7d, 0x2a, 0xd1, 0x9a, 0x58, 0x29,
	0xc7, 0xf2, 0xaa, 0x47, 0xd9, 0x80, 0x32, 0x57, 0x01, 0x6a, 0xa3, 0xa1, 0x8a, 0xda, 0xd5, 0xba,
	0x88, 0xe1, 0xc3, 0x33, 0x3c, 0x4a, 0x42, 0x85, 0x5f, 0xfa, 0x35, 0x0b, 0x96, 0x4c, 0xcf, 0xc3,
	0x8c, 0xd5, 0x69, 0xd8, 0x23, 0x7d, 0xf8, 0x3e, 0x00, 0x43, 0x1c, 0x0d, 0x08, 0x63, 0x84, 0x86,
	0xa5, 0x6c, 0x35, 0xbb, 0x7e, 0x6a, 0xeb, 0xc2, 0xe6, 0x0b, 0x37, 0xd9, 0x54, 0xa4, 0xce, 0x78,
	0x88, 0xed, 0x14, 0x01, 0x6e, 0x81, 0x05, 0xe4, 0xfb, 0x11, 0x66, 0xac, 0x94, 0xab, 0x66, 0xd7,
	0x8b, 0xdb, 0xa5, 0xdf, 0x7f, 0x7e, 0x7b, 0x59, 0x5f, 0xc9, 0x54, 0x88, 0xc3, 0x23, 0x12, 0xf6,
	0xed, 0xc4, 0x11, 0xde, 0x04, 0x45, 0xbd, 0xc4, 0xac, 0x94, 0xaf, 0xe6, 0x5f, 0xc9, 0x9a, 0xb9,
	0xde, 0x2a, 0x7c, 0xfb, 0xdd, 0xc5, 0xec, 0xa5, 0xef, 0xf3, 0x60, 0xbe, 0x8d, 0x22, 0x34, 0x60,
	0xd0, 0x01, 0xd0, 0xa3, 0x3e, 0x76, 0xe3, 0x61, 0x40, 0x91, 0xef, 0x22, 0x79, 0x45, 0x99, 0xc3,
	0x89, 0xad, 0x8b, 0xff, 0x99, 0x83, 0x4a, 0x7c, 0xbb, 0xf0, 0xf8, 0xcf, 0x8b, 0x19, 0xdb, 0x10,
	0x01, 0xee, 0x4a, 0xbe, 0x42, 0xa1, 0x07, 0x2a, 0x24, 0x64, 0x1c, 0x85, 0x9c, 0x20, 0x8e, 0x5d,
	0x1f, 0xf7, 0x50, 0x1c, 0x70, 0x37, 0x25, 0x52, 0xee, 0x38, 0x22, 0xad, 0xa5, 0x82, 0xec, 0xa8,
	0x18, 0xed, 0x99, 0x6c, 0x1b, 0x00, 0x0e, 0xd0, 0xc8, 0x15, 0x64, 0x57, 0xa6, 0xc0, 0xc8, 0x43,
	0x5c, 0xca, 0x57, 0xb3, 0xeb, 0x05, 0xfb, 0xf4, 0x00, 0x8d, 0xee, 0x21, 0x36, 0xa8, 0x53, 0x1f,
	0x3b, 0xe4, 0x21, 0x86, 0x37, 0xc0, 0x79, 0xe1, 0xdc, 0x47, 0x4c, 0x11, 0xf0, 0x08, 0x7b, 0x31,
	0x17, 0x37, 0x29, 0x48, 0xc2, 0xd9, 0x01, 0x1a, 0xed, 0x22, 0x26, 0x38, 0x56, 0x02, 0xc1, 0x5b,
	0x60, 0x95, 0x61, 0x2f, 0x8e, 0x08, 0x1f, 0xbb, 0x28, 0x44, 0xc1, 0x98, 0x11, 0xe6, 0xe2, 0x10,
	0x75, 0x03, 0xec, 0x97, 0xe6, 0xaa, 0xd9, 0xf5, 0x45, 0x7b, 0x25, 0x71, 0x30, 0x35, 0x6e, 0x29,
	0x18, 0xbe, 0x07, 0x56, 0x23, 0xfc, 0x65, 0x4c, 0x22, 0xec, 0x22, 0x7f, 0x40, 0x42, 0xb7, 0x47,
	0x23, 0x77, 0x40, 0xfa, 0x11, 0xe2, 0xb8, 0x34, 0x2f, 0xb9, 0xe7, 0xb5, 0x83, 0x29, 0xf0, 0xdb,
	0x34, 0xba, 0xa3, 0x50, 0x59, 0xa3, 0xcc, 0xa5, 0x47, 0x39, 0xb0, 0x28, 0xae, 0xdf, 0x08, 0x7b,
	0x14, 0xbe, 0x06, 0x8a, 0x32, 0xc5, 0x03, 0xc4, 0x0e, 0x64, 0x71, 0x96, 0xec, 0x45, 0x61, 0xd8,
	0x43, 0xec, 0x40, 0xf4, 0x8f, 0x17, 0x61, 0xc4, 0x69, 0x74, 0x74, 0xff, 0x68, 0x47, 0xd8, 0x01,
	0x30, 0x5d, 0x21, 0x4f, 0xd6, 0x53, 0x8a, 0x77, 0xec, 0xb2, 0x9f, 0x49, 0x05, 0xd0, 0x83, 0x70,
	0x01, 0x00, 0x79, 0x00, 0xf6, 0x5d, 0xc4, 0xb5, 0xb2, 0x45, 0x6d, 0x31, 0x39, 0x3c, 0x0f, 0xe6,
	0x19, 0x8d, 0x23, 0x0f, 0x4b, 0xf1, 0x8a, 0xb6, 0xde, 0xc1, 0x12, 0x58, 0xe8, 0xc6, 0x24, 0xf0,
	0x71, 0x24, 0x95, 0x29, 0xda, 0xc9, 0xf6, 0x56, 0xe1, 0x6f, 0xd1, 0xae, 0x5f, 0xe7, 0xc0, 0x52,
	0x9d, 0x86, 0x3c, 0x42, 0x1e, 0x97, 0x72, 0xac, 0x80, 0x05, 0x29, 0x07, 0xf1, 0xa5, 0x18, 0x05,
	0x7b, 0x5e, 0x6c, 0x1b, 0xfe, 0xff, 0x92, 0x62, 0x13, 0xcc, 0xc9, 0x0a, 0xc9, 0xec, 0x5f, 0xc5,
	0x50, 0x6e, 0x70, 0x19, 0xcc, 0x05, 0xa8, 0x8b, 0x03, 0x99, 0x5f, 0xd1, 0x56, 0x9b, 0xe7, 0x52,
	0x9f, 0x7b, 0x3e, 0xf5, 0x0a, 0x38, 0x41, 0xba, 0x9e, 0x3b, 0xa4, 0x11, 0x17, 0xb7, 0x56, 0x69,
	0x16, 0x49, 0xd7, 0x6b, 0xd3, 0x88, 0x37, 0x7c, 0xb8, 0x06, 0x8a, 0x78, 0xc4, 0x71, 0x28, 0x87,
	0x63, 0x41, 0x16, 0x78, 0x66, 0xd0, 0x32, 0xfc, 0x92, 0x05, 0xcb, 0x89, 0x0c, 0x7b, 0x84, 0x71,
	0x1a, 0x8d, 0xad, 0x90, 0x47, 0x63, 0xf8, 0x31, 0x28, 0xd2, 0x21, 0x8e, 0x10, 0x9f, 0x3d, 0x3f,
	0x37, 0x5e, 0x52, 0xc3, 0x84, 0x2b, 0xba, 0x4a, 0xf3, 0x5b, 0x09, 0x4d, 0xce, 0xdb, 0x2c, 0x4a,
	0x5a, 0xe1, 0xdc, 0xbf, 0x14, 0xbe, 0x00, 0x40, 0x3c, 0xf4, 0x93, 0x3c, 0xd5, 0xb4, 0x15, 0xb5,
	0xc5, 0xe4, 0xd0, 0x00, 0xf9, 0x01, 0xeb, 0x4b, 0x69, 0x96, 0x6c, 0xb1, 0xd4, 0x77, 0x7f, 0x07,
	0xcc, 0xdd, 0xa1, 0x3e, 0x0e, 0x84, 0xc3, 0x7d, 0x3c, 0xd6, 0x3d, 0x2c, 0x96, 0x42, 0xcf, 0x07,
	0x28, 0x88, 0xb1, 0x3c, 0x68, 0xc9, 0x56, 0x1b, 0x4d, 0xfb, 0x2d, 0x07, 0x4e, 0x3a, 0x7a, 0xc2,
	0x1c, 0x8e, 0x38, 0x83, 0xd7, 0xc0, 0x32, 0xa7, 0x1c, 0x05, 0x72, 0xe4, 0x99, 0x1a, 0xcb, 0x87,
	0x38, 0xe9, 0x03, 0x28, 0x31, 0x91, 0x20, 0x33, 0x35, 0x02, 0xdf, 0x04, 0xa7, 0x94, 0x6f, 0x84,
	0xbf, 0xc0, 0x1e, 0xc7, 0x49, 0x46, 0x27, 0xa5, 0xd5, 0xd6, 0x46, 0x78, 0x19, 0x18, 0x9e, 0x16,
	0x88, 0xb9, 0x43, 0x14, 0x33, 0xec, 0x27, 0x8f, 0xc9, 0xa1, 0xbd, 0x2d, 0xcd, 0xc2, 0x55, 0xdd,
	0xe1, 0xf0, 0x15, 0x61, 0xba, 0xd9, 0x4f, 0x4b, 0xfb, 0xe1, 0x0b, 0xc2, 0xe0, 0x06, 0x38, 0xd3,
	0x43, 0x24, 0xc0, 0x7e, 0xda, 0x57, 0x75, 0x87, 0xa1, 0x80, 0x94, 0xf3, 0x55, 0x00, 0xc5, 0x03,
	0xe5, 0xd1, 0x90, 0xc5, 0x03, 0xec, 0xbb, 0x32, 0x98, 0xec, 0x95, 0x82, 0x6d, 0xf4, 0x91, 0x18,
	0x3f, 0x09, 0x74, 0x84, 0x5d, 0x78, 0x07, 0x88, 0x71, 0xf7, 0xf0, 0x89, 0x62, 0x1e, 0x52, 0xbd,
	0x53, 0xb0, 0x0d, 0x81, 0x1c, 0x0a, 0xe7, 0xa1, 0xa4, 0x85, 0x3e, 0x05, 0xd0, 0xec, 0x32, 0x1a,
	0xc4, 0x1c, 0x77, 0x46, 0x6d, 0xca, 0x88, 0x2c, 0xf6, 0xeb, 0x60, 0xa9, 0x1b, 0x50, 0xef, 0xbe,
	0x7b, 0x80, 0x49, 0xff, 0x80, 0x6b, 0x2d, 0x4f, 0x48, 0xdb, 0x9e, 0x34, 0xc1, 0x55, 0xb0, 0xc8,
	0x47, 0x2e, 0x09, 0x7d, 0x3c, 0xd2, 0xf2, 0x2d, 0xf0, 0x51, 0x43, 0x6c, 0x55, 0xe4, 0x2b, 0x3f,
	0xe6, 0x00, 0x98, 0x3d, 0xdd, 0xf0, 0x26, 0x58, 0x31, 0xeb, 0x75, 0xcb, 0x71, 0xdc, 0xce, 0x7e,
	0xdb, 0x72, 0xef, 0x36, 0x9d, 0xb6, 0x55, 0x6f, 0xdc, 0x6e, 0x58, 0x3b, 0x46, 0xa6, 0xbc, 0x3a,
	0x99, 0x56, 0xcf, 0xcd, 0x9c, 0xef, 0x86, 0x6c, 0x88, 0x3d, 0xd2, 0x23, 0xd8, 0x17, 0x49, 0xa5,
	0x79, 0xcd, 0xd6, 0x76, 0x6b, 0x67, 0xdf, 0xc8, 0x96, 0x97, 0x27, 0xd3, 0xaa, 0x31, 0xa3, 0x34,
	0x69, 0x97, 0xfa, 0x63, 0xf8, 0x2e, 0x28, 0xa5, 0xbd, 0x5b, 0xcd, 0x8f, 0xf6, 0x5d, 0x73, 0x67,
	0xc7, 0xb6, 0x1c, 0xc7, 0xc8, 0x3d, 0x7f, 0x4c, 0x2b, 0x0c, 0xc6, 0x7a, 0xa0, 0xe1, 0x16, 0x38,
	0x97, 0x26, 0x5a, 0x9f, 0x58, 0xf6, 0xbe, 0x3c, 0x29, 0x5f, 0x5e, 0x99, 0x4c, 0xab, 0x67, 0x67,
	0x2c, 0xeb, 0x01, 0x8e, 0xc6, 0xf2, 0xb0, 0x0f, 0xc0, 0x5a, 0x9a, 0x63, 0x36, 0xf7, 0xdd, 0xd6,
	0xed, 0xe4, 0x38, 0xcb, 0x31, 0x0a, 0xe5, 0xb5, 0xc9, 0xb4, 0x5a, 0x9a, 0x51, 0xcd, 0x70, 0xdc,
	0xea, 0x99, 0xc9, 0xa7, 0xb7, 0x5c, 0x78, 0xf4, 0x43, 0x25, 0x73, 0xe5, 0xa7, 0x3c, 0xa8, 0x1e,
	0x35, 0x88, 0x10, 0x83, 0x6b, 0xf5, 0x56, 0xb3, 0x63, 0x9b, 0xf5, 0x8e, 0x5b, 0x6f, 0xed, 0x58,
	0xee, 0x5e, 0xc3, 0xe9, 0xb4, 0xec, 0x7d, 0xb7, 0xd5, 0xb6, 0x6c, 0xb3, 0xd3, 0x68, 0x35, 0x5f,
	0x26, 0x6b, 0x6d, 0x32, 0xad, 0x6e, 0x1c, 0x15, 0x3b, 0x2d, 0xf6, 0x3d, 0x70, 0xf9, 0x58, 0xc7,
	0x34, 0x9a, 0x8d, 0x8e, 0x91, 0x2d, 0xaf, 0x4f, 0xa6, 0xd5, 0x37, 0x8e, 0x8a, 0xdf, 0x08, 0x09,
	0x87, 0x9f, 0x83, 0xab, 0xc7, 0x0a, 0x7c, 0xa7, 0xb1, 0x6b, 0x9b, 0x1d, 0xcb, 0xc8, 0x95, 0x37,
	0x26, 0xd3, 0xea, 0x5b, 0x47, 0xc5, 0xd6, 0x1f, 0xc8, 0x63, 0x87, 0xdf, 0xb5, 0x9a, 0x96, 0xd3,
	0x70, 0x8c, 0xfc, 0xf1, 0xc2, 0xef, 0xe2, 0x10, 0x33, 0xa2, 0x0b, 0xb5, 0xfd, 0xe1, 0xe3, 0xa7,
	0x95, 0xec, 0x93, 0xa7, 0x95, 0xec, 0x5f, 0x4f, 0x2b, 0xd9, 0x6f, 0x9e, 0x55, 0x32, 0x4f, 0x9e,
	0x55, 0x32, 0x7f, 0x3c, 0xab, 0x64, 0x3e, 0xbb, 0xd6, 0x27, 0xfc, 0x20, 0xee, 0x6e, 0x7a, 0x74,
	0x50, 0x43, 0xe2, 0x13, 0xce, 0x11, 0xab, 0xc9, 0xbf, 0x52, 0xf5, 0x33, 0xf9, 0xc2, 0x0f, 0x6a,
	0x77, 0x5e, 0x02, 0x37, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xba, 0x17, 0x47, 0xbc, 0x0a,
	0x00, 0x00,
}

func (this *CodeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CodeInfo)
	if !ok {
		that2, ok := that.(CodeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.CodeHash, that1.CodeHash) {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if !this.InstantiateConfig.Equal(&that1.InstantiateConfig) {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if this.Builder != that1.Builder {
		return false
	}
	return true
}
func (this *ContractInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ContractInfo)
	if !ok {
		that2, ok := that.(ContractInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CodeId != that1.CodeId {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.Admin != that1.Admin {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if this.IbcPortId != that1.IbcPortId {
		return false
	}
	if !bytes.Equal(this.Extension, that1.Extension) {
		return false
	}
	return true
}
func (this *ContractHistoryEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ContractHistoryEntry)
	if !ok {
		that2, ok := that.(ContractHistoryEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Operation != that1.Operation {
		return false
	}
	if this.CodeId != that1.CodeId {
		return false
	}
	if this.UpdatedAt != that1.UpdatedAt {
		return false
	}
	if !bytes.Equal(this.Msg, that1.Msg) {
		return false
	}
	return true
}
func (this *Model) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Model)
	if !ok {
		that2, ok := that.(Model)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	return true
}
func (this *SecurityStats) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SecurityStats)
	if !ok {
		that2, ok := that.(SecurityStats)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TotalCodesAnalyzed != that1.TotalCodesAnalyzed {
		return false
	}
	if this.CodesRejected != that1.CodesRejected {
		return false
	}
	if this.ContractsPaused != that1.ContractsPaused {
		return false
	}
	if this.TotalExecutions != that1.TotalExecutions {
		return false
	}
	if this.FailedExecutions != that1.FailedExecutions {
		return false
	}
	if this.GasConsumedTotal != that1.GasConsumedTotal {
		return false
	}
	if this.LastSecurityScan != that1.LastSecurityScan {
		return false
	}
	return true
}
func (this *AbsoluteTxPosition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AbsoluteTxPosition)
	if !ok {
		that2, ok := that.(AbsoluteTxPosition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if this.TxIndex != that1.TxIndex {
		return false
	}
	return true
}
func (m *AccessConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccessConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccessConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintWasm(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Permission != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.Permission))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequireAdminForMigrate {
		i--
		if m.RequireAdminForMigrate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SecurityAnalysisEnabled {
		i--
		if m.SecurityAnalysisEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.MaxGasWasmExecution != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.MaxGasWasmExecution))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxWasmCodeSize != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.MaxWasmCodeSize))
		i--
		dAtA[i] = 0x18
	}
	if m.InstantiateDefaultPermission != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.InstantiateDefaultPermission))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.CodeUploadAccess.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWasm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Builder) > 0 {
		i -= len(m.Builder)
		copy(dAtA[i:], m.Builder)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Builder)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.InstantiateConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWasm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CodeHash) > 0 {
		i -= len(m.CodeHash)
		copy(dAtA[i:], m.CodeHash)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.CodeHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ContractInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Extension) > 0 {
		i -= len(m.Extension)
		copy(dAtA[i:], m.Extension)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Extension)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.IbcPortId) > 0 {
		i -= len(m.IbcPortId)
		copy(dAtA[i:], m.IbcPortId)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.IbcPortId)))
		i--
		dAtA[i] = 0x32
	}
	if m.CreatedAt != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.CodeId != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.CodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ContractHistoryEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractHistoryEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractHistoryEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x22
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.CodeId != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.CodeId))
		i--
		dAtA[i] = 0x10
	}
	if m.Operation != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.Operation))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Model) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Model) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Model) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintWasm(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SecurityStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SecurityStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SecurityStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSecurityScan != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.LastSecurityScan))
		i--
		dAtA[i] = 0x38
	}
	if m.GasConsumedTotal != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.GasConsumedTotal))
		i--
		dAtA[i] = 0x30
	}
	if m.FailedExecutions != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.FailedExecutions))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalExecutions != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.TotalExecutions))
		i--
		dAtA[i] = 0x20
	}
	if m.ContractsPaused != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.ContractsPaused))
		i--
		dAtA[i] = 0x18
	}
	if m.CodesRejected != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.CodesRejected))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalCodesAnalyzed != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.TotalCodesAnalyzed))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AbsoluteTxPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AbsoluteTxPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AbsoluteTxPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxIndex != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.TxIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.BlockHeight != 0 {
		i = encodeVarintWasm(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWasm(dAtA []byte, offset int, v uint64) int {
	offset -= sovWasm(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccessConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Permission != 0 {
		n += 1 + sovWasm(uint64(m.Permission))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovWasm(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CodeUploadAccess.Size()
	n += 1 + l + sovWasm(uint64(l))
	if m.InstantiateDefaultPermission != 0 {
		n += 1 + sovWasm(uint64(m.InstantiateDefaultPermission))
	}
	if m.MaxWasmCodeSize != 0 {
		n += 1 + sovWasm(uint64(m.MaxWasmCodeSize))
	}
	if m.MaxGasWasmExecution != 0 {
		n += 1 + sovWasm(uint64(m.MaxGasWasmExecution))
	}
	if m.SecurityAnalysisEnabled {
		n += 2
	}
	if m.RequireAdminForMigrate {
		n += 2
	}
	return n
}

func (m *CodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeHash)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = m.InstantiateConfig.Size()
	n += 1 + l + sovWasm(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovWasm(uint64(m.CreatedAt))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Builder)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	return n
}

func (m *ContractInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CodeId != 0 {
		n += 1 + sovWasm(uint64(m.CodeId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovWasm(uint64(m.CreatedAt))
	}
	l = len(m.IbcPortId)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Extension)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	return n
}

func (m *ContractHistoryEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Operation != 0 {
		n += 1 + sovWasm(uint64(m.Operation))
	}
	if m.CodeId != 0 {
		n += 1 + sovWasm(uint64(m.CodeId))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovWasm(uint64(m.UpdatedAt))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	return n
}

func (m *Model) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovWasm(uint64(l))
	}
	return n
}

func (m *SecurityStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalCodesAnalyzed != 0 {
		n += 1 + sovWasm(uint64(m.TotalCodesAnalyzed))
	}
	if m.CodesRejected != 0 {
		n += 1 + sovWasm(uint64(m.CodesRejected))
	}
	if m.ContractsPaused != 0 {
		n += 1 + sovWasm(uint64(m.ContractsPaused))
	}
	if m.TotalExecutions != 0 {
		n += 1 + sovWasm(uint64(m.TotalExecutions))
	}
	if m.FailedExecutions != 0 {
		n += 1 + sovWasm(uint64(m.FailedExecutions))
	}
	if m.GasConsumedTotal != 0 {
		n += 1 + sovWasm(uint64(m.GasConsumedTotal))
	}
	if m.LastSecurityScan != 0 {
		n += 1 + sovWasm(uint64(m.LastSecurityScan))
	}
	return n
}

func (m *AbsoluteTxPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovWasm(uint64(m.BlockHeight))
	}
	if m.TxIndex != 0 {
		n += 1 + sovWasm(uint64(m.TxIndex))
	}
	return n
}

func sovWasm(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWasm(x uint64) (n int) {
	return sovWasm(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccessConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccessConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccessConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permission", wireType)
			}
			m.Permission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Permission |= AccessType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeUploadAccess", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CodeUploadAccess.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstantiateDefaultPermission", wireType)
			}
			m.InstantiateDefaultPermission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstantiateDefaultPermission |= AccessType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWasmCodeSize", wireType)
			}
			m.MaxWasmCodeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWasmCodeSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasWasmExecution", wireType)
			}
			m.MaxGasWasmExecution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasWasmExecution |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityAnalysisEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SecurityAnalysisEnabled = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireAdminForMigrate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequireAdminForMigrate = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeHash = append(m.CodeHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeHash == nil {
				m.CodeHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstantiateConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InstantiateConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Builder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Builder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContractInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			m.CodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcPortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcPortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extension", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extension = append(m.Extension[:0], dAtA[iNdEx:postIndex]...)
			if m.Extension == nil {
				m.Extension = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContractHistoryEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractHistoryEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractHistoryEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			m.Operation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Operation |= ContractCodeHistoryOperationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			m.CodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = append(m.Msg[:0], dAtA[iNdEx:postIndex]...)
			if m.Msg == nil {
				m.Msg = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Model) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Model: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Model: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWasm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWasm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SecurityStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SecurityStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SecurityStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCodesAnalyzed", wireType)
			}
			m.TotalCodesAnalyzed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCodesAnalyzed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodesRejected", wireType)
			}
			m.CodesRejected = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodesRejected |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractsPaused", wireType)
			}
			m.ContractsPaused = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractsPaused |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalExecutions", wireType)
			}
			m.TotalExecutions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalExecutions |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedExecutions", wireType)
			}
			m.FailedExecutions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FailedExecutions |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasConsumedTotal", wireType)
			}
			m.GasConsumedTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasConsumedTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSecurityScan", wireType)
			}
			m.LastSecurityScan = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSecurityScan |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AbsoluteTxPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AbsoluteTxPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AbsoluteTxPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxIndex", wireType)
			}
			m.TxIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWasm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWasm(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWasm
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWasm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWasm
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWasm
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWasm
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWasm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWasm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWasm = fmt.Errorf("proto: unexpected end of group")
)
