"""AURA Python SDK - Official Python SDK for AURA blockchain."""

from .client import AuraClient
from .wallet import AuraWallet
from .tx import TxBuilder
from .types import (
    ChainConfig,
    Pool,
    Validator,
    Proposal,
    VoteOption,
    TxResult,
)
from .errors import (
    AuraError,
    ConnectionError,
    NotConnectedError,
    EndpointError,
    WalletError,
    WalletNotInitializedError,
    InvalidMnemonicError,
    NoAccountsError,
    SigningError,
    TransactionError,
    TransactionBroadcastError,
    TransactionTimeoutError,
    InsufficientFundsError,
    GasEstimationError,
    QueryError,
    NotFoundError,
    InvalidResponseError,
    BridgeError,
    BridgeTransferError,
    UnsupportedChainError,
    IdentityError,
    DIDNotFoundError,
    ComplianceError,
    KYCRequiredError,
    DEXError,
    SlippageExceededError,
    PoolNotFoundError,
    ValidationError,
    InvalidAddressError,
    InvalidAmountError,
)

__version__ = "1.0.0"
__all__ = [
    # Core
    "AuraClient",
    "AuraWallet",
    "TxBuilder",
    # Types
    "ChainConfig",
    "Pool",
    "Validator",
    "Proposal",
    "VoteOption",
    "TxResult",
    # Errors
    "AuraError",
    "ConnectionError",
    "NotConnectedError",
    "EndpointError",
    "WalletError",
    "WalletNotInitializedError",
    "InvalidMnemonicError",
    "NoAccountsError",
    "SigningError",
    "TransactionError",
    "TransactionBroadcastError",
    "TransactionTimeoutError",
    "InsufficientFundsError",
    "GasEstimationError",
    "QueryError",
    "NotFoundError",
    "InvalidResponseError",
    "BridgeError",
    "BridgeTransferError",
    "UnsupportedChainError",
    "IdentityError",
    "DIDNotFoundError",
    "ComplianceError",
    "KYCRequiredError",
    "DEXError",
    "SlippageExceededError",
    "PoolNotFoundError",
    "ValidationError",
    "InvalidAddressError",
    "InvalidAmountError",
]
