"""AURA Python SDK - Official Python SDK for AURA blockchain."""

from .client import AuraClient
from .wallet import AuraWallet
from .tx import TxBuilder
from .types import (
    ChainConfig,
    Pool,
    Validator,
    Proposal,
    VoteOption,
    TxResult,
)
from .errors import (
    AuraError,
    ConnectionError,
    NotConnectedError,
    EndpointError,
    WalletError,
    WalletNotInitializedError,
    InvalidMnemonicError,
    NoAccountsError,
    SigningError,
    TransactionError,
    TransactionBroadcastError,
    TransactionTimeoutError,
    InsufficientFundsError,
    GasEstimationError,
    QueryError,
    NotFoundError,
    InvalidResponseError,
    BridgeError,
    BridgeTransferError,
    UnsupportedChainError,
    IdentityError,
    DIDNotFoundError,
    ComplianceError,
    KYCRequiredError,
    DEXError,
    SlippageExceededError,
    PoolNotFoundError,
    ValidationError,
    InvalidAddressError,
    InvalidAmountError,
)
from .events import (
    EventSubscriber,
    EventFilter,
    EventType,
    BlockEvent,
    TxEvent,
    TransferEvent,
    BridgeTransferEvent,
    IdentityEvent,
    GovernanceEvent,
    DEXEvent,
    create_event_subscriber,
)
from .batch import (
    BatchTransactionBuilder,
    BatchConfig,
    BatchResult,
    BatchQueryResult,
    BatchTransferItem,
    batch_queries,
    batch_queries_sync,
    create_batch_transfers,
    validate_batch_size,
    estimate_batch_gas,
    chunk,
)

__version__ = "1.0.0"
__all__ = [
    # Core
    "AuraClient",
    "AuraWallet",
    "TxBuilder",
    # Types
    "ChainConfig",
    "Pool",
    "Validator",
    "Proposal",
    "VoteOption",
    "TxResult",
    # Errors
    "AuraError",
    "ConnectionError",
    "NotConnectedError",
    "EndpointError",
    "WalletError",
    "WalletNotInitializedError",
    "InvalidMnemonicError",
    "NoAccountsError",
    "SigningError",
    "TransactionError",
    "TransactionBroadcastError",
    "TransactionTimeoutError",
    "InsufficientFundsError",
    "GasEstimationError",
    "QueryError",
    "NotFoundError",
    "InvalidResponseError",
    "BridgeError",
    "BridgeTransferError",
    "UnsupportedChainError",
    "IdentityError",
    "DIDNotFoundError",
    "ComplianceError",
    "KYCRequiredError",
    "DEXError",
    "SlippageExceededError",
    "PoolNotFoundError",
    "ValidationError",
    "InvalidAddressError",
    "InvalidAmountError",
    # Events
    "EventSubscriber",
    "EventFilter",
    "EventType",
    "BlockEvent",
    "TxEvent",
    "TransferEvent",
    "BridgeTransferEvent",
    "IdentityEvent",
    "GovernanceEvent",
    "DEXEvent",
    "create_event_subscriber",
    # Batch operations
    "BatchTransactionBuilder",
    "BatchConfig",
    "BatchResult",
    "BatchQueryResult",
    "BatchTransferItem",
    "batch_queries",
    "batch_queries_sync",
    "create_batch_transfers",
    "validate_batch_size",
    "estimate_batch_gas",
    "chunk",
]
