package types

import "errors"

var (
	ErrInvalidParam                = errors.New("invalid parameter")
	ErrInvalidRequest              = errors.New("invalid request")
	ErrPoolAlreadyExists           = errors.New("pool already exists")
	ErrPoolNotFound                = errors.New("pool not found")
	ErrInsufficientLiquidity       = errors.New("insufficient liquidity")
	ErrInsufficientPoolLiquidity   = errors.New("insufficient pool liquidity")
	ErrInsufficientLPTokens        = errors.New("insufficient LP tokens")
	ErrNotLiquidityProvider        = errors.New("not a liquidity provider")
	ErrSlippageExceeded            = errors.New("slippage exceeded")
	ErrSlippageTooHigh             = errors.New("slippage too high")
	ErrPriceImpactTooHigh          = errors.New("price impact too high")
	ErrCircuitBreakerActive        = errors.New("circuit breaker is active")
	ErrFrontRunningDetected        = errors.New("front-running detected")
	ErrDustAttack                  = errors.New("dust attack detected")
	ErrInsufficientBalance         = errors.New("insufficient balance")
	ErrOrderNotFound               = errors.New("order not found")
	ErrOrderAlreadyCanceled        = errors.New("order already canceled")
	ErrOrderAlreadyExecuted        = errors.New("order already executed")
	ErrHTLCNotFound                = errors.New("HTLC not found")
	ErrHTLCAlreadyClaimed          = errors.New("HTLC already claimed")
	ErrHTLCExpired                 = errors.New("HTLC expired")
	ErrInvalidSecret               = errors.New("invalid secret")
	ErrFlashLoanDetected           = errors.New("flash loan attack detected")
	ErrMEVDetected                 = errors.New("MEV attack detected")
	ErrTradeTooLarge               = errors.New("trade size exceeds maximum")
	ErrLiquidityLocked             = errors.New("liquidity is locked")
	ErrOrderManipulation           = errors.New("order manipulation detected")
	ErrWashTradingDetected         = errors.New("wash trading detected")
	ErrPoolCreationCooldown        = errors.New("pool creation cooldown active")
	ErrMaxPoolsExceeded            = errors.New("maximum pools per creator exceeded")
	ErrPoolCreationLimitExceeded   = errors.New("pool creation limit exceeded")
	ErrPriceManipulation           = errors.New("price manipulation detected")
	ErrCommitmentNotFound          = errors.New("order commitment not found")
	ErrRevealDeadlineExpired       = errors.New("reveal deadline has expired")
	ErrHashMismatch                = errors.New("commitment hash does not match revealed order")
	ErrCommitmentAlreadyExists     = errors.New("commitment already exists for this sender")
)
