package types

const (
	EventTypeSpendingLimitCheck        = "wallet_spending_limit_check"
	EventTypeDustTransaction           = "wallet_dust_transaction"
	EventTypeMultiSigWallet            = "multisig_wallet"
	EventTypeSocialRecovery            = "social_recovery"
	EventTypeInitiateRecovery          = "initiate_recovery"
	EventTypeExecuteRecovery           = "execute_recovery"
	EventTypeSessionCreated            = "session_created"
	EventTypeLockSession               = "lock_session"
	EventTypeSessionLocked             = "session_locked"
	EventTypeSessionTerminated         = "session_terminated"
	EventTypeEnrollBiometric           = "enroll_biometric"
	EventTypeBiometricAuth             = "biometric_auth"
	EventTypeRegisterHardwareWallet    = "register_hardware_wallet"
	EventTypeSignMultiSigTx            = "sign_multisig_tx"
	EventTypeVerifyDomain              = "verify_domain"
	EventTypeSetSpendingLimit          = "set_spending_limit"
	EventTypeUnlockSession             = "unlock_session"

	AttributeKeyWalletID   = "wallet_id"
	AttributeKeyDenom      = "denom"
	AttributeKeyAmount     = "amount"
	AttributeKeyStatus     = "status"
	AttributeKeyReason     = "reason"
	AttributeKeyTxHash     = "tx_hash"
	AttributeKeyFromAddr   = "from_address"
	AttributeKeyToAddr     = "to_address"
	AttributeKeyDustBlock  = "blocked"
	AttributeKeyRequestID  = "request_id"
	AttributeKeySessionID  = "session_id"
	AttributeKeyDeviceID   = "device_id"
	AttributeKeyAddress    = "address"
	AttributeKeyTxID       = "tx_id"
	AttributeKeySigner     = "signer"
	AttributeKeyDomain     = "domain"

	AttributeValueStatusAllowed = "allowed"
	AttributeValueStatusBlocked = "blocked"
)
