// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aura/dataregistry/v1beta1/data_registry.proto

package v1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DataItemType categorizes stored data
type DataItemType int32

const (
	DataItemType_DATA_ITEM_TYPE_UNSPECIFIED DataItemType = 0
	// Documents
	DataItemType_DATA_ITEM_TYPE_VEHICLE_REGISTRATION DataItemType = 1
	DataItemType_DATA_ITEM_TYPE_VEHICLE_INSURANCE    DataItemType = 2
	DataItemType_DATA_ITEM_TYPE_PROPERTY_DEED        DataItemType = 3
	DataItemType_DATA_ITEM_TYPE_LEASE_AGREEMENT      DataItemType = 4
	DataItemType_DATA_ITEM_TYPE_CONTRACT             DataItemType = 5
	DataItemType_DATA_ITEM_TYPE_RECEIPT              DataItemType = 6
	DataItemType_DATA_ITEM_TYPE_WARRANTY             DataItemType = 7
	// Media
	DataItemType_DATA_ITEM_TYPE_PHOTO        DataItemType = 10
	DataItemType_DATA_ITEM_TYPE_VIDEO        DataItemType = 11
	DataItemType_DATA_ITEM_TYPE_AUDIO        DataItemType = 12
	DataItemType_DATA_ITEM_TYPE_DOCUMENT_PDF DataItemType = 13
	// Scores & Achievements
	DataItemType_DATA_ITEM_TYPE_GOLF_SCORE    DataItemType = 20
	DataItemType_DATA_ITEM_TYPE_TEST_SCORE    DataItemType = 21
	DataItemType_DATA_ITEM_TYPE_CERTIFICATION DataItemType = 22
	DataItemType_DATA_ITEM_TYPE_ACHIEVEMENT   DataItemType = 23
	// Digital Assets
	DataItemType_DATA_ITEM_TYPE_NFT           DataItemType = 30
	DataItemType_DATA_ITEM_TYPE_DIGITAL_ART   DataItemType = 31
	DataItemType_DATA_ITEM_TYPE_MUSIC_LICENSE DataItemType = 32
	// Health
	DataItemType_DATA_ITEM_TYPE_VACCINATION_RECORD DataItemType = 40
	DataItemType_DATA_ITEM_TYPE_MEDICAL_RECORD     DataItemType = 41
	DataItemType_DATA_ITEM_TYPE_PRESCRIPTION       DataItemType = 42
	// Custom
	DataItemType_DATA_ITEM_TYPE_CUSTOM DataItemType = 100
)

var DataItemType_name = map[int32]string{
	0:   "DATA_ITEM_TYPE_UNSPECIFIED",
	1:   "DATA_ITEM_TYPE_VEHICLE_REGISTRATION",
	2:   "DATA_ITEM_TYPE_VEHICLE_INSURANCE",
	3:   "DATA_ITEM_TYPE_PROPERTY_DEED",
	4:   "DATA_ITEM_TYPE_LEASE_AGREEMENT",
	5:   "DATA_ITEM_TYPE_CONTRACT",
	6:   "DATA_ITEM_TYPE_RECEIPT",
	7:   "DATA_ITEM_TYPE_WARRANTY",
	10:  "DATA_ITEM_TYPE_PHOTO",
	11:  "DATA_ITEM_TYPE_VIDEO",
	12:  "DATA_ITEM_TYPE_AUDIO",
	13:  "DATA_ITEM_TYPE_DOCUMENT_PDF",
	20:  "DATA_ITEM_TYPE_GOLF_SCORE",
	21:  "DATA_ITEM_TYPE_TEST_SCORE",
	22:  "DATA_ITEM_TYPE_CERTIFICATION",
	23:  "DATA_ITEM_TYPE_ACHIEVEMENT",
	30:  "DATA_ITEM_TYPE_NFT",
	31:  "DATA_ITEM_TYPE_DIGITAL_ART",
	32:  "DATA_ITEM_TYPE_MUSIC_LICENSE",
	40:  "DATA_ITEM_TYPE_VACCINATION_RECORD",
	41:  "DATA_ITEM_TYPE_MEDICAL_RECORD",
	42:  "DATA_ITEM_TYPE_PRESCRIPTION",
	100: "DATA_ITEM_TYPE_CUSTOM",
}

var DataItemType_value = map[string]int32{
	"DATA_ITEM_TYPE_UNSPECIFIED":          0,
	"DATA_ITEM_TYPE_VEHICLE_REGISTRATION": 1,
	"DATA_ITEM_TYPE_VEHICLE_INSURANCE":    2,
	"DATA_ITEM_TYPE_PROPERTY_DEED":        3,
	"DATA_ITEM_TYPE_LEASE_AGREEMENT":      4,
	"DATA_ITEM_TYPE_CONTRACT":             5,
	"DATA_ITEM_TYPE_RECEIPT":              6,
	"DATA_ITEM_TYPE_WARRANTY":             7,
	"DATA_ITEM_TYPE_PHOTO":                10,
	"DATA_ITEM_TYPE_VIDEO":                11,
	"DATA_ITEM_TYPE_AUDIO":                12,
	"DATA_ITEM_TYPE_DOCUMENT_PDF":         13,
	"DATA_ITEM_TYPE_GOLF_SCORE":           20,
	"DATA_ITEM_TYPE_TEST_SCORE":           21,
	"DATA_ITEM_TYPE_CERTIFICATION":        22,
	"DATA_ITEM_TYPE_ACHIEVEMENT":          23,
	"DATA_ITEM_TYPE_NFT":                  30,
	"DATA_ITEM_TYPE_DIGITAL_ART":          31,
	"DATA_ITEM_TYPE_MUSIC_LICENSE":        32,
	"DATA_ITEM_TYPE_VACCINATION_RECORD":   40,
	"DATA_ITEM_TYPE_MEDICAL_RECORD":       41,
	"DATA_ITEM_TYPE_PRESCRIPTION":         42,
	"DATA_ITEM_TYPE_CUSTOM":               100,
}

func (x DataItemType) String() string {
	return proto.EnumName(DataItemType_name, int32(x))
}

func (DataItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{0}
}

// DataItemStatus represents lifecycle
type DataItemStatus int32

const (
	DataItemStatus_DATA_ITEM_STATUS_UNSPECIFIED          DataItemStatus = 0
	DataItemStatus_DATA_ITEM_STATUS_PENDING_VERIFICATION DataItemStatus = 1
	DataItemStatus_DATA_ITEM_STATUS_VERIFIED             DataItemStatus = 2
	DataItemStatus_DATA_ITEM_STATUS_REJECTED             DataItemStatus = 3
	DataItemStatus_DATA_ITEM_STATUS_EXPIRED              DataItemStatus = 4
	DataItemStatus_DATA_ITEM_STATUS_REVOKED              DataItemStatus = 5
)

var DataItemStatus_name = map[int32]string{
	0: "DATA_ITEM_STATUS_UNSPECIFIED",
	1: "DATA_ITEM_STATUS_PENDING_VERIFICATION",
	2: "DATA_ITEM_STATUS_VERIFIED",
	3: "DATA_ITEM_STATUS_REJECTED",
	4: "DATA_ITEM_STATUS_EXPIRED",
	5: "DATA_ITEM_STATUS_REVOKED",
}

var DataItemStatus_value = map[string]int32{
	"DATA_ITEM_STATUS_UNSPECIFIED":          0,
	"DATA_ITEM_STATUS_PENDING_VERIFICATION": 1,
	"DATA_ITEM_STATUS_VERIFIED":             2,
	"DATA_ITEM_STATUS_REJECTED":             3,
	"DATA_ITEM_STATUS_EXPIRED":              4,
	"DATA_ITEM_STATUS_REVOKED":              5,
}

func (x DataItemStatus) String() string {
	return proto.EnumName(DataItemStatus_name, int32(x))
}

func (DataItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{1}
}

// VerificationLevel indicates trust level
type VerificationLevel int32

const (
	VerificationLevel_VERIFICATION_LEVEL_UNSPECIFIED         VerificationLevel = 0
	VerificationLevel_VERIFICATION_LEVEL_SELF_ATTESTED       VerificationLevel = 1
	VerificationLevel_VERIFICATION_LEVEL_PEER_VERIFIED       VerificationLevel = 2
	VerificationLevel_VERIFICATION_LEVEL_AI_VERIFIED         VerificationLevel = 3
	VerificationLevel_VERIFICATION_LEVEL_AUTHORITY_VERIFIED  VerificationLevel = 4
	VerificationLevel_VERIFICATION_LEVEL_BLOCKCHAIN_ANCHORED VerificationLevel = 5
)

var VerificationLevel_name = map[int32]string{
	0: "VERIFICATION_LEVEL_UNSPECIFIED",
	1: "VERIFICATION_LEVEL_SELF_ATTESTED",
	2: "VERIFICATION_LEVEL_PEER_VERIFIED",
	3: "VERIFICATION_LEVEL_AI_VERIFIED",
	4: "VERIFICATION_LEVEL_AUTHORITY_VERIFIED",
	5: "VERIFICATION_LEVEL_BLOCKCHAIN_ANCHORED",
}

var VerificationLevel_value = map[string]int32{
	"VERIFICATION_LEVEL_UNSPECIFIED":         0,
	"VERIFICATION_LEVEL_SELF_ATTESTED":       1,
	"VERIFICATION_LEVEL_PEER_VERIFIED":       2,
	"VERIFICATION_LEVEL_AI_VERIFIED":         3,
	"VERIFICATION_LEVEL_AUTHORITY_VERIFIED":  4,
	"VERIFICATION_LEVEL_BLOCKCHAIN_ANCHORED": 5,
}

func (x VerificationLevel) String() string {
	return proto.EnumName(VerificationLevel_name, int32(x))
}

func (VerificationLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{2}
}

// AccessMode defines visibility policy
type AccessMode int32

const (
	AccessMode_ACCESS_MODE_PRIVATE        AccessMode = 0
	AccessMode_ACCESS_MODE_WHITELIST      AccessMode = 1
	AccessMode_ACCESS_MODE_PUBLIC         AccessMode = 2
	AccessMode_ACCESS_MODE_VERIFIED_USERS AccessMode = 3
)

var AccessMode_name = map[int32]string{
	0: "ACCESS_MODE_PRIVATE",
	1: "ACCESS_MODE_WHITELIST",
	2: "ACCESS_MODE_PUBLIC",
	3: "ACCESS_MODE_VERIFIED_USERS",
}

var AccessMode_value = map[string]int32{
	"ACCESS_MODE_PRIVATE":        0,
	"ACCESS_MODE_WHITELIST":      1,
	"ACCESS_MODE_PUBLIC":         2,
	"ACCESS_MODE_VERIFIED_USERS": 3,
}

func (x AccessMode) String() string {
	return proto.EnumName(AccessMode_name, int32(x))
}

func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{3}
}

// GeoLocation for geotagged data
type GeoLocation struct {
	Latitude             float64          `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64          `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64          `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	AccuracyMeters       float64          `protobuf:"fixed64,4,opt,name=accuracy_meters,json=accuracyMeters,proto3" json:"accuracy_meters,omitempty"`
	Timestamp            *types.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LocationName         string           `protobuf:"bytes,6,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GeoLocation) Reset()         { *m = GeoLocation{} }
func (m *GeoLocation) String() string { return proto.CompactTextString(m) }
func (*GeoLocation) ProtoMessage()    {}
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{0}
}
func (m *GeoLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoLocation.Unmarshal(m, b)
}
func (m *GeoLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoLocation.Marshal(b, m, deterministic)
}
func (m *GeoLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoLocation.Merge(m, src)
}
func (m *GeoLocation) XXX_Size() int {
	return xxx_messageInfo_GeoLocation.Size(m)
}
func (m *GeoLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GeoLocation proto.InternalMessageInfo

func (m *GeoLocation) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GeoLocation) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GeoLocation) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *GeoLocation) GetAccuracyMeters() float64 {
	if m != nil {
		return m.AccuracyMeters
	}
	return 0
}

func (m *GeoLocation) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GeoLocation) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

// Verification record
type Verification struct {
	VerifierAddress      string            `protobuf:"bytes,1,opt,name=verifier_address,json=verifierAddress,proto3" json:"verifier_address,omitempty"`
	Level                VerificationLevel `protobuf:"varint,2,opt,name=level,proto3,enum=aura.dataregistry.v1beta1.VerificationLevel" json:"level,omitempty"`
	VerifiedAt           *types.Timestamp  `protobuf:"bytes,3,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	VerificationMethod   string            `protobuf:"bytes,4,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	ConfidenceScore      uint64            `protobuf:"varint,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Notes                string            `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Proof                []byte            `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Verification) Reset()         { *m = Verification{} }
func (m *Verification) String() string { return proto.CompactTextString(m) }
func (*Verification) ProtoMessage()    {}
func (*Verification) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{1}
}
func (m *Verification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verification.Unmarshal(m, b)
}
func (m *Verification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verification.Marshal(b, m, deterministic)
}
func (m *Verification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verification.Merge(m, src)
}
func (m *Verification) XXX_Size() int {
	return xxx_messageInfo_Verification.Size(m)
}
func (m *Verification) XXX_DiscardUnknown() {
	xxx_messageInfo_Verification.DiscardUnknown(m)
}

var xxx_messageInfo_Verification proto.InternalMessageInfo

func (m *Verification) GetVerifierAddress() string {
	if m != nil {
		return m.VerifierAddress
	}
	return ""
}

func (m *Verification) GetLevel() VerificationLevel {
	if m != nil {
		return m.Level
	}
	return VerificationLevel_VERIFICATION_LEVEL_UNSPECIFIED
}

func (m *Verification) GetVerifiedAt() *types.Timestamp {
	if m != nil {
		return m.VerifiedAt
	}
	return nil
}

func (m *Verification) GetVerificationMethod() string {
	if m != nil {
		return m.VerificationMethod
	}
	return ""
}

func (m *Verification) GetConfidenceScore() uint64 {
	if m != nil {
		return m.ConfidenceScore
	}
	return 0
}

func (m *Verification) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Verification) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

// AccessPolicy controls who can view data
type AccessPolicy struct {
	Mode                    AccessMode `protobuf:"varint,1,opt,name=mode,proto3,enum=aura.dataregistry.v1beta1.AccessMode" json:"mode,omitempty"`
	AllowedAddresses        []string   `protobuf:"bytes,2,rep,name=allowed_addresses,json=allowedAddresses,proto3" json:"allowed_addresses,omitempty"`
	DeniedAddresses         []string   `protobuf:"bytes,3,rep,name=denied_addresses,json=deniedAddresses,proto3" json:"denied_addresses,omitempty"`
	RequireVerifiedIdentity bool       `protobuf:"varint,4,opt,name=require_verified_identity,json=requireVerifiedIdentity,proto3" json:"require_verified_identity,omitempty"`
	MinConfidenceScore      uint64     `protobuf:"varint,5,opt,name=min_confidence_score,json=minConfidenceScore,proto3" json:"min_confidence_score,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}   `json:"-"`
	XXX_unrecognized        []byte     `json:"-"`
	XXX_sizecache           int32      `json:"-"`
}

func (m *AccessPolicy) Reset()         { *m = AccessPolicy{} }
func (m *AccessPolicy) String() string { return proto.CompactTextString(m) }
func (*AccessPolicy) ProtoMessage()    {}
func (*AccessPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{2}
}
func (m *AccessPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessPolicy.Unmarshal(m, b)
}
func (m *AccessPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessPolicy.Marshal(b, m, deterministic)
}
func (m *AccessPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessPolicy.Merge(m, src)
}
func (m *AccessPolicy) XXX_Size() int {
	return xxx_messageInfo_AccessPolicy.Size(m)
}
func (m *AccessPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_AccessPolicy proto.InternalMessageInfo

func (m *AccessPolicy) GetMode() AccessMode {
	if m != nil {
		return m.Mode
	}
	return AccessMode_ACCESS_MODE_PRIVATE
}

func (m *AccessPolicy) GetAllowedAddresses() []string {
	if m != nil {
		return m.AllowedAddresses
	}
	return nil
}

func (m *AccessPolicy) GetDeniedAddresses() []string {
	if m != nil {
		return m.DeniedAddresses
	}
	return nil
}

func (m *AccessPolicy) GetRequireVerifiedIdentity() bool {
	if m != nil {
		return m.RequireVerifiedIdentity
	}
	return false
}

func (m *AccessPolicy) GetMinConfidenceScore() uint64 {
	if m != nil {
		return m.MinConfidenceScore
	}
	return 0
}

// DataItem represents a stored data item
type DataItem struct {
	DataId            string            `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	OwnerAddress      string            `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	DataType          DataItemType      `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3,enum=aura.dataregistry.v1beta1.DataItemType" json:"data_type,omitempty"`
	DataTypeCustom    string            `protobuf:"bytes,4,opt,name=data_type_custom,json=dataTypeCustom,proto3" json:"data_type_custom,omitempty"`
	Status            DataItemStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=aura.dataregistry.v1beta1.DataItemStatus" json:"status,omitempty"`
	VerificationLevel VerificationLevel `protobuf:"varint,6,opt,name=verification_level,json=verificationLevel,proto3,enum=aura.dataregistry.v1beta1.VerificationLevel" json:"verification_level,omitempty"`
	// Content (stored off-chain or encrypted)
	ContentHash       []byte `protobuf:"bytes,7,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	StorageLocation   string `protobuf:"bytes,8,opt,name=storage_location,json=storageLocation,proto3" json:"storage_location,omitempty"`
	IsEncrypted       bool   `protobuf:"varint,9,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptionKeyHash []byte `protobuf:"bytes,10,opt,name=encryption_key_hash,json=encryptionKeyHash,proto3" json:"encryption_key_hash,omitempty"`
	// Metadata
	Title       string            `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	Description string            `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tags        []string          `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// Temporal/Geospatial
	CreatedAt   *types.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VerifiedAt  *types.Timestamp `protobuf:"bytes,16,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt   *types.Timestamp `protobuf:"bytes,17,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	GeoLocation *GeoLocation     `protobuf:"bytes,18,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	// Verification
	Verifications []*Verification `protobuf:"bytes,19,rep,name=verifications,proto3" json:"verifications,omitempty"`
	VerifiedBy    string          `protobuf:"bytes,20,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	// Access control
	AccessPolicy *AccessPolicy `protobuf:"bytes,21,opt,name=access_policy,json=accessPolicy,proto3" json:"access_policy,omitempty"`
	// Provenance
	PreviousDataId       string   `protobuf:"bytes,22,opt,name=previous_data_id,json=previousDataId,proto3" json:"previous_data_id,omitempty"`
	Version              uint64   `protobuf:"varint,23,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataItem) Reset()         { *m = DataItem{} }
func (m *DataItem) String() string { return proto.CompactTextString(m) }
func (*DataItem) ProtoMessage()    {}
func (*DataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{3}
}
func (m *DataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataItem.Unmarshal(m, b)
}
func (m *DataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataItem.Marshal(b, m, deterministic)
}
func (m *DataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataItem.Merge(m, src)
}
func (m *DataItem) XXX_Size() int {
	return xxx_messageInfo_DataItem.Size(m)
}
func (m *DataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DataItem.DiscardUnknown(m)
}

var xxx_messageInfo_DataItem proto.InternalMessageInfo

func (m *DataItem) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *DataItem) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *DataItem) GetDataType() DataItemType {
	if m != nil {
		return m.DataType
	}
	return DataItemType_DATA_ITEM_TYPE_UNSPECIFIED
}

func (m *DataItem) GetDataTypeCustom() string {
	if m != nil {
		return m.DataTypeCustom
	}
	return ""
}

func (m *DataItem) GetStatus() DataItemStatus {
	if m != nil {
		return m.Status
	}
	return DataItemStatus_DATA_ITEM_STATUS_UNSPECIFIED
}

func (m *DataItem) GetVerificationLevel() VerificationLevel {
	if m != nil {
		return m.VerificationLevel
	}
	return VerificationLevel_VERIFICATION_LEVEL_UNSPECIFIED
}

func (m *DataItem) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *DataItem) GetStorageLocation() string {
	if m != nil {
		return m.StorageLocation
	}
	return ""
}

func (m *DataItem) GetIsEncrypted() bool {
	if m != nil {
		return m.IsEncrypted
	}
	return false
}

func (m *DataItem) GetEncryptionKeyHash() []byte {
	if m != nil {
		return m.EncryptionKeyHash
	}
	return nil
}

func (m *DataItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DataItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataItem) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DataItem) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DataItem) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DataItem) GetVerifiedAt() *types.Timestamp {
	if m != nil {
		return m.VerifiedAt
	}
	return nil
}

func (m *DataItem) GetExpiresAt() *types.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *DataItem) GetGeoLocation() *GeoLocation {
	if m != nil {
		return m.GeoLocation
	}
	return nil
}

func (m *DataItem) GetVerifications() []*Verification {
	if m != nil {
		return m.Verifications
	}
	return nil
}

func (m *DataItem) GetVerifiedBy() string {
	if m != nil {
		return m.VerifiedBy
	}
	return ""
}

func (m *DataItem) GetAccessPolicy() *AccessPolicy {
	if m != nil {
		return m.AccessPolicy
	}
	return nil
}

func (m *DataItem) GetPreviousDataId() string {
	if m != nil {
		return m.PreviousDataId
	}
	return ""
}

func (m *DataItem) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// Golf score with geotagging and timestamping
type GolfScoreData struct {
	CourseName           string           `protobuf:"bytes,1,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	Location             *GeoLocation     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	PlayedAt             *types.Timestamp `protobuf:"bytes,3,opt,name=played_at,json=playedAt,proto3" json:"played_at,omitempty"`
	TotalScore           uint32           `protobuf:"varint,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	HoleScores           []uint32         `protobuf:"varint,5,rep,packed,name=hole_scores,json=holeScores,proto3" json:"hole_scores,omitempty"`
	Handicap             uint32           `protobuf:"varint,6,opt,name=handicap,proto3" json:"handicap,omitempty"`
	ScorecardImageCid    string           `protobuf:"bytes,7,opt,name=scorecard_image_cid,json=scorecardImageCid,proto3" json:"scorecard_image_cid,omitempty"`
	PlayingPartners      []string         `protobuf:"bytes,8,rep,name=playing_partners,json=playingPartners,proto3" json:"playing_partners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GolfScoreData) Reset()         { *m = GolfScoreData{} }
func (m *GolfScoreData) String() string { return proto.CompactTextString(m) }
func (*GolfScoreData) ProtoMessage()    {}
func (*GolfScoreData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{4}
}
func (m *GolfScoreData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GolfScoreData.Unmarshal(m, b)
}
func (m *GolfScoreData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GolfScoreData.Marshal(b, m, deterministic)
}
func (m *GolfScoreData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GolfScoreData.Merge(m, src)
}
func (m *GolfScoreData) XXX_Size() int {
	return xxx_messageInfo_GolfScoreData.Size(m)
}
func (m *GolfScoreData) XXX_DiscardUnknown() {
	xxx_messageInfo_GolfScoreData.DiscardUnknown(m)
}

var xxx_messageInfo_GolfScoreData proto.InternalMessageInfo

func (m *GolfScoreData) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *GolfScoreData) GetLocation() *GeoLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GolfScoreData) GetPlayedAt() *types.Timestamp {
	if m != nil {
		return m.PlayedAt
	}
	return nil
}

func (m *GolfScoreData) GetTotalScore() uint32 {
	if m != nil {
		return m.TotalScore
	}
	return 0
}

func (m *GolfScoreData) GetHoleScores() []uint32 {
	if m != nil {
		return m.HoleScores
	}
	return nil
}

func (m *GolfScoreData) GetHandicap() uint32 {
	if m != nil {
		return m.Handicap
	}
	return 0
}

func (m *GolfScoreData) GetScorecardImageCid() string {
	if m != nil {
		return m.ScorecardImageCid
	}
	return ""
}

func (m *GolfScoreData) GetPlayingPartners() []string {
	if m != nil {
		return m.PlayingPartners
	}
	return nil
}

// Vehicle registration data
type VehicleRegistrationData struct {
	Vin                  string           `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Make                 string           `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model                string           `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year                 uint32           `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	LicensePlate         string           `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	State                string           `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	RegisteredAt         *types.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	ExpiresAt            *types.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RegistrationImageCid string           `protobuf:"bytes,9,opt,name=registration_image_cid,json=registrationImageCid,proto3" json:"registration_image_cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VehicleRegistrationData) Reset()         { *m = VehicleRegistrationData{} }
func (m *VehicleRegistrationData) String() string { return proto.CompactTextString(m) }
func (*VehicleRegistrationData) ProtoMessage()    {}
func (*VehicleRegistrationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{5}
}
func (m *VehicleRegistrationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleRegistrationData.Unmarshal(m, b)
}
func (m *VehicleRegistrationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleRegistrationData.Marshal(b, m, deterministic)
}
func (m *VehicleRegistrationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleRegistrationData.Merge(m, src)
}
func (m *VehicleRegistrationData) XXX_Size() int {
	return xxx_messageInfo_VehicleRegistrationData.Size(m)
}
func (m *VehicleRegistrationData) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleRegistrationData.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleRegistrationData proto.InternalMessageInfo

func (m *VehicleRegistrationData) GetVin() string {
	if m != nil {
		return m.Vin
	}
	return ""
}

func (m *VehicleRegistrationData) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *VehicleRegistrationData) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *VehicleRegistrationData) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *VehicleRegistrationData) GetLicensePlate() string {
	if m != nil {
		return m.LicensePlate
	}
	return ""
}

func (m *VehicleRegistrationData) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *VehicleRegistrationData) GetRegisteredAt() *types.Timestamp {
	if m != nil {
		return m.RegisteredAt
	}
	return nil
}

func (m *VehicleRegistrationData) GetExpiresAt() *types.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *VehicleRegistrationData) GetRegistrationImageCid() string {
	if m != nil {
		return m.RegistrationImageCid
	}
	return ""
}

// Photo with metadata
type PhotoData struct {
	PhotoCid             string           `protobuf:"bytes,1,opt,name=photo_cid,json=photoCid,proto3" json:"photo_cid,omitempty"`
	Location             *GeoLocation     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	TakenAt              *types.Timestamp `protobuf:"bytes,3,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	CameraModel          string           `protobuf:"bytes,4,opt,name=camera_model,json=cameraModel,proto3" json:"camera_model,omitempty"`
	Description          string           `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PeopleTagged         []string         `protobuf:"bytes,6,rep,name=people_tagged,json=peopleTagged,proto3" json:"people_tagged,omitempty"`
	Width                uint32           `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32           `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PhotoData) Reset()         { *m = PhotoData{} }
func (m *PhotoData) String() string { return proto.CompactTextString(m) }
func (*PhotoData) ProtoMessage()    {}
func (*PhotoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{6}
}
func (m *PhotoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoData.Unmarshal(m, b)
}
func (m *PhotoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoData.Marshal(b, m, deterministic)
}
func (m *PhotoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoData.Merge(m, src)
}
func (m *PhotoData) XXX_Size() int {
	return xxx_messageInfo_PhotoData.Size(m)
}
func (m *PhotoData) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoData.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoData proto.InternalMessageInfo

func (m *PhotoData) GetPhotoCid() string {
	if m != nil {
		return m.PhotoCid
	}
	return ""
}

func (m *PhotoData) GetLocation() *GeoLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *PhotoData) GetTakenAt() *types.Timestamp {
	if m != nil {
		return m.TakenAt
	}
	return nil
}

func (m *PhotoData) GetCameraModel() string {
	if m != nil {
		return m.CameraModel
	}
	return ""
}

func (m *PhotoData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PhotoData) GetPeopleTagged() []string {
	if m != nil {
		return m.PeopleTagged
	}
	return nil
}

func (m *PhotoData) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PhotoData) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// Params for module configuration
type Params struct {
	MaxDataItemsPerUser  uint64   `protobuf:"varint,1,opt,name=max_data_items_per_user,json=maxDataItemsPerUser,proto3" json:"max_data_items_per_user,omitempty"`
	MaxStorageBytes      uint64   `protobuf:"varint,2,opt,name=max_storage_bytes,json=maxStorageBytes,proto3" json:"max_storage_bytes,omitempty"`
	StorageFee           string   `protobuf:"bytes,3,opt,name=storage_fee,json=storageFee,proto3" json:"storage_fee,omitempty"`
	VerificationReward   uint64   `protobuf:"varint,4,opt,name=verification_reward,json=verificationReward,proto3" json:"verification_reward,omitempty"`
	AuthorizedVerifiers  []string `protobuf:"bytes,5,rep,name=authorized_verifiers,json=authorizedVerifiers,proto3" json:"authorized_verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{7}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxDataItemsPerUser() uint64 {
	if m != nil {
		return m.MaxDataItemsPerUser
	}
	return 0
}

func (m *Params) GetMaxStorageBytes() uint64 {
	if m != nil {
		return m.MaxStorageBytes
	}
	return 0
}

func (m *Params) GetStorageFee() string {
	if m != nil {
		return m.StorageFee
	}
	return ""
}

func (m *Params) GetVerificationReward() uint64 {
	if m != nil {
		return m.VerificationReward
	}
	return 0
}

func (m *Params) GetAuthorizedVerifiers() []string {
	if m != nil {
		return m.AuthorizedVerifiers
	}
	return nil
}

// GenesisState defines the initial state of the dataregistry module
type GenesisState struct {
	Params               *Params     `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	DataItems            []*DataItem `protobuf:"bytes,2,rep,name=data_items,json=dataItems,proto3" json:"data_items,omitempty"`
	NextDataId           uint64      `protobuf:"varint,3,opt,name=next_data_id,json=nextDataId,proto3" json:"next_data_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{8}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetDataItems() []*DataItem {
	if m != nil {
		return m.DataItems
	}
	return nil
}

func (m *GenesisState) GetNextDataId() uint64 {
	if m != nil {
		return m.NextDataId
	}
	return 0
}

// EventDataItemStored is emitted when a data item is stored
type EventDataItemStored struct {
	DataId               string           `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	DataType             DataItemType     `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=aura.dataregistry.v1beta1.DataItemType" json:"data_type,omitempty"`
	OwnerAddress         string           `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	StorageLocation      string           `protobuf:"bytes,4,opt,name=storage_location,json=storageLocation,proto3" json:"storage_location,omitempty"`
	CreatedAt            *types.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BlockHeight          uint64           `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventDataItemStored) Reset()         { *m = EventDataItemStored{} }
func (m *EventDataItemStored) String() string { return proto.CompactTextString(m) }
func (*EventDataItemStored) ProtoMessage()    {}
func (*EventDataItemStored) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{9}
}
func (m *EventDataItemStored) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataItemStored.Unmarshal(m, b)
}
func (m *EventDataItemStored) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataItemStored.Marshal(b, m, deterministic)
}
func (m *EventDataItemStored) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataItemStored.Merge(m, src)
}
func (m *EventDataItemStored) XXX_Size() int {
	return xxx_messageInfo_EventDataItemStored.Size(m)
}
func (m *EventDataItemStored) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataItemStored.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataItemStored proto.InternalMessageInfo

func (m *EventDataItemStored) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *EventDataItemStored) GetDataType() DataItemType {
	if m != nil {
		return m.DataType
	}
	return DataItemType_DATA_ITEM_TYPE_UNSPECIFIED
}

func (m *EventDataItemStored) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *EventDataItemStored) GetStorageLocation() string {
	if m != nil {
		return m.StorageLocation
	}
	return ""
}

func (m *EventDataItemStored) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EventDataItemStored) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// EventDataItemUpdated is emitted when a data item is updated
type EventDataItemUpdated struct {
	DataId               string           `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	OwnerAddress         string           `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	UpdatedAt            *types.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BlockHeight          uint64           `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventDataItemUpdated) Reset()         { *m = EventDataItemUpdated{} }
func (m *EventDataItemUpdated) String() string { return proto.CompactTextString(m) }
func (*EventDataItemUpdated) ProtoMessage()    {}
func (*EventDataItemUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{10}
}
func (m *EventDataItemUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataItemUpdated.Unmarshal(m, b)
}
func (m *EventDataItemUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataItemUpdated.Marshal(b, m, deterministic)
}
func (m *EventDataItemUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataItemUpdated.Merge(m, src)
}
func (m *EventDataItemUpdated) XXX_Size() int {
	return xxx_messageInfo_EventDataItemUpdated.Size(m)
}
func (m *EventDataItemUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataItemUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataItemUpdated proto.InternalMessageInfo

func (m *EventDataItemUpdated) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *EventDataItemUpdated) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *EventDataItemUpdated) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *EventDataItemUpdated) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// EventDataItemDeleted is emitted when a data item is deleted
type EventDataItemDeleted struct {
	DataId               string           `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	OwnerAddress         string           `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	DeletedAt            *types.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	BlockHeight          uint64           `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventDataItemDeleted) Reset()         { *m = EventDataItemDeleted{} }
func (m *EventDataItemDeleted) String() string { return proto.CompactTextString(m) }
func (*EventDataItemDeleted) ProtoMessage()    {}
func (*EventDataItemDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{11}
}
func (m *EventDataItemDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataItemDeleted.Unmarshal(m, b)
}
func (m *EventDataItemDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataItemDeleted.Marshal(b, m, deterministic)
}
func (m *EventDataItemDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataItemDeleted.Merge(m, src)
}
func (m *EventDataItemDeleted) XXX_Size() int {
	return xxx_messageInfo_EventDataItemDeleted.Size(m)
}
func (m *EventDataItemDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataItemDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataItemDeleted proto.InternalMessageInfo

func (m *EventDataItemDeleted) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *EventDataItemDeleted) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *EventDataItemDeleted) GetDeletedAt() *types.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *EventDataItemDeleted) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// EventDataItemVerified is emitted when a data item is verified
type EventDataItemVerified struct {
	DataId               string            `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	VerifierAddress      string            `protobuf:"bytes,2,opt,name=verifier_address,json=verifierAddress,proto3" json:"verifier_address,omitempty"`
	Level                VerificationLevel `protobuf:"varint,3,opt,name=level,proto3,enum=aura.dataregistry.v1beta1.VerificationLevel" json:"level,omitempty"`
	ConfidenceScore      uint64            `protobuf:"varint,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	VerifiedAt           *types.Timestamp  `protobuf:"bytes,5,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	BlockHeight          uint64            `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventDataItemVerified) Reset()         { *m = EventDataItemVerified{} }
func (m *EventDataItemVerified) String() string { return proto.CompactTextString(m) }
func (*EventDataItemVerified) ProtoMessage()    {}
func (*EventDataItemVerified) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{12}
}
func (m *EventDataItemVerified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataItemVerified.Unmarshal(m, b)
}
func (m *EventDataItemVerified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataItemVerified.Marshal(b, m, deterministic)
}
func (m *EventDataItemVerified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataItemVerified.Merge(m, src)
}
func (m *EventDataItemVerified) XXX_Size() int {
	return xxx_messageInfo_EventDataItemVerified.Size(m)
}
func (m *EventDataItemVerified) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataItemVerified.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataItemVerified proto.InternalMessageInfo

func (m *EventDataItemVerified) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *EventDataItemVerified) GetVerifierAddress() string {
	if m != nil {
		return m.VerifierAddress
	}
	return ""
}

func (m *EventDataItemVerified) GetLevel() VerificationLevel {
	if m != nil {
		return m.Level
	}
	return VerificationLevel_VERIFICATION_LEVEL_UNSPECIFIED
}

func (m *EventDataItemVerified) GetConfidenceScore() uint64 {
	if m != nil {
		return m.ConfidenceScore
	}
	return 0
}

func (m *EventDataItemVerified) GetVerifiedAt() *types.Timestamp {
	if m != nil {
		return m.VerifiedAt
	}
	return nil
}

func (m *EventDataItemVerified) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// EventDataItemRevoked is emitted when a data item is revoked
type EventDataItemRevoked struct {
	DataId               string           `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Authority            string           `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Reason               string           `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedAt            *types.Timestamp `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	BlockHeight          uint64           `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventDataItemRevoked) Reset()         { *m = EventDataItemRevoked{} }
func (m *EventDataItemRevoked) String() string { return proto.CompactTextString(m) }
func (*EventDataItemRevoked) ProtoMessage()    {}
func (*EventDataItemRevoked) Descriptor() ([]byte, []int) {
	return fileDescriptor_2947d93931fa2afd, []int{13}
}
func (m *EventDataItemRevoked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataItemRevoked.Unmarshal(m, b)
}
func (m *EventDataItemRevoked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataItemRevoked.Marshal(b, m, deterministic)
}
func (m *EventDataItemRevoked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataItemRevoked.Merge(m, src)
}
func (m *EventDataItemRevoked) XXX_Size() int {
	return xxx_messageInfo_EventDataItemRevoked.Size(m)
}
func (m *EventDataItemRevoked) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataItemRevoked.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataItemRevoked proto.InternalMessageInfo

func (m *EventDataItemRevoked) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *EventDataItemRevoked) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *EventDataItemRevoked) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *EventDataItemRevoked) GetRevokedAt() *types.Timestamp {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func (m *EventDataItemRevoked) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("aura.dataregistry.v1beta1.DataItemType", DataItemType_name, DataItemType_value)
	proto.RegisterEnum("aura.dataregistry.v1beta1.DataItemStatus", DataItemStatus_name, DataItemStatus_value)
	proto.RegisterEnum("aura.dataregistry.v1beta1.VerificationLevel", VerificationLevel_name, VerificationLevel_value)
	proto.RegisterEnum("aura.dataregistry.v1beta1.AccessMode", AccessMode_name, AccessMode_value)
	proto.RegisterType((*GeoLocation)(nil), "aura.dataregistry.v1beta1.GeoLocation")
	proto.RegisterType((*Verification)(nil), "aura.dataregistry.v1beta1.Verification")
	proto.RegisterType((*AccessPolicy)(nil), "aura.dataregistry.v1beta1.AccessPolicy")
	proto.RegisterType((*DataItem)(nil), "aura.dataregistry.v1beta1.DataItem")
	proto.RegisterMapType((map[string]string)(nil), "aura.dataregistry.v1beta1.DataItem.MetadataEntry")
	proto.RegisterType((*GolfScoreData)(nil), "aura.dataregistry.v1beta1.GolfScoreData")
	proto.RegisterType((*VehicleRegistrationData)(nil), "aura.dataregistry.v1beta1.VehicleRegistrationData")
	proto.RegisterType((*PhotoData)(nil), "aura.dataregistry.v1beta1.PhotoData")
	proto.RegisterType((*Params)(nil), "aura.dataregistry.v1beta1.Params")
	proto.RegisterType((*GenesisState)(nil), "aura.dataregistry.v1beta1.GenesisState")
	proto.RegisterType((*EventDataItemStored)(nil), "aura.dataregistry.v1beta1.EventDataItemStored")
	proto.RegisterType((*EventDataItemUpdated)(nil), "aura.dataregistry.v1beta1.EventDataItemUpdated")
	proto.RegisterType((*EventDataItemDeleted)(nil), "aura.dataregistry.v1beta1.EventDataItemDeleted")
	proto.RegisterType((*EventDataItemVerified)(nil), "aura.dataregistry.v1beta1.EventDataItemVerified")
	proto.RegisterType((*EventDataItemRevoked)(nil), "aura.dataregistry.v1beta1.EventDataItemRevoked")
}

func init() {
	proto.RegisterFile("aura/dataregistry/v1beta1/data_registry.proto", fileDescriptor_2947d93931fa2afd)
}

var fileDescriptor_2947d93931fa2afd = []byte{
	// 2319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0xcd, 0x72, 0xdb, 0xc8,
	0xf1, 0x5f, 0x7e, 0x48, 0x26, 0x9b, 0xa4, 0x0c, 0x8d, 0x64, 0x8b, 0xd6, 0x7a, 0xd7, 0xb4, 0xbc,
	0xbb, 0x96, 0xf5, 0xff, 0x47, 0x8a, 0x95, 0x4d, 0x65, 0xbd, 0x7b, 0x48, 0x41, 0xe0, 0x48, 0x42,
	0x96, 0x5f, 0x35, 0x04, 0xb5, 0x71, 0x72, 0x40, 0x8d, 0xc0, 0x31, 0x89, 0x32, 0x09, 0x70, 0x81,
	0x21, 0x6d, 0xe6, 0x25, 0xf2, 0x0e, 0x39, 0xe6, 0x92, 0xaa, 0x5c, 0x73, 0x4b, 0x9e, 0x20, 0x97,
	0xe4, 0x0d, 0x52, 0xa9, 0xca, 0x21, 0x6f, 0x90, 0x4a, 0xcd, 0x0c, 0xc0, 0x2f, 0xc1, 0x92, 0xec,
	0xec, 0x8d, 0xf3, 0xeb, 0x5f, 0x03, 0xd3, 0xbf, 0xee, 0xe9, 0x69, 0x48, 0xf0, 0x23, 0x3a, 0x0e,
	0xe8, 0x51, 0x97, 0x72, 0x1a, 0xb0, 0x9e, 0x1b, 0xf2, 0x60, 0x7a, 0x34, 0x79, 0x7e, 0xc9, 0x38,
	0x7d, 0x2e, 0x41, 0x3b, 0x46, 0x0f, 0x47, 0x81, 0xcf, 0x7d, 0xf4, 0x40, 0xd0, 0x0f, 0x17, 0xe9,
	0x87, 0x11, 0x7d, 0xf7, 0x51, 0xcf, 0xf7, 0x7b, 0x03, 0x76, 0x24, 0x89, 0x97, 0xe3, 0x57, 0x47,
	0xdc, 0x1d, 0xb2, 0x90, 0xd3, 0xe1, 0x48, 0xf9, 0xee, 0x1e, 0x38, 0x7e, 0x38, 0xf4, 0xc3, 0xa3,
	0x4b, 0x1a, 0xb2, 0xa3, 0xef, 0xc7, 0x6c, 0xe1, 0x55, 0x23, 0xda, 0x73, 0x3d, 0xca, 0x5d, 0xdf,
	0x53, 0xdc, 0xbd, 0x7f, 0xa5, 0xa0, 0x70, 0xc6, 0xfc, 0x9a, 0xef, 0x48, 0x14, 0xed, 0x42, 0x6e,
	0x40, 0xb9, 0xcb, 0xc7, 0x5d, 0x56, 0x4e, 0x55, 0x52, 0xfb, 0x29, 0x32, 0x5b, 0xa3, 0x87, 0x90,
	0x1f, 0xf8, 0x5e, 0x4f, 0x19, 0xd3, 0xd2, 0x38, 0x07, 0x84, 0x27, 0x1d, 0x44, 0x9e, 0x19, 0xe5,
	0x19, 0xaf, 0xd1, 0x53, 0xb8, 0x4b, 0x1d, 0x67, 0x1c, 0x50, 0x67, 0x6a, 0x0f, 0x19, 0x67, 0x41,
	0x58, 0xce, 0x4a, 0xca, 0x46, 0x0c, 0xd7, 0x25, 0x8a, 0xbe, 0x82, 0xfc, 0x2c, 0x9a, 0xf2, 0x5a,
	0x25, 0xb5, 0x5f, 0x38, 0xde, 0x3d, 0x54, 0xf1, 0x1e, 0xc6, 0xf1, 0x1e, 0x5a, 0x31, 0x83, 0xcc,
	0xc9, 0xe8, 0x09, 0x94, 0x06, 0x51, 0x10, 0xb6, 0x47, 0x87, 0xac, 0xbc, 0x5e, 0x49, 0xed, 0xe7,
	0x49, 0x31, 0x06, 0x1b, 0x74, 0xc8, 0xf6, 0xfe, 0x9c, 0x86, 0xe2, 0x05, 0x0b, 0xdc, 0x57, 0x6e,
	0x14, 0xee, 0x33, 0xd0, 0x26, 0x72, 0xcd, 0x02, 0x9b, 0x76, 0xbb, 0x01, 0x0b, 0x43, 0x19, 0x76,
	0x9e, 0xdc, 0x8d, 0x71, 0x5d, 0xc1, 0xe8, 0x04, 0xd6, 0x06, 0x6c, 0xc2, 0x06, 0x32, 0xf2, 0x8d,
	0xe3, 0xff, 0x3f, 0x7c, 0x67, 0x86, 0x0e, 0x17, 0x5f, 0x51, 0x13, 0x3e, 0x44, 0xb9, 0xa2, 0x6f,
	0xa0, 0x10, 0x3d, 0xb6, 0x6b, 0x53, 0x2e, 0x65, 0xba, 0x3e, 0x40, 0x88, 0xe9, 0x3a, 0x47, 0x47,
	0xb0, 0x35, 0x59, 0x78, 0xb0, 0x10, 0xb2, 0xef, 0x77, 0xa5, 0x90, 0x79, 0x82, 0x16, 0x4d, 0x75,
	0x69, 0x11, 0xc1, 0x39, 0xbe, 0xf7, 0xca, 0xed, 0x32, 0xcf, 0x61, 0x76, 0xe8, 0xf8, 0x01, 0x93,
	0x9a, 0x66, 0xc9, 0xdd, 0x39, 0xde, 0x16, 0x30, 0xda, 0x86, 0x35, 0xcf, 0xe7, 0x2c, 0x8c, 0x54,
	0x53, 0x0b, 0x81, 0x8e, 0x02, 0xdf, 0x7f, 0x55, 0xbe, 0x53, 0x49, 0xed, 0x17, 0x89, 0x5a, 0xec,
	0xfd, 0x36, 0x0d, 0x45, 0xdd, 0x71, 0x58, 0x18, 0xb6, 0xfc, 0x81, 0xeb, 0x4c, 0xd1, 0x0b, 0xc8,
	0x0e, 0xfd, 0xa8, 0x5e, 0x36, 0x8e, 0x3f, 0xbf, 0x46, 0x18, 0xe5, 0x56, 0xf7, 0xbb, 0x8c, 0x48,
	0x17, 0xf4, 0x7f, 0xb0, 0x49, 0x07, 0x03, 0xff, 0x8d, 0xd0, 0x43, 0xe9, 0xcc, 0xc2, 0x72, 0xba,
	0x92, 0xd9, 0xcf, 0x13, 0x2d, 0x32, 0xe8, 0x31, 0x2e, 0xe2, 0xe9, 0x32, 0xcf, 0x5d, 0xe2, 0x66,
	0x24, 0xf7, 0xae, 0xc2, 0xe7, 0xd4, 0xaf, 0xe1, 0x41, 0xc0, 0xbe, 0x1f, 0xbb, 0x01, 0xb3, 0x67,
	0x82, 0x8b, 0x78, 0xb9, 0xcb, 0xa7, 0x52, 0xb1, 0x1c, 0xd9, 0x89, 0x08, 0x17, 0x91, 0xdd, 0x8c,
	0xcc, 0xe8, 0xc7, 0xb0, 0x3d, 0x74, 0x3d, 0xfb, 0x1d, 0xd2, 0xa1, 0xa1, 0xeb, 0x19, 0xcb, 0xea,
	0xed, 0xfd, 0x35, 0x0f, 0xb9, 0x2a, 0xe5, 0xd4, 0xe4, 0x6c, 0x88, 0x76, 0xe0, 0x8e, 0x3c, 0xd0,
	0x6e, 0x37, 0xaa, 0xa4, 0x75, 0xb1, 0x34, 0xbb, 0xa2, 0x42, 0xfd, 0x37, 0xde, 0x42, 0xa1, 0xa5,
	0x55, 0x85, 0x4a, 0x30, 0xae, 0xb2, 0x2a, 0xe4, 0xa5, 0x37, 0x9f, 0x8e, 0xd4, 0x31, 0xda, 0x38,
	0x7e, 0x7a, 0x8d, 0xa0, 0xf1, 0x5b, 0xad, 0xe9, 0x88, 0x91, 0x9c, 0xa0, 0x88, 0x5f, 0x68, 0x1f,
	0xb4, 0xd9, 0x53, 0x6c, 0x67, 0x1c, 0x72, 0x7f, 0x18, 0xd5, 0xc9, 0x46, 0xcc, 0x31, 0x24, 0x8a,
	0x74, 0x58, 0x0f, 0x39, 0xe5, 0xe3, 0x50, 0x86, 0xb7, 0x71, 0xfc, 0xec, 0x16, 0x2f, 0x6b, 0x4b,
	0x07, 0x12, 0x39, 0xa2, 0x5f, 0xc3, 0x52, 0xf1, 0xd9, 0xea, 0x94, 0xac, 0x7f, 0xc0, 0x29, 0xd9,
	0x9c, 0xac, 0x42, 0xe8, 0x31, 0x14, 0x1d, 0xdf, 0xe3, 0xcc, 0xe3, 0x76, 0x9f, 0x86, 0xfd, 0xa8,
	0x12, 0x0b, 0x11, 0x76, 0x4e, 0xc3, 0xbe, 0x28, 0x8b, 0x90, 0xfb, 0x01, 0xed, 0x31, 0x3b, 0x3e,
	0xec, 0xe5, 0x9c, 0x3a, 0xc3, 0x11, 0x3e, 0xeb, 0x6e, 0x8f, 0xa1, 0xe8, 0x86, 0x36, 0xf3, 0x9c,
	0x60, 0x3a, 0xe2, 0xac, 0x5b, 0xce, 0xcb, 0x4a, 0x28, 0xb8, 0x21, 0x8e, 0x21, 0x74, 0x08, 0x5b,
	0x91, 0x5d, 0xc4, 0xf2, 0x9a, 0x4d, 0xd5, 0x7b, 0x41, 0xbe, 0x77, 0x73, 0x6e, 0xfa, 0x96, 0x4d,
	0xe5, 0xdb, 0xb7, 0x61, 0x8d, 0xbb, 0x7c, 0xc0, 0xca, 0x05, 0x75, 0x72, 0xe4, 0x02, 0x55, 0xa0,
	0xd0, 0x65, 0xa1, 0x13, 0xb8, 0x92, 0x5b, 0x2e, 0x4a, 0xdb, 0x22, 0x84, 0xea, 0x90, 0x1b, 0x32,
	0x4e, 0x85, 0x32, 0xe5, 0x52, 0x25, 0xb3, 0x5f, 0x38, 0x7e, 0x7e, 0x0b, 0xe9, 0x0f, 0xeb, 0x91,
	0x0f, 0xf6, 0x78, 0x30, 0x25, 0xb3, 0x47, 0x20, 0x04, 0x59, 0x4e, 0x7b, 0x61, 0x79, 0x43, 0x9e,
	0x07, 0xf9, 0x1b, 0xbd, 0x00, 0x70, 0x02, 0x46, 0xb9, 0x6a, 0x36, 0x77, 0x6f, 0xee, 0xa6, 0x11,
	0x5b, 0xe7, 0xab, 0x8d, 0x4a, 0x7b, 0xaf, 0x46, 0xf5, 0x02, 0x80, 0xbd, 0x1d, 0xb9, 0x01, 0x0b,
	0x85, 0xef, 0xe6, 0xcd, 0xef, 0x8d, 0xd8, 0x3a, 0x47, 0x26, 0x14, 0x7b, 0xcc, 0x9f, 0xe7, 0x11,
	0x49, 0xe7, 0x2f, 0xae, 0x51, 0x66, 0xe1, 0xf2, 0x22, 0x85, 0xde, 0xc2, 0x4d, 0x56, 0x87, 0xd2,
	0x62, 0x39, 0x85, 0xe5, 0x2d, 0xa9, 0xf2, 0xd3, 0x5b, 0x56, 0x24, 0x59, 0xf6, 0x46, 0x8f, 0x16,
	0x14, 0xb9, 0x9c, 0x96, 0xb7, 0x65, 0x46, 0x67, 0x51, 0x9f, 0x4c, 0x51, 0x0d, 0x4a, 0x54, 0xb6,
	0x37, 0x7b, 0x24, 0xdb, 0x62, 0xf9, 0x9e, 0xdc, 0xfb, 0xd3, 0x1b, 0xdb, 0xa1, 0xea, 0xa2, 0xa4,
	0x48, 0x17, 0x7b, 0xea, 0x3e, 0x68, 0xa3, 0x80, 0x4d, 0x5c, 0x7f, 0x1c, 0xda, 0x71, 0x3b, 0xb9,
	0xaf, 0x4e, 0x70, 0x8c, 0x57, 0x55, 0x5b, 0x29, 0xc3, 0x9d, 0x09, 0x0b, 0x42, 0xa1, 0xd6, 0x8e,
	0xec, 0x50, 0xf1, 0x72, 0xf7, 0x1b, 0x28, 0x2d, 0x95, 0x0b, 0xd2, 0x20, 0xf3, 0x9a, 0x4d, 0xa3,
	0xb6, 0x24, 0x7e, 0x8a, 0xea, 0x9d, 0xd0, 0xc1, 0x98, 0x45, 0xbd, 0x48, 0x2d, 0xbe, 0x4e, 0x7f,
	0x95, 0xda, 0xfb, 0x47, 0x1a, 0x4a, 0x67, 0xfe, 0xe0, 0x95, 0xec, 0x70, 0xe2, 0x55, 0x42, 0x01,
	0xc7, 0x1f, 0x07, 0x21, 0x53, 0xf7, 0xab, 0x7a, 0x0a, 0x28, 0x48, 0xdc, 0xae, 0xe8, 0x04, 0x72,
	0xb3, 0xc4, 0xa5, 0xdf, 0x2b, 0x71, 0x33, 0x3f, 0xf4, 0x33, 0xc8, 0x8f, 0x06, 0x74, 0x7a, 0xdb,
	0xfb, 0x31, 0xa7, 0xc8, 0x3a, 0x17, 0xbb, 0xe3, 0x3e, 0xa7, 0x83, 0xa8, 0x59, 0x8b, 0x6e, 0x57,
	0x22, 0x20, 0x21, 0x75, 0xc5, 0x3d, 0x82, 0x42, 0xdf, 0x1f, 0x44, 0xcd, 0x5c, 0xb4, 0xbb, 0x8c,
	0x20, 0x08, 0x48, 0xda, 0x43, 0x31, 0xc0, 0xf4, 0xa9, 0xd7, 0x75, 0x1d, 0x3a, 0x92, 0xdd, 0xab,
	0x44, 0x66, 0x6b, 0xd1, 0x15, 0xa4, 0x9f, 0x43, 0x83, 0xae, 0xed, 0x0e, 0x45, 0xaf, 0x71, 0xdc,
	0xae, 0xec, 0x46, 0x79, 0xb2, 0x39, 0x33, 0x99, 0xc2, 0x62, 0xb8, 0xf2, 0xea, 0x15, 0x3b, 0x73,
	0xbd, 0x9e, 0x3d, 0xa2, 0x01, 0xf7, 0xc4, 0xc4, 0x93, 0x53, 0x57, 0x55, 0x84, 0xb7, 0x22, 0x78,
	0xef, 0x6f, 0x69, 0xd8, 0xb9, 0x60, 0x7d, 0xd7, 0x19, 0x30, 0xa2, 0x34, 0x92, 0x4a, 0x48, 0xc9,
	0x35, 0xc8, 0x4c, 0x5c, 0x2f, 0x4e, 0xd8, 0xc4, 0xf5, 0xc4, 0x39, 0x1f, 0xd2, 0xd7, 0x71, 0xbe,
	0xe4, 0x6f, 0x91, 0x44, 0x71, 0x99, 0x0e, 0xa4, 0x5e, 0x79, 0xa2, 0x16, 0x82, 0x39, 0x65, 0x34,
	0x88, 0x94, 0x90, 0xbf, 0xe5, 0x90, 0xe4, 0x3a, 0xcc, 0x0b, 0x99, 0x3d, 0x1a, 0x50, 0xae, 0xee,
	0x34, 0x31, 0x24, 0x29, 0xb0, 0x25, 0x30, 0xf1, 0x38, 0xd1, 0xd9, 0xe3, 0x09, 0x4a, 0x2d, 0xd0,
	0xcf, 0xa1, 0xa4, 0x52, 0xc8, 0x02, 0x95, 0x9c, 0x3b, 0x37, 0x26, 0xa7, 0x38, 0x77, 0xb8, 0xd2,
	0x15, 0x72, 0xef, 0xd3, 0x15, 0xbe, 0x84, 0xfb, 0xc1, 0x82, 0x34, 0x0b, 0x09, 0xc8, 0xcb, 0x2d,
	0x6e, 0x2f, 0x5a, 0xe3, 0x1c, 0xec, 0xfd, 0x29, 0x0d, 0xf9, 0x56, 0xdf, 0xe7, 0xbe, 0x94, 0xf2,
	0x63, 0xc8, 0x8f, 0xc4, 0x42, 0xba, 0x29, 0x41, 0x73, 0x12, 0x10, 0xe9, 0xfa, 0x21, 0x2a, 0xf7,
	0xa7, 0x90, 0xe3, 0xf4, 0x35, 0xf3, 0x6e, 0x57, 0xb8, 0x77, 0x24, 0x57, 0xe7, 0xf2, 0x82, 0xa3,
	0x43, 0x16, 0x50, 0x5b, 0xe5, 0x50, 0x5d, 0xd3, 0x05, 0x85, 0xd5, 0x65, 0x26, 0x57, 0x2e, 0x93,
	0xb5, 0xab, 0x97, 0xc9, 0x13, 0x28, 0x8d, 0x98, 0x3f, 0x1a, 0x30, 0x9b, 0xd3, 0x5e, 0x8f, 0x75,
	0xcb, 0xeb, 0xb2, 0xd6, 0x8a, 0x0a, 0xb4, 0x24, 0x26, 0xf2, 0xfa, 0xc6, 0xed, 0x72, 0x75, 0x87,
	0x96, 0x88, 0x5a, 0xa0, 0xfb, 0xb0, 0xde, 0x67, 0x6e, 0xaf, 0xaf, 0x52, 0x52, 0x22, 0xd1, 0x6a,
	0xef, 0xdf, 0x29, 0x58, 0x6f, 0xd1, 0x80, 0x0e, 0x43, 0xf4, 0x25, 0xec, 0x0c, 0xe9, 0xdb, 0xa8,
	0x0d, 0x71, 0x36, 0x0c, 0xed, 0x11, 0x0b, 0xec, 0x71, 0xc8, 0x02, 0x29, 0x64, 0x96, 0x6c, 0x0d,
	0xe9, 0xdb, 0xf8, 0x86, 0x0a, 0x5b, 0x2c, 0xe8, 0x84, 0x2c, 0x40, 0x07, 0xb0, 0x29, 0xbc, 0xe2,
	0xab, 0xf9, 0x72, 0xca, 0x99, 0x1a, 0x79, 0xb2, 0xe4, 0xee, 0x90, 0xbe, 0x6d, 0x2b, 0xfc, 0x44,
	0xc0, 0xe2, 0x6c, 0xc6, 0xbc, 0x57, 0x8c, 0x45, 0x75, 0x0c, 0x11, 0x74, 0xca, 0xd8, 0x95, 0xd9,
	0x37, 0x60, 0x6f, 0x68, 0xa0, 0x66, 0xdf, 0xec, 0xf2, 0xec, 0x4b, 0xa4, 0x05, 0x3d, 0x87, 0x6d,
	0x3a, 0xe6, 0x7d, 0x3f, 0x70, 0x7f, 0xc3, 0xba, 0xf1, 0x0c, 0x18, 0xa8, 0x63, 0x9f, 0x27, 0x5b,
	0x73, 0xdb, 0x45, 0x6c, 0xda, 0xfb, 0x43, 0x0a, 0x8a, 0x67, 0xcc, 0x63, 0xa1, 0x1b, 0xb6, 0x65,
	0xc9, 0xbf, 0x80, 0xf5, 0x91, 0x54, 0x40, 0x86, 0x59, 0x38, 0x7e, 0x7c, 0x4d, 0x4d, 0x28, 0xa9,
	0x48, 0xe4, 0x80, 0x4e, 0x00, 0xe6, 0x72, 0xc9, 0x81, 0xb6, 0x70, 0xfc, 0xe4, 0x16, 0xf7, 0x3b,
	0x91, 0xd3, 0x9f, 0xd4, 0x11, 0x55, 0xa0, 0xe8, 0xb1, 0xb7, 0x7c, 0xd6, 0xfe, 0x33, 0x32, 0x58,
	0x10, 0x98, 0x6a, 0xfd, 0x7b, 0xbf, 0x4b, 0xc3, 0x16, 0x9e, 0x30, 0x8f, 0xcf, 0x27, 0x33, 0x3f,
	0x60, 0xdd, 0x77, 0x8f, 0xa0, 0x4b, 0xd3, 0x65, 0xfa, 0x43, 0xa7, 0xcb, 0x2b, 0x83, 0x6c, 0x26,
	0x61, 0x90, 0x4d, 0x9a, 0xca, 0xb2, 0xc9, 0x53, 0xd9, 0xf2, 0x9c, 0xb2, 0xf6, 0x3e, 0x73, 0xca,
	0x63, 0x28, 0x5e, 0x0e, 0x7c, 0xe7, 0xb5, 0x1d, 0xd5, 0xf0, 0xba, 0xd4, 0xa8, 0x20, 0xb1, 0x73,
	0x55, 0xc8, 0x7f, 0x4c, 0xc1, 0xf6, 0x92, 0x48, 0x9d, 0x51, 0x57, 0x78, 0xff, 0x8f, 0x83, 0xfa,
	0x0b, 0x80, 0xb1, 0x7a, 0xd0, 0xed, 0x0e, 0x7c, 0x3e, 0x62, 0x27, 0x6c, 0x3a, 0x7b, 0x8b, 0x4d,
	0x57, 0xd9, 0x80, 0xfd, 0x20, 0x9b, 0xee, 0xaa, 0x07, 0xdd, 0x72, 0xd3, 0x11, 0xfb, 0x76, 0x9b,
	0xfe, 0x7d, 0x1a, 0xee, 0x2d, 0x6d, 0x3a, 0xfe, 0xb4, 0x7a, 0xf7, 0xae, 0x93, 0xbe, 0xbf, 0xd3,
	0x37, 0x7c, 0x7f, 0x67, 0x3e, 0xfc, 0xfb, 0x3b, 0xe9, 0x8b, 0x38, 0x9b, 0xfc, 0x45, 0xbc, 0x32,
	0x01, 0xaf, 0xbd, 0xd7, 0x04, 0x7c, 0x8b, 0xb2, 0xfc, 0xcb, 0x6a, 0x86, 0x09, 0x9b, 0xf8, 0xaf,
	0xaf, 0xd3, 0xea, 0x21, 0xe4, 0xa3, 0xb6, 0xc5, 0xa7, 0x91, 0x48, 0x73, 0x40, 0xf4, 0xf1, 0x80,
	0xd1, 0xd0, 0xf7, 0xa2, 0xd3, 0x18, 0xad, 0x44, 0xca, 0x03, 0xf5, 0x64, 0x11, 0x46, 0xf6, 0xe6,
	0x94, 0x47, 0xec, 0x84, 0x28, 0xd6, 0xae, 0x44, 0x71, 0xf0, 0xcf, 0x35, 0x28, 0x2e, 0x76, 0x09,
	0xf4, 0x29, 0xec, 0x56, 0x75, 0x4b, 0xb7, 0x4d, 0x0b, 0xd7, 0x6d, 0xeb, 0x65, 0x0b, 0xdb, 0x9d,
	0x46, 0xbb, 0x85, 0x0d, 0xf3, 0xd4, 0xc4, 0x55, 0xed, 0x23, 0xf4, 0x14, 0x9e, 0xac, 0xd8, 0x2f,
	0xf0, 0xb9, 0x69, 0xd4, 0xb0, 0x4d, 0xf0, 0x99, 0xd9, 0xb6, 0x88, 0x6e, 0x99, 0xcd, 0x86, 0x96,
	0x42, 0x9f, 0x41, 0xe5, 0x1d, 0x44, 0xb3, 0xd1, 0xee, 0x10, 0xbd, 0x61, 0x60, 0x2d, 0x8d, 0x2a,
	0xf0, 0x70, 0x85, 0xd5, 0x22, 0xcd, 0x16, 0x26, 0xd6, 0x4b, 0xbb, 0x8a, 0x71, 0x55, 0xcb, 0xa0,
	0x3d, 0xf8, 0x74, 0x85, 0x51, 0xc3, 0x7a, 0x1b, 0xdb, 0xfa, 0x19, 0xc1, 0xb8, 0x8e, 0x1b, 0x96,
	0x96, 0x45, 0x1f, 0xc3, 0xce, 0x0a, 0xc7, 0x68, 0x36, 0x2c, 0xa2, 0x1b, 0x96, 0xb6, 0x86, 0x76,
	0xe1, 0xfe, 0x8a, 0x91, 0x60, 0x03, 0x9b, 0x2d, 0x4b, 0x5b, 0x4f, 0x70, 0xfc, 0x4e, 0x27, 0x44,
	0x6f, 0x58, 0x2f, 0xb5, 0x3b, 0xa8, 0x0c, 0xdb, 0xab, 0x7b, 0x3b, 0x6f, 0x5a, 0x4d, 0x0d, 0x12,
	0x2c, 0x17, 0x66, 0x15, 0x37, 0xb5, 0x42, 0x82, 0x45, 0xef, 0x54, 0xcd, 0xa6, 0x56, 0x44, 0x8f,
	0xe0, 0xe3, 0x15, 0x4b, 0xb5, 0x69, 0x74, 0x44, 0x00, 0x76, 0xab, 0x7a, 0xaa, 0x95, 0xd0, 0x27,
	0xf0, 0x60, 0x85, 0x70, 0xd6, 0xac, 0x9d, 0xda, 0x6d, 0xa3, 0x49, 0xb0, 0xb6, 0x9d, 0x60, 0xb6,
	0x70, 0xdb, 0x8a, 0xcc, 0xf7, 0x12, 0x84, 0x34, 0x30, 0xb1, 0xcc, 0x53, 0xd3, 0x50, 0x09, 0xb9,
	0x9f, 0x90, 0x59, 0xdd, 0x38, 0x37, 0xf1, 0x85, 0x12, 0x71, 0x07, 0xdd, 0x07, 0xb4, 0x62, 0x6f,
	0x9c, 0x5a, 0xda, 0xa7, 0x09, 0x7e, 0x55, 0xf3, 0xcc, 0xb4, 0xf4, 0x9a, 0xad, 0x13, 0x4b, 0x7b,
	0x94, 0xf0, 0xe6, 0x7a, 0xa7, 0x6d, 0x1a, 0x76, 0xcd, 0x34, 0x70, 0xa3, 0x8d, 0xb5, 0x0a, 0xfa,
	0x1c, 0x1e, 0xaf, 0xca, 0xa5, 0x1b, 0x86, 0xd9, 0x90, 0x3b, 0x13, 0xd9, 0x68, 0x92, 0xaa, 0xb6,
	0x8f, 0x1e, 0xc3, 0x27, 0xab, 0x0f, 0xc2, 0x55, 0xd3, 0xd0, 0x6b, 0x31, 0xe5, 0x59, 0x82, 0x88,
	0x2d, 0x82, 0xdb, 0x06, 0x31, 0x5b, 0x32, 0xc8, 0x03, 0xf4, 0x00, 0xee, 0xad, 0xca, 0xd0, 0x69,
	0x5b, 0xcd, 0xba, 0xd6, 0x3d, 0xf8, 0x7b, 0x0a, 0x36, 0x96, 0xff, 0x02, 0xb2, 0xbc, 0xf5, 0xb6,
	0xa5, 0x5b, 0x9d, 0xf6, 0x4a, 0xb9, 0x3f, 0x83, 0xcf, 0xaf, 0x30, 0x5a, 0xb8, 0x51, 0x35, 0x1b,
	0x67, 0xf6, 0x05, 0x26, 0x73, 0x7d, 0x53, 0xcb, 0x09, 0x8a, 0xa8, 0x8a, 0x82, 0xab, 0x5a, 0x3a,
	0xd1, 0x4c, 0xf0, 0x2f, 0xb0, 0x61, 0xc9, 0x32, 0x7f, 0x08, 0xe5, 0x2b, 0x66, 0xfc, 0xcb, 0x96,
	0x49, 0x70, 0x55, 0xcb, 0x26, 0x5a, 0x09, 0xbe, 0x68, 0x7e, 0x8b, 0xab, 0xda, 0xda, 0xc1, 0x7f,
	0x52, 0xb0, 0x79, 0xa5, 0x65, 0x8a, 0x83, 0xb3, 0xb8, 0x43, 0xbb, 0x86, 0x2f, 0x70, 0x6d, 0x25,
	0xbc, 0xcf, 0xa0, 0x92, 0xc0, 0x69, 0xe3, 0xda, 0xa9, 0xad, 0x5b, 0xa2, 0xbe, 0x70, 0x55, 0x1d,
	0xe5, 0x04, 0x56, 0x0b, 0x63, 0xb2, 0x18, 0x60, 0xf2, 0xfb, 0x74, 0x73, 0xce, 0xc9, 0x08, 0x39,
	0x93, 0x38, 0x1d, 0xeb, 0xbc, 0x49, 0x4c, 0xeb, 0xe5, 0x9c, 0x9a, 0x45, 0x07, 0xf0, 0x45, 0x02,
	0xf5, 0xa4, 0xd6, 0x34, 0xbe, 0x35, 0xce, 0x75, 0xb3, 0x61, 0xeb, 0x0d, 0xe3, 0xbc, 0x49, 0xa4,
	0x00, 0x6f, 0x01, 0xe6, 0x7f, 0x99, 0x44, 0x3b, 0xb0, 0xa5, 0x1b, 0x06, 0x6e, 0xb7, 0xed, 0x7a,
	0xb3, 0x2a, 0x2a, 0xc4, 0xbc, 0xd0, 0x2d, 0xac, 0x7d, 0x24, 0x8a, 0x63, 0xd1, 0xf0, 0xdd, 0xb9,
	0x69, 0xe1, 0x9a, 0xd9, 0xb6, 0xb4, 0x94, 0x28, 0xfe, 0x25, 0x9f, 0xce, 0x49, 0xcd, 0x34, 0xb4,
	0xb4, 0x28, 0xfe, 0x45, 0x3c, 0xde, 0x9f, 0xdd, 0x69, 0x63, 0xd2, 0xd6, 0x32, 0x27, 0x5f, 0xff,
	0xea, 0xab, 0x9e, 0xcb, 0xfb, 0xe3, 0xcb, 0x43, 0xc7, 0x1f, 0x1e, 0x51, 0xf6, 0xfd, 0xd8, 0xe5,
	0x34, 0x3c, 0x92, 0xff, 0x2b, 0x90, 0xcd, 0xf9, 0xe8, 0x9d, 0xff, 0x36, 0xb8, 0x5c, 0x97, 0x84,
	0x9f, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xed, 0x91, 0x00, 0x5a, 0x18, 0x00, 0x00,
}
