// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aura/cryptography/v1beta1/genesis.proto

package v1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the cryptography module's genesis state
type GenesisState struct {
	Params               Params                      `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	KeyRotationSchedules []*KeyRotationSchedule      `protobuf:"bytes,2,rep,name=key_rotation_schedules,json=keyRotationSchedules,proto3" json:"key_rotation_schedules,omitempty"`
	ThresholdSchemes     []*ThresholdSignatureScheme `protobuf:"bytes,3,rep,name=threshold_schemes,json=thresholdSchemes,proto3" json:"threshold_schemes,omitempty"`
	ZkProofConfigs       []*ZKProofConfig            `protobuf:"bytes,4,rep,name=zk_proof_configs,json=zkProofConfigs,proto3" json:"zk_proof_configs,omitempty"`
	SecureEnclaves       []*SecureEnclaveConfig      `protobuf:"bytes,5,rep,name=secure_enclaves,json=secureEnclaves,proto3" json:"secure_enclaves,omitempty"`
	QuantumResistantKeys []*QuantumResistantKey      `protobuf:"bytes,6,rep,name=quantum_resistant_keys,json=quantumResistantKeys,proto3" json:"quantum_resistant_keys,omitempty"`
	RandomSources        []*CryptoRandomSource       `protobuf:"bytes,7,rep,name=random_sources,json=randomSources,proto3" json:"random_sources,omitempty"`
	KeyStretchingConfigs []*KeyStretchingConfig      `protobuf:"bytes,8,rep,name=key_stretching_configs,json=keyStretchingConfigs,proto3" json:"key_stretching_configs,omitempty"`
	CertificatePins      []*CertificatePin           `protobuf:"bytes,9,rep,name=certificate_pins,json=certificatePins,proto3" json:"certificate_pins,omitempty"`
	ZkProofVerifications []*ZKProofVerification      `protobuf:"bytes,10,rep,name=zk_proof_verifications,json=zkProofVerifications,proto3" json:"zk_proof_verifications,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9b450a35075ce6, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetKeyRotationSchedules() []*KeyRotationSchedule {
	if m != nil {
		return m.KeyRotationSchedules
	}
	return nil
}

func (m *GenesisState) GetThresholdSchemes() []*ThresholdSignatureScheme {
	if m != nil {
		return m.ThresholdSchemes
	}
	return nil
}

func (m *GenesisState) GetZkProofConfigs() []*ZKProofConfig {
	if m != nil {
		return m.ZkProofConfigs
	}
	return nil
}

func (m *GenesisState) GetSecureEnclaves() []*SecureEnclaveConfig {
	if m != nil {
		return m.SecureEnclaves
	}
	return nil
}

func (m *GenesisState) GetQuantumResistantKeys() []*QuantumResistantKey {
	if m != nil {
		return m.QuantumResistantKeys
	}
	return nil
}

func (m *GenesisState) GetRandomSources() []*CryptoRandomSource {
	if m != nil {
		return m.RandomSources
	}
	return nil
}

func (m *GenesisState) GetKeyStretchingConfigs() []*KeyStretchingConfig {
	if m != nil {
		return m.KeyStretchingConfigs
	}
	return nil
}

func (m *GenesisState) GetCertificatePins() []*CertificatePin {
	if m != nil {
		return m.CertificatePins
	}
	return nil
}

func (m *GenesisState) GetZkProofVerifications() []*ZKProofVerification {
	if m != nil {
		return m.ZkProofVerifications
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "aura.cryptography.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("aura/cryptography/v1beta1/genesis.proto", fileDescriptor_ed9b450a35075ce6)
}

var fileDescriptor_ed9b450a35075ce6 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x13, 0x5a, 0x52, 0x70, 0xa1, 0x0d, 0x56, 0x84, 0x4c, 0x0f, 0xa6, 0x70, 0x21, 0x48,
	0x60, 0xab, 0xed, 0x85, 0x1b, 0x52, 0x2b, 0xc4, 0xa1, 0x97, 0xb0, 0xae, 0x40, 0xea, 0xc5, 0x6c,
	0x36, 0x13, 0x7b, 0x95, 0x64, 0xd7, 0xd9, 0x59, 0x47, 0x4a, 0x9f, 0x82, 0x67, 0xe0, 0x69, 0x7a,
	0xec, 0x91, 0x13, 0x42, 0xc9, 0x8b, 0x20, 0xaf, 0x1d, 0xe3, 0x52, 0xc5, 0xe9, 0xcd, 0xfb, 0xfb,
	0xff, 0xfe, 0x19, 0xcd, 0x8e, 0xd6, 0x7a, 0x43, 0x53, 0x45, 0x7d, 0xa6, 0xe6, 0x89, 0x96, 0x91,
	0xa2, 0x49, 0x3c, 0xf7, 0x67, 0x47, 0x7d, 0xd0, 0xf4, 0xc8, 0x8f, 0x40, 0x00, 0x72, 0xf4, 0x12,
	0x25, 0xb5, 0xb4, 0x5f, 0x64, 0x46, 0xaf, 0x6a, 0xf4, 0x0a, 0xe3, 0x41, 0x27, 0x92, 0x91, 0x34,
	0x2e, 0x3f, 0xfb, 0xca, 0x81, 0x83, 0x77, 0xeb, 0x93, 0x6f, 0xa5, 0x18, 0xf7, 0xeb, 0x9f, 0x3b,
	0xd6, 0x93, 0xcf, 0x79, 0xc1, 0x40, 0x53, 0x0d, 0xf6, 0x47, 0xab, 0x95, 0x50, 0x45, 0x27, 0xe8,
	0x34, 0x0f, 0x9b, 0xdd, 0xdd, 0xe3, 0x57, 0xde, 0xda, 0x06, 0xbc, 0x9e, 0x31, 0x9e, 0x6e, 0x5f,
	0xff, 0x7e, 0xd9, 0x20, 0x05, 0x66, 0x0f, 0xac, 0xe7, 0x23, 0x98, 0x87, 0x4a, 0x6a, 0xaa, 0xb9,
	0x14, 0x21, 0xb2, 0x18, 0x06, 0xe9, 0x18, 0xd0, 0x79, 0x70, 0xb8, 0xd5, 0xdd, 0x3d, 0xf6, 0x6a,
	0x02, 0xcf, 0x61, 0x4e, 0x0a, 0x2e, 0x28, 0x30, 0xd2, 0x19, 0xdd, 0x15, 0xd1, 0xfe, 0x6e, 0x3d,
	0xd3, 0xb1, 0x02, 0x8c, 0xe5, 0x78, 0x60, 0x4a, 0x4c, 0x00, 0x9d, 0x2d, 0x53, 0xe0, 0xa4, 0xa6,
	0xc0, 0xc5, 0x8a, 0x09, 0x78, 0x24, 0xa8, 0x4e, 0x15, 0x04, 0x86, 0x25, 0xed, 0x32, 0x2d, 0x17,
	0xd0, 0x26, 0x56, 0xfb, 0x6a, 0x14, 0x26, 0x4a, 0xca, 0x61, 0xc8, 0xa4, 0x18, 0xf2, 0x08, 0x9d,
	0x6d, 0x53, 0xa0, 0x5b, 0x53, 0xe0, 0xf2, 0xbc, 0x97, 0x11, 0x67, 0x06, 0x20, 0x7b, 0x57, 0xa3,
	0xca, 0x11, 0xed, 0x6f, 0xd6, 0x3e, 0x02, 0x4b, 0x15, 0x84, 0x20, 0xd8, 0x98, 0xce, 0x00, 0x9d,
	0x87, 0x1b, 0x87, 0x12, 0x18, 0xe2, 0x53, 0x0e, 0xac, 0x82, 0xb1, 0x2a, 0x9a, 0xa1, 0x4f, 0x53,
	0x2a, 0x74, 0x3a, 0x09, 0x55, 0x76, 0x97, 0x9a, 0x0a, 0x1d, 0x8e, 0x60, 0x8e, 0x4e, 0x6b, 0x63,
	0xfe, 0x97, 0x1c, 0x24, 0x2b, 0x2e, 0xbb, 0x84, 0xce, 0xf4, 0xae, 0x88, 0xf6, 0x85, 0xb5, 0xa7,
	0xa8, 0x18, 0xc8, 0x49, 0x88, 0x32, 0x55, 0x0c, 0xd0, 0xd9, 0x31, 0xe9, 0xef, 0x6b, 0xd2, 0xcf,
	0x8c, 0x48, 0x0c, 0x16, 0x18, 0x8a, 0x3c, 0x55, 0x95, 0x53, 0xb9, 0x30, 0xa8, 0x15, 0x68, 0x16,
	0x73, 0x11, 0x95, 0xe3, 0x7e, 0x74, 0x9f, 0x85, 0x09, 0x4a, 0xae, 0x98, 0x4d, 0xb6, 0x30, 0xff,
	0x8b, 0x59, 0xef, 0x6d, 0x06, 0x4a, 0xf3, 0x21, 0x67, 0x54, 0x43, 0x98, 0x70, 0x81, 0xce, 0x63,
	0x93, 0xff, 0xb6, 0xae, 0xfb, 0x7f, 0x48, 0x8f, 0x0b, 0xb2, 0xcf, 0x6e, 0x9d, 0x4d, 0xef, 0xe5,
	0x92, 0xcc, 0x40, 0xe5, 0xbf, 0xb8, 0x14, 0xe8, 0x58, 0x1b, 0x7b, 0x2f, 0x56, 0xe5, 0x6b, 0x05,
	0x23, 0x9d, 0x62, 0x61, 0xaa, 0x22, 0x9e, 0x92, 0xeb, 0x85, 0xdb, 0xbc, 0x59, 0xb8, 0xcd, 0x3f,
	0x0b, 0xb7, 0xf9, 0x63, 0xe9, 0x36, 0x6e, 0x96, 0x6e, 0xe3, 0xd7, 0xd2, 0x6d, 0x5c, 0x7e, 0x88,
	0xb8, 0x8e, 0xd3, 0xbe, 0xc7, 0xe4, 0xc4, 0xa7, 0x30, 0x4d, 0xb9, 0xa6, 0xe8, 0x9b, 0x07, 0x20,
	0x7f, 0x17, 0xd6, 0xbe, 0x05, 0xfd, 0x96, 0x31, 0x9c, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x23, 0x3c, 0xd0, 0x89, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZkProofVerifications) > 0 {
		for iNdEx := len(m.ZkProofVerifications) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ZkProofVerifications[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.CertificatePins) > 0 {
		for iNdEx := len(m.CertificatePins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CertificatePins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.KeyStretchingConfigs) > 0 {
		for iNdEx := len(m.KeyStretchingConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeyStretchingConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.RandomSources) > 0 {
		for iNdEx := len(m.RandomSources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RandomSources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.QuantumResistantKeys) > 0 {
		for iNdEx := len(m.QuantumResistantKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QuantumResistantKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SecureEnclaves) > 0 {
		for iNdEx := len(m.SecureEnclaves) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecureEnclaves[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ZkProofConfigs) > 0 {
		for iNdEx := len(m.ZkProofConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ZkProofConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ThresholdSchemes) > 0 {
		for iNdEx := len(m.ThresholdSchemes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ThresholdSchemes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.KeyRotationSchedules) > 0 {
		for iNdEx := len(m.KeyRotationSchedules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeyRotationSchedules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.KeyRotationSchedules) > 0 {
		for _, e := range m.KeyRotationSchedules {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ThresholdSchemes) > 0 {
		for _, e := range m.ThresholdSchemes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ZkProofConfigs) > 0 {
		for _, e := range m.ZkProofConfigs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SecureEnclaves) > 0 {
		for _, e := range m.SecureEnclaves {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.QuantumResistantKeys) > 0 {
		for _, e := range m.QuantumResistantKeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RandomSources) > 0 {
		for _, e := range m.RandomSources {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.KeyStretchingConfigs) > 0 {
		for _, e := range m.KeyStretchingConfigs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CertificatePins) > 0 {
		for _, e := range m.CertificatePins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ZkProofVerifications) > 0 {
		for _, e := range m.ZkProofVerifications {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyRotationSchedules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyRotationSchedules = append(m.KeyRotationSchedules, &KeyRotationSchedule{})
			if err := m.KeyRotationSchedules[len(m.KeyRotationSchedules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThresholdSchemes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThresholdSchemes = append(m.ThresholdSchemes, &ThresholdSignatureScheme{})
			if err := m.ThresholdSchemes[len(m.ThresholdSchemes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkProofConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkProofConfigs = append(m.ZkProofConfigs, &ZKProofConfig{})
			if err := m.ZkProofConfigs[len(m.ZkProofConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecureEnclaves", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecureEnclaves = append(m.SecureEnclaves, &SecureEnclaveConfig{})
			if err := m.SecureEnclaves[len(m.SecureEnclaves)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuantumResistantKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuantumResistantKeys = append(m.QuantumResistantKeys, &QuantumResistantKey{})
			if err := m.QuantumResistantKeys[len(m.QuantumResistantKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomSources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RandomSources = append(m.RandomSources, &CryptoRandomSource{})
			if err := m.RandomSources[len(m.RandomSources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyStretchingConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyStretchingConfigs = append(m.KeyStretchingConfigs, &KeyStretchingConfig{})
			if err := m.KeyStretchingConfigs[len(m.KeyStretchingConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificatePins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertificatePins = append(m.CertificatePins, &CertificatePin{})
			if err := m.CertificatePins[len(m.CertificatePins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkProofVerifications", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkProofVerifications = append(m.ZkProofVerifications, &ZKProofVerification{})
			if err := m.ZkProofVerifications[len(m.ZkProofVerifications)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
