// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: aura/validatorsecurity/v1beta1/query.proto

package validatorsecurityv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName                = "/aura.validatorsecurity.v1beta1.Query/Params"
	Query_ValidatorSecurityInfo_FullMethodName = "/aura.validatorsecurity.v1beta1.Query/ValidatorSecurityInfo"
	Query_AllValidators_FullMethodName         = "/aura.validatorsecurity.v1beta1.Query/AllValidators"
	Query_JailedValidators_FullMethodName      = "/aura.validatorsecurity.v1beta1.Query/JailedValidators"
	Query_TombstonedValidators_FullMethodName  = "/aura.validatorsecurity.v1beta1.Query/TombstonedValidators"
	Query_DoubleSignEvidences_FullMethodName   = "/aura.validatorsecurity.v1beta1.Query/DoubleSignEvidences"
	Query_ValidatorAlerts_FullMethodName       = "/aura.validatorsecurity.v1beta1.Query/ValidatorAlerts"
	Query_SentryNodes_FullMethodName           = "/aura.validatorsecurity.v1beta1.Query/SentryNodes"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service
type QueryClient interface {
	// Params queries the module parameters
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ValidatorSecurityInfo queries security info for a validator
	ValidatorSecurityInfo(ctx context.Context, in *QueryValidatorSecurityInfoRequest, opts ...grpc.CallOption) (*QueryValidatorSecurityInfoResponse, error)
	// AllValidators queries all validator security info
	AllValidators(ctx context.Context, in *QueryAllValidatorsRequest, opts ...grpc.CallOption) (*QueryAllValidatorsResponse, error)
	// JailedValidators queries all jailed validators
	JailedValidators(ctx context.Context, in *QueryJailedValidatorsRequest, opts ...grpc.CallOption) (*QueryJailedValidatorsResponse, error)
	// TombstonedValidators queries all tombstoned validators
	TombstonedValidators(ctx context.Context, in *QueryTombstonedValidatorsRequest, opts ...grpc.CallOption) (*QueryTombstonedValidatorsResponse, error)
	// DoubleSignEvidences queries all double sign evidences
	DoubleSignEvidences(ctx context.Context, in *QueryDoubleSignEvidencesRequest, opts ...grpc.CallOption) (*QueryDoubleSignEvidencesResponse, error)
	// ValidatorAlerts queries alerts for a validator
	ValidatorAlerts(ctx context.Context, in *QueryValidatorAlertsRequest, opts ...grpc.CallOption) (*QueryValidatorAlertsResponse, error)
	// SentryNodes queries sentry nodes for a validator
	SentryNodes(ctx context.Context, in *QuerySentryNodesRequest, opts ...grpc.CallOption) (*QuerySentryNodesResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorSecurityInfo(ctx context.Context, in *QueryValidatorSecurityInfoRequest, opts ...grpc.CallOption) (*QueryValidatorSecurityInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryValidatorSecurityInfoResponse)
	err := c.cc.Invoke(ctx, Query_ValidatorSecurityInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllValidators(ctx context.Context, in *QueryAllValidatorsRequest, opts ...grpc.CallOption) (*QueryAllValidatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAllValidatorsResponse)
	err := c.cc.Invoke(ctx, Query_AllValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) JailedValidators(ctx context.Context, in *QueryJailedValidatorsRequest, opts ...grpc.CallOption) (*QueryJailedValidatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryJailedValidatorsResponse)
	err := c.cc.Invoke(ctx, Query_JailedValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TombstonedValidators(ctx context.Context, in *QueryTombstonedValidatorsRequest, opts ...grpc.CallOption) (*QueryTombstonedValidatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTombstonedValidatorsResponse)
	err := c.cc.Invoke(ctx, Query_TombstonedValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DoubleSignEvidences(ctx context.Context, in *QueryDoubleSignEvidencesRequest, opts ...grpc.CallOption) (*QueryDoubleSignEvidencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDoubleSignEvidencesResponse)
	err := c.cc.Invoke(ctx, Query_DoubleSignEvidences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorAlerts(ctx context.Context, in *QueryValidatorAlertsRequest, opts ...grpc.CallOption) (*QueryValidatorAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryValidatorAlertsResponse)
	err := c.cc.Invoke(ctx, Query_ValidatorAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SentryNodes(ctx context.Context, in *QuerySentryNodesRequest, opts ...grpc.CallOption) (*QuerySentryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySentryNodesResponse)
	err := c.cc.Invoke(ctx, Query_SentryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service
type QueryServer interface {
	// Params queries the module parameters
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ValidatorSecurityInfo queries security info for a validator
	ValidatorSecurityInfo(context.Context, *QueryValidatorSecurityInfoRequest) (*QueryValidatorSecurityInfoResponse, error)
	// AllValidators queries all validator security info
	AllValidators(context.Context, *QueryAllValidatorsRequest) (*QueryAllValidatorsResponse, error)
	// JailedValidators queries all jailed validators
	JailedValidators(context.Context, *QueryJailedValidatorsRequest) (*QueryJailedValidatorsResponse, error)
	// TombstonedValidators queries all tombstoned validators
	TombstonedValidators(context.Context, *QueryTombstonedValidatorsRequest) (*QueryTombstonedValidatorsResponse, error)
	// DoubleSignEvidences queries all double sign evidences
	DoubleSignEvidences(context.Context, *QueryDoubleSignEvidencesRequest) (*QueryDoubleSignEvidencesResponse, error)
	// ValidatorAlerts queries alerts for a validator
	ValidatorAlerts(context.Context, *QueryValidatorAlertsRequest) (*QueryValidatorAlertsResponse, error)
	// SentryNodes queries sentry nodes for a validator
	SentryNodes(context.Context, *QuerySentryNodesRequest) (*QuerySentryNodesResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) ValidatorSecurityInfo(context.Context, *QueryValidatorSecurityInfoRequest) (*QueryValidatorSecurityInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatorSecurityInfo not implemented")
}
func (UnimplementedQueryServer) AllValidators(context.Context, *QueryAllValidatorsRequest) (*QueryAllValidatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllValidators not implemented")
}
func (UnimplementedQueryServer) JailedValidators(context.Context, *QueryJailedValidatorsRequest) (*QueryJailedValidatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JailedValidators not implemented")
}
func (UnimplementedQueryServer) TombstonedValidators(context.Context, *QueryTombstonedValidatorsRequest) (*QueryTombstonedValidatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TombstonedValidators not implemented")
}
func (UnimplementedQueryServer) DoubleSignEvidences(context.Context, *QueryDoubleSignEvidencesRequest) (*QueryDoubleSignEvidencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DoubleSignEvidences not implemented")
}
func (UnimplementedQueryServer) ValidatorAlerts(context.Context, *QueryValidatorAlertsRequest) (*QueryValidatorAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatorAlerts not implemented")
}
func (UnimplementedQueryServer) SentryNodes(context.Context, *QuerySentryNodesRequest) (*QuerySentryNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SentryNodes not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorSecurityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorSecurityInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorSecurityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ValidatorSecurityInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorSecurityInfo(ctx, req.(*QueryValidatorSecurityInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllValidators(ctx, req.(*QueryAllValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_JailedValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryJailedValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).JailedValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_JailedValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).JailedValidators(ctx, req.(*QueryJailedValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TombstonedValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTombstonedValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TombstonedValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TombstonedValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TombstonedValidators(ctx, req.(*QueryTombstonedValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DoubleSignEvidences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDoubleSignEvidencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DoubleSignEvidences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DoubleSignEvidences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DoubleSignEvidences(ctx, req.(*QueryDoubleSignEvidencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ValidatorAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorAlerts(ctx, req.(*QueryValidatorAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SentryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySentryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SentryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SentryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SentryNodes(ctx, req.(*QuerySentryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aura.validatorsecurity.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ValidatorSecurityInfo",
			Handler:    _Query_ValidatorSecurityInfo_Handler,
		},
		{
			MethodName: "AllValidators",
			Handler:    _Query_AllValidators_Handler,
		},
		{
			MethodName: "JailedValidators",
			Handler:    _Query_JailedValidators_Handler,
		},
		{
			MethodName: "TombstonedValidators",
			Handler:    _Query_TombstonedValidators_Handler,
		},
		{
			MethodName: "DoubleSignEvidences",
			Handler:    _Query_DoubleSignEvidences_Handler,
		},
		{
			MethodName: "ValidatorAlerts",
			Handler:    _Query_ValidatorAlerts_Handler,
		},
		{
			MethodName: "SentryNodes",
			Handler:    _Query_SentryNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aura/validatorsecurity/v1beta1/query.proto",
}
