// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aura/auth/v1beta1/tx.proto

package v1beta1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateRole
type MsgCreateRole struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions          []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateRole) Reset()         { *m = MsgCreateRole{} }
func (m *MsgCreateRole) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRole) ProtoMessage()    {}
func (*MsgCreateRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{0}
}
func (m *MsgCreateRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRole.Unmarshal(m, b)
}
func (m *MsgCreateRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRole.Marshal(b, m, deterministic)
}
func (m *MsgCreateRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRole.Merge(m, src)
}
func (m *MsgCreateRole) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRole.Size(m)
}
func (m *MsgCreateRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRole proto.InternalMessageInfo

func (m *MsgCreateRole) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateRole) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *MsgCreateRole) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MsgCreateRoleResponse struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateRoleResponse) Reset()         { *m = MsgCreateRoleResponse{} }
func (m *MsgCreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRoleResponse) ProtoMessage()    {}
func (*MsgCreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{1}
}
func (m *MsgCreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRoleResponse.Unmarshal(m, b)
}
func (m *MsgCreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRoleResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRoleResponse.Merge(m, src)
}
func (m *MsgCreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRoleResponse.Size(m)
}
func (m *MsgCreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRoleResponse proto.InternalMessageInfo

func (m *MsgCreateRoleResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

// MsgAssignRole
type MsgAssignRole struct {
	Assigner             string   `protobuf:"bytes,1,opt,name=assigner,proto3" json:"assigner,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ExpiresInSeconds     int64    `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAssignRole) Reset()         { *m = MsgAssignRole{} }
func (m *MsgAssignRole) String() string { return proto.CompactTextString(m) }
func (*MsgAssignRole) ProtoMessage()    {}
func (*MsgAssignRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{2}
}
func (m *MsgAssignRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAssignRole.Unmarshal(m, b)
}
func (m *MsgAssignRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAssignRole.Marshal(b, m, deterministic)
}
func (m *MsgAssignRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAssignRole.Merge(m, src)
}
func (m *MsgAssignRole) XXX_Size() int {
	return xxx_messageInfo_MsgAssignRole.Size(m)
}
func (m *MsgAssignRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAssignRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAssignRole proto.InternalMessageInfo

func (m *MsgAssignRole) GetAssigner() string {
	if m != nil {
		return m.Assigner
	}
	return ""
}

func (m *MsgAssignRole) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgAssignRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *MsgAssignRole) GetExpiresInSeconds() int64 {
	if m != nil {
		return m.ExpiresInSeconds
	}
	return 0
}

type MsgAssignRoleResponse struct {
	Assignment           *RoleAssignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MsgAssignRoleResponse) Reset()         { *m = MsgAssignRoleResponse{} }
func (m *MsgAssignRoleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAssignRoleResponse) ProtoMessage()    {}
func (*MsgAssignRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{3}
}
func (m *MsgAssignRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAssignRoleResponse.Unmarshal(m, b)
}
func (m *MsgAssignRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAssignRoleResponse.Marshal(b, m, deterministic)
}
func (m *MsgAssignRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAssignRoleResponse.Merge(m, src)
}
func (m *MsgAssignRoleResponse) XXX_Size() int {
	return xxx_messageInfo_MsgAssignRoleResponse.Size(m)
}
func (m *MsgAssignRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAssignRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAssignRoleResponse proto.InternalMessageInfo

func (m *MsgAssignRoleResponse) GetAssignment() *RoleAssignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

// MsgRevokeRole
type MsgRevokeRole struct {
	Revoker              string   `protobuf:"bytes,1,opt,name=revoker,proto3" json:"revoker,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevokeRole) Reset()         { *m = MsgRevokeRole{} }
func (m *MsgRevokeRole) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeRole) ProtoMessage()    {}
func (*MsgRevokeRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{4}
}
func (m *MsgRevokeRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevokeRole.Unmarshal(m, b)
}
func (m *MsgRevokeRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevokeRole.Marshal(b, m, deterministic)
}
func (m *MsgRevokeRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeRole.Merge(m, src)
}
func (m *MsgRevokeRole) XXX_Size() int {
	return xxx_messageInfo_MsgRevokeRole.Size(m)
}
func (m *MsgRevokeRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeRole proto.InternalMessageInfo

func (m *MsgRevokeRole) GetRevoker() string {
	if m != nil {
		return m.Revoker
	}
	return ""
}

func (m *MsgRevokeRole) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgRevokeRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type MsgRevokeRoleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevokeRoleResponse) Reset()         { *m = MsgRevokeRoleResponse{} }
func (m *MsgRevokeRoleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeRoleResponse) ProtoMessage()    {}
func (*MsgRevokeRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{5}
}
func (m *MsgRevokeRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevokeRoleResponse.Unmarshal(m, b)
}
func (m *MsgRevokeRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevokeRoleResponse.Marshal(b, m, deterministic)
}
func (m *MsgRevokeRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeRoleResponse.Merge(m, src)
}
func (m *MsgRevokeRoleResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRevokeRoleResponse.Size(m)
}
func (m *MsgRevokeRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeRoleResponse proto.InternalMessageInfo

func (m *MsgRevokeRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgCreateMultisigWallet
type MsgCreateMultisigWallet struct {
	Creator              string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Signers              []string   `protobuf:"bytes,2,rep,name=signers,proto3" json:"signers,omitempty"`
	Threshold            uint32     `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	WalletType           WalletType `protobuf:"varint,4,opt,name=wallet_type,json=walletType,proto3,enum=aura.auth.v1beta1.WalletType" json:"wallet_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgCreateMultisigWallet) Reset()         { *m = MsgCreateMultisigWallet{} }
func (m *MsgCreateMultisigWallet) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMultisigWallet) ProtoMessage()    {}
func (*MsgCreateMultisigWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{6}
}
func (m *MsgCreateMultisigWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateMultisigWallet.Unmarshal(m, b)
}
func (m *MsgCreateMultisigWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateMultisigWallet.Marshal(b, m, deterministic)
}
func (m *MsgCreateMultisigWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMultisigWallet.Merge(m, src)
}
func (m *MsgCreateMultisigWallet) XXX_Size() int {
	return xxx_messageInfo_MsgCreateMultisigWallet.Size(m)
}
func (m *MsgCreateMultisigWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMultisigWallet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMultisigWallet proto.InternalMessageInfo

func (m *MsgCreateMultisigWallet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateMultisigWallet) GetSigners() []string {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *MsgCreateMultisigWallet) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *MsgCreateMultisigWallet) GetWalletType() WalletType {
	if m != nil {
		return m.WalletType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

type MsgCreateMultisigWalletResponse struct {
	Wallet               *MultisigWallet `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MsgCreateMultisigWalletResponse) Reset()         { *m = MsgCreateMultisigWalletResponse{} }
func (m *MsgCreateMultisigWalletResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMultisigWalletResponse) ProtoMessage()    {}
func (*MsgCreateMultisigWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{7}
}
func (m *MsgCreateMultisigWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateMultisigWalletResponse.Unmarshal(m, b)
}
func (m *MsgCreateMultisigWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateMultisigWalletResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateMultisigWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMultisigWalletResponse.Merge(m, src)
}
func (m *MsgCreateMultisigWalletResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateMultisigWalletResponse.Size(m)
}
func (m *MsgCreateMultisigWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMultisigWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMultisigWalletResponse proto.InternalMessageInfo

func (m *MsgCreateMultisigWalletResponse) GetWallet() *MultisigWallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

// MsgCreateMultisigProposal
type MsgCreateMultisigProposal struct {
	Proposer             string   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	WalletId             string   `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpiresInSeconds     int64    `protobuf:"varint,6,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateMultisigProposal) Reset()         { *m = MsgCreateMultisigProposal{} }
func (m *MsgCreateMultisigProposal) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMultisigProposal) ProtoMessage()    {}
func (*MsgCreateMultisigProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{8}
}
func (m *MsgCreateMultisigProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateMultisigProposal.Unmarshal(m, b)
}
func (m *MsgCreateMultisigProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateMultisigProposal.Marshal(b, m, deterministic)
}
func (m *MsgCreateMultisigProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMultisigProposal.Merge(m, src)
}
func (m *MsgCreateMultisigProposal) XXX_Size() int {
	return xxx_messageInfo_MsgCreateMultisigProposal.Size(m)
}
func (m *MsgCreateMultisigProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMultisigProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMultisigProposal proto.InternalMessageInfo

func (m *MsgCreateMultisigProposal) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *MsgCreateMultisigProposal) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *MsgCreateMultisigProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgCreateMultisigProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgCreateMultisigProposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgCreateMultisigProposal) GetExpiresInSeconds() int64 {
	if m != nil {
		return m.ExpiresInSeconds
	}
	return 0
}

type MsgCreateMultisigProposalResponse struct {
	Proposal             *MultisigProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgCreateMultisigProposalResponse) Reset()         { *m = MsgCreateMultisigProposalResponse{} }
func (m *MsgCreateMultisigProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMultisigProposalResponse) ProtoMessage()    {}
func (*MsgCreateMultisigProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{9}
}
func (m *MsgCreateMultisigProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateMultisigProposalResponse.Unmarshal(m, b)
}
func (m *MsgCreateMultisigProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateMultisigProposalResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateMultisigProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMultisigProposalResponse.Merge(m, src)
}
func (m *MsgCreateMultisigProposalResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateMultisigProposalResponse.Size(m)
}
func (m *MsgCreateMultisigProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMultisigProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMultisigProposalResponse proto.InternalMessageInfo

func (m *MsgCreateMultisigProposalResponse) GetProposal() *MultisigProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

// MsgSignMultisigProposal
type MsgSignMultisigProposal struct {
	Signer               string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	ProposalId           string   `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSignMultisigProposal) Reset()         { *m = MsgSignMultisigProposal{} }
func (m *MsgSignMultisigProposal) String() string { return proto.CompactTextString(m) }
func (*MsgSignMultisigProposal) ProtoMessage()    {}
func (*MsgSignMultisigProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{10}
}
func (m *MsgSignMultisigProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignMultisigProposal.Unmarshal(m, b)
}
func (m *MsgSignMultisigProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignMultisigProposal.Marshal(b, m, deterministic)
}
func (m *MsgSignMultisigProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignMultisigProposal.Merge(m, src)
}
func (m *MsgSignMultisigProposal) XXX_Size() int {
	return xxx_messageInfo_MsgSignMultisigProposal.Size(m)
}
func (m *MsgSignMultisigProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignMultisigProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignMultisigProposal proto.InternalMessageInfo

func (m *MsgSignMultisigProposal) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSignMultisigProposal) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

type MsgSignMultisigProposalResponse struct {
	Proposal             *MultisigProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgSignMultisigProposalResponse) Reset()         { *m = MsgSignMultisigProposalResponse{} }
func (m *MsgSignMultisigProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSignMultisigProposalResponse) ProtoMessage()    {}
func (*MsgSignMultisigProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{11}
}
func (m *MsgSignMultisigProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignMultisigProposalResponse.Unmarshal(m, b)
}
func (m *MsgSignMultisigProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignMultisigProposalResponse.Marshal(b, m, deterministic)
}
func (m *MsgSignMultisigProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignMultisigProposalResponse.Merge(m, src)
}
func (m *MsgSignMultisigProposalResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSignMultisigProposalResponse.Size(m)
}
func (m *MsgSignMultisigProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignMultisigProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignMultisigProposalResponse proto.InternalMessageInfo

func (m *MsgSignMultisigProposalResponse) GetProposal() *MultisigProposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

// MsgExecuteMultisigProposal
type MsgExecuteMultisigProposal struct {
	Executor             string   `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	ProposalId           string   `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgExecuteMultisigProposal) Reset()         { *m = MsgExecuteMultisigProposal{} }
func (m *MsgExecuteMultisigProposal) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteMultisigProposal) ProtoMessage()    {}
func (*MsgExecuteMultisigProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{12}
}
func (m *MsgExecuteMultisigProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgExecuteMultisigProposal.Unmarshal(m, b)
}
func (m *MsgExecuteMultisigProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgExecuteMultisigProposal.Marshal(b, m, deterministic)
}
func (m *MsgExecuteMultisigProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteMultisigProposal.Merge(m, src)
}
func (m *MsgExecuteMultisigProposal) XXX_Size() int {
	return xxx_messageInfo_MsgExecuteMultisigProposal.Size(m)
}
func (m *MsgExecuteMultisigProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteMultisigProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteMultisigProposal proto.InternalMessageInfo

func (m *MsgExecuteMultisigProposal) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *MsgExecuteMultisigProposal) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

type MsgExecuteMultisigProposalResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgExecuteMultisigProposalResponse) Reset()         { *m = MsgExecuteMultisigProposalResponse{} }
func (m *MsgExecuteMultisigProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteMultisigProposalResponse) ProtoMessage()    {}
func (*MsgExecuteMultisigProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{13}
}
func (m *MsgExecuteMultisigProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgExecuteMultisigProposalResponse.Unmarshal(m, b)
}
func (m *MsgExecuteMultisigProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgExecuteMultisigProposalResponse.Marshal(b, m, deterministic)
}
func (m *MsgExecuteMultisigProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteMultisigProposalResponse.Merge(m, src)
}
func (m *MsgExecuteMultisigProposalResponse) XXX_Size() int {
	return xxx_messageInfo_MsgExecuteMultisigProposalResponse.Size(m)
}
func (m *MsgExecuteMultisigProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteMultisigProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteMultisigProposalResponse proto.InternalMessageInfo

func (m *MsgExecuteMultisigProposalResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgProposeTimeLockedAction
type MsgProposeTimeLockedAction struct {
	Proposer             string   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	ActionType           string   `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	DelaySeconds         uint64   `protobuf:"varint,4,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgProposeTimeLockedAction) Reset()         { *m = MsgProposeTimeLockedAction{} }
func (m *MsgProposeTimeLockedAction) String() string { return proto.CompactTextString(m) }
func (*MsgProposeTimeLockedAction) ProtoMessage()    {}
func (*MsgProposeTimeLockedAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{14}
}
func (m *MsgProposeTimeLockedAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgProposeTimeLockedAction.Unmarshal(m, b)
}
func (m *MsgProposeTimeLockedAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgProposeTimeLockedAction.Marshal(b, m, deterministic)
}
func (m *MsgProposeTimeLockedAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeTimeLockedAction.Merge(m, src)
}
func (m *MsgProposeTimeLockedAction) XXX_Size() int {
	return xxx_messageInfo_MsgProposeTimeLockedAction.Size(m)
}
func (m *MsgProposeTimeLockedAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeTimeLockedAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeTimeLockedAction proto.InternalMessageInfo

func (m *MsgProposeTimeLockedAction) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *MsgProposeTimeLockedAction) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *MsgProposeTimeLockedAction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgProposeTimeLockedAction) GetDelaySeconds() uint64 {
	if m != nil {
		return m.DelaySeconds
	}
	return 0
}

type MsgProposeTimeLockedActionResponse struct {
	Action               *TimeLockedAction `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgProposeTimeLockedActionResponse) Reset()         { *m = MsgProposeTimeLockedActionResponse{} }
func (m *MsgProposeTimeLockedActionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProposeTimeLockedActionResponse) ProtoMessage()    {}
func (*MsgProposeTimeLockedActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{15}
}
func (m *MsgProposeTimeLockedActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgProposeTimeLockedActionResponse.Unmarshal(m, b)
}
func (m *MsgProposeTimeLockedActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgProposeTimeLockedActionResponse.Marshal(b, m, deterministic)
}
func (m *MsgProposeTimeLockedActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeTimeLockedActionResponse.Merge(m, src)
}
func (m *MsgProposeTimeLockedActionResponse) XXX_Size() int {
	return xxx_messageInfo_MsgProposeTimeLockedActionResponse.Size(m)
}
func (m *MsgProposeTimeLockedActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeTimeLockedActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeTimeLockedActionResponse proto.InternalMessageInfo

func (m *MsgProposeTimeLockedActionResponse) GetAction() *TimeLockedAction {
	if m != nil {
		return m.Action
	}
	return nil
}

// MsgExecuteTimeLockedAction
type MsgExecuteTimeLockedAction struct {
	Executor             string   `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	ActionId             string   `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgExecuteTimeLockedAction) Reset()         { *m = MsgExecuteTimeLockedAction{} }
func (m *MsgExecuteTimeLockedAction) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteTimeLockedAction) ProtoMessage()    {}
func (*MsgExecuteTimeLockedAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{16}
}
func (m *MsgExecuteTimeLockedAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgExecuteTimeLockedAction.Unmarshal(m, b)
}
func (m *MsgExecuteTimeLockedAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgExecuteTimeLockedAction.Marshal(b, m, deterministic)
}
func (m *MsgExecuteTimeLockedAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteTimeLockedAction.Merge(m, src)
}
func (m *MsgExecuteTimeLockedAction) XXX_Size() int {
	return xxx_messageInfo_MsgExecuteTimeLockedAction.Size(m)
}
func (m *MsgExecuteTimeLockedAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteTimeLockedAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteTimeLockedAction proto.InternalMessageInfo

func (m *MsgExecuteTimeLockedAction) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *MsgExecuteTimeLockedAction) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

type MsgExecuteTimeLockedActionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgExecuteTimeLockedActionResponse) Reset()         { *m = MsgExecuteTimeLockedActionResponse{} }
func (m *MsgExecuteTimeLockedActionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteTimeLockedActionResponse) ProtoMessage()    {}
func (*MsgExecuteTimeLockedActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{17}
}
func (m *MsgExecuteTimeLockedActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgExecuteTimeLockedActionResponse.Unmarshal(m, b)
}
func (m *MsgExecuteTimeLockedActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgExecuteTimeLockedActionResponse.Marshal(b, m, deterministic)
}
func (m *MsgExecuteTimeLockedActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteTimeLockedActionResponse.Merge(m, src)
}
func (m *MsgExecuteTimeLockedActionResponse) XXX_Size() int {
	return xxx_messageInfo_MsgExecuteTimeLockedActionResponse.Size(m)
}
func (m *MsgExecuteTimeLockedActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteTimeLockedActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteTimeLockedActionResponse proto.InternalMessageInfo

func (m *MsgExecuteTimeLockedActionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgCancelTimeLockedAction
type MsgCancelTimeLockedAction struct {
	Canceller            string   `protobuf:"bytes,1,opt,name=canceller,proto3" json:"canceller,omitempty"`
	ActionId             string   `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCancelTimeLockedAction) Reset()         { *m = MsgCancelTimeLockedAction{} }
func (m *MsgCancelTimeLockedAction) String() string { return proto.CompactTextString(m) }
func (*MsgCancelTimeLockedAction) ProtoMessage()    {}
func (*MsgCancelTimeLockedAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{18}
}
func (m *MsgCancelTimeLockedAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCancelTimeLockedAction.Unmarshal(m, b)
}
func (m *MsgCancelTimeLockedAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCancelTimeLockedAction.Marshal(b, m, deterministic)
}
func (m *MsgCancelTimeLockedAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelTimeLockedAction.Merge(m, src)
}
func (m *MsgCancelTimeLockedAction) XXX_Size() int {
	return xxx_messageInfo_MsgCancelTimeLockedAction.Size(m)
}
func (m *MsgCancelTimeLockedAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelTimeLockedAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelTimeLockedAction proto.InternalMessageInfo

func (m *MsgCancelTimeLockedAction) GetCanceller() string {
	if m != nil {
		return m.Canceller
	}
	return ""
}

func (m *MsgCancelTimeLockedAction) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

type MsgCancelTimeLockedActionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCancelTimeLockedActionResponse) Reset()         { *m = MsgCancelTimeLockedActionResponse{} }
func (m *MsgCancelTimeLockedActionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelTimeLockedActionResponse) ProtoMessage()    {}
func (*MsgCancelTimeLockedActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{19}
}
func (m *MsgCancelTimeLockedActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCancelTimeLockedActionResponse.Unmarshal(m, b)
}
func (m *MsgCancelTimeLockedActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCancelTimeLockedActionResponse.Marshal(b, m, deterministic)
}
func (m *MsgCancelTimeLockedActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelTimeLockedActionResponse.Merge(m, src)
}
func (m *MsgCancelTimeLockedActionResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCancelTimeLockedActionResponse.Size(m)
}
func (m *MsgCancelTimeLockedActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelTimeLockedActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelTimeLockedActionResponse proto.InternalMessageInfo

func (m *MsgCancelTimeLockedActionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgActivateEmergencyAdmin
type MsgActivateEmergencyAdmin struct {
	Activator            string   `protobuf:"bytes,1,opt,name=activator,proto3" json:"activator,omitempty"`
	AdminAddress         string   `protobuf:"bytes,2,opt,name=admin_address,json=adminAddress,proto3" json:"admin_address,omitempty"`
	Privileges           []string `protobuf:"bytes,3,rep,name=privileges,proto3" json:"privileges,omitempty"`
	ExpiresInSeconds     int64    `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgActivateEmergencyAdmin) Reset()         { *m = MsgActivateEmergencyAdmin{} }
func (m *MsgActivateEmergencyAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgActivateEmergencyAdmin) ProtoMessage()    {}
func (*MsgActivateEmergencyAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{20}
}
func (m *MsgActivateEmergencyAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActivateEmergencyAdmin.Unmarshal(m, b)
}
func (m *MsgActivateEmergencyAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActivateEmergencyAdmin.Marshal(b, m, deterministic)
}
func (m *MsgActivateEmergencyAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActivateEmergencyAdmin.Merge(m, src)
}
func (m *MsgActivateEmergencyAdmin) XXX_Size() int {
	return xxx_messageInfo_MsgActivateEmergencyAdmin.Size(m)
}
func (m *MsgActivateEmergencyAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActivateEmergencyAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActivateEmergencyAdmin proto.InternalMessageInfo

func (m *MsgActivateEmergencyAdmin) GetActivator() string {
	if m != nil {
		return m.Activator
	}
	return ""
}

func (m *MsgActivateEmergencyAdmin) GetAdminAddress() string {
	if m != nil {
		return m.AdminAddress
	}
	return ""
}

func (m *MsgActivateEmergencyAdmin) GetPrivileges() []string {
	if m != nil {
		return m.Privileges
	}
	return nil
}

func (m *MsgActivateEmergencyAdmin) GetExpiresInSeconds() int64 {
	if m != nil {
		return m.ExpiresInSeconds
	}
	return 0
}

type MsgActivateEmergencyAdminResponse struct {
	Admin                *EmergencyAdmin `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MsgActivateEmergencyAdminResponse) Reset()         { *m = MsgActivateEmergencyAdminResponse{} }
func (m *MsgActivateEmergencyAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgActivateEmergencyAdminResponse) ProtoMessage()    {}
func (*MsgActivateEmergencyAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{21}
}
func (m *MsgActivateEmergencyAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActivateEmergencyAdminResponse.Unmarshal(m, b)
}
func (m *MsgActivateEmergencyAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActivateEmergencyAdminResponse.Marshal(b, m, deterministic)
}
func (m *MsgActivateEmergencyAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActivateEmergencyAdminResponse.Merge(m, src)
}
func (m *MsgActivateEmergencyAdminResponse) XXX_Size() int {
	return xxx_messageInfo_MsgActivateEmergencyAdminResponse.Size(m)
}
func (m *MsgActivateEmergencyAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActivateEmergencyAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActivateEmergencyAdminResponse proto.InternalMessageInfo

func (m *MsgActivateEmergencyAdminResponse) GetAdmin() *EmergencyAdmin {
	if m != nil {
		return m.Admin
	}
	return nil
}

// MsgDeactivateEmergencyAdmin
type MsgDeactivateEmergencyAdmin struct {
	Deactivator          string   `protobuf:"bytes,1,opt,name=deactivator,proto3" json:"deactivator,omitempty"`
	AdminAddress         string   `protobuf:"bytes,2,opt,name=admin_address,json=adminAddress,proto3" json:"admin_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeactivateEmergencyAdmin) Reset()         { *m = MsgDeactivateEmergencyAdmin{} }
func (m *MsgDeactivateEmergencyAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgDeactivateEmergencyAdmin) ProtoMessage()    {}
func (*MsgDeactivateEmergencyAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{22}
}
func (m *MsgDeactivateEmergencyAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeactivateEmergencyAdmin.Unmarshal(m, b)
}
func (m *MsgDeactivateEmergencyAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeactivateEmergencyAdmin.Marshal(b, m, deterministic)
}
func (m *MsgDeactivateEmergencyAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeactivateEmergencyAdmin.Merge(m, src)
}
func (m *MsgDeactivateEmergencyAdmin) XXX_Size() int {
	return xxx_messageInfo_MsgDeactivateEmergencyAdmin.Size(m)
}
func (m *MsgDeactivateEmergencyAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeactivateEmergencyAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeactivateEmergencyAdmin proto.InternalMessageInfo

func (m *MsgDeactivateEmergencyAdmin) GetDeactivator() string {
	if m != nil {
		return m.Deactivator
	}
	return ""
}

func (m *MsgDeactivateEmergencyAdmin) GetAdminAddress() string {
	if m != nil {
		return m.AdminAddress
	}
	return ""
}

type MsgDeactivateEmergencyAdminResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeactivateEmergencyAdminResponse) Reset()         { *m = MsgDeactivateEmergencyAdminResponse{} }
func (m *MsgDeactivateEmergencyAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeactivateEmergencyAdminResponse) ProtoMessage()    {}
func (*MsgDeactivateEmergencyAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{23}
}
func (m *MsgDeactivateEmergencyAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeactivateEmergencyAdminResponse.Unmarshal(m, b)
}
func (m *MsgDeactivateEmergencyAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeactivateEmergencyAdminResponse.Marshal(b, m, deterministic)
}
func (m *MsgDeactivateEmergencyAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeactivateEmergencyAdminResponse.Merge(m, src)
}
func (m *MsgDeactivateEmergencyAdminResponse) XXX_Size() int {
	return xxx_messageInfo_MsgDeactivateEmergencyAdminResponse.Size(m)
}
func (m *MsgDeactivateEmergencyAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeactivateEmergencyAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeactivateEmergencyAdminResponse proto.InternalMessageInfo

func (m *MsgDeactivateEmergencyAdminResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgInitiateValidatorKeyRotation
type MsgInitiateValidatorKeyRotation struct {
	Initiator            string   `protobuf:"bytes,1,opt,name=initiator,proto3" json:"initiator,omitempty"`
	ValidatorAddress     string   `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	NewConsensusPubkey   string   `protobuf:"bytes,3,opt,name=new_consensus_pubkey,json=newConsensusPubkey,proto3" json:"new_consensus_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgInitiateValidatorKeyRotation) Reset()         { *m = MsgInitiateValidatorKeyRotation{} }
func (m *MsgInitiateValidatorKeyRotation) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateValidatorKeyRotation) ProtoMessage()    {}
func (*MsgInitiateValidatorKeyRotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{24}
}
func (m *MsgInitiateValidatorKeyRotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotation.Unmarshal(m, b)
}
func (m *MsgInitiateValidatorKeyRotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotation.Marshal(b, m, deterministic)
}
func (m *MsgInitiateValidatorKeyRotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateValidatorKeyRotation.Merge(m, src)
}
func (m *MsgInitiateValidatorKeyRotation) XXX_Size() int {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotation.Size(m)
}
func (m *MsgInitiateValidatorKeyRotation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateValidatorKeyRotation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateValidatorKeyRotation proto.InternalMessageInfo

func (m *MsgInitiateValidatorKeyRotation) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *MsgInitiateValidatorKeyRotation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgInitiateValidatorKeyRotation) GetNewConsensusPubkey() string {
	if m != nil {
		return m.NewConsensusPubkey
	}
	return ""
}

type MsgInitiateValidatorKeyRotationResponse struct {
	Rotation             *ValidatorKeyRotation `protobuf:"bytes,1,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MsgInitiateValidatorKeyRotationResponse) Reset() {
	*m = MsgInitiateValidatorKeyRotationResponse{}
}
func (m *MsgInitiateValidatorKeyRotationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateValidatorKeyRotationResponse) ProtoMessage()    {}
func (*MsgInitiateValidatorKeyRotationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{25}
}
func (m *MsgInitiateValidatorKeyRotationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse.Unmarshal(m, b)
}
func (m *MsgInitiateValidatorKeyRotationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse.Marshal(b, m, deterministic)
}
func (m *MsgInitiateValidatorKeyRotationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse.Merge(m, src)
}
func (m *MsgInitiateValidatorKeyRotationResponse) XXX_Size() int {
	return xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse.Size(m)
}
func (m *MsgInitiateValidatorKeyRotationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateValidatorKeyRotationResponse proto.InternalMessageInfo

func (m *MsgInitiateValidatorKeyRotationResponse) GetRotation() *ValidatorKeyRotation {
	if m != nil {
		return m.Rotation
	}
	return nil
}

// MsgCompleteValidatorKeyRotation
type MsgCompleteValidatorKeyRotation struct {
	Completer            string   `protobuf:"bytes,1,opt,name=completer,proto3" json:"completer,omitempty"`
	ValidatorAddress     string   `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCompleteValidatorKeyRotation) Reset()         { *m = MsgCompleteValidatorKeyRotation{} }
func (m *MsgCompleteValidatorKeyRotation) String() string { return proto.CompactTextString(m) }
func (*MsgCompleteValidatorKeyRotation) ProtoMessage()    {}
func (*MsgCompleteValidatorKeyRotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{26}
}
func (m *MsgCompleteValidatorKeyRotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotation.Unmarshal(m, b)
}
func (m *MsgCompleteValidatorKeyRotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotation.Marshal(b, m, deterministic)
}
func (m *MsgCompleteValidatorKeyRotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCompleteValidatorKeyRotation.Merge(m, src)
}
func (m *MsgCompleteValidatorKeyRotation) XXX_Size() int {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotation.Size(m)
}
func (m *MsgCompleteValidatorKeyRotation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCompleteValidatorKeyRotation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCompleteValidatorKeyRotation proto.InternalMessageInfo

func (m *MsgCompleteValidatorKeyRotation) GetCompleter() string {
	if m != nil {
		return m.Completer
	}
	return ""
}

func (m *MsgCompleteValidatorKeyRotation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

type MsgCompleteValidatorKeyRotationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCompleteValidatorKeyRotationResponse) Reset() {
	*m = MsgCompleteValidatorKeyRotationResponse{}
}
func (m *MsgCompleteValidatorKeyRotationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCompleteValidatorKeyRotationResponse) ProtoMessage()    {}
func (*MsgCompleteValidatorKeyRotationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{27}
}
func (m *MsgCompleteValidatorKeyRotationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse.Unmarshal(m, b)
}
func (m *MsgCompleteValidatorKeyRotationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse.Marshal(b, m, deterministic)
}
func (m *MsgCompleteValidatorKeyRotationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse.Merge(m, src)
}
func (m *MsgCompleteValidatorKeyRotationResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse.Size(m)
}
func (m *MsgCompleteValidatorKeyRotationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCompleteValidatorKeyRotationResponse proto.InternalMessageInfo

func (m *MsgCompleteValidatorKeyRotationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgCreateSession
type MsgCreateSession struct {
	UserAddress          string            `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	IpAddress            string            `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgCreateSession) Reset()         { *m = MsgCreateSession{} }
func (m *MsgCreateSession) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSession) ProtoMessage()    {}
func (*MsgCreateSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{28}
}
func (m *MsgCreateSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateSession.Unmarshal(m, b)
}
func (m *MsgCreateSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateSession.Marshal(b, m, deterministic)
}
func (m *MsgCreateSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSession.Merge(m, src)
}
func (m *MsgCreateSession) XXX_Size() int {
	return xxx_messageInfo_MsgCreateSession.Size(m)
}
func (m *MsgCreateSession) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSession.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSession proto.InternalMessageInfo

func (m *MsgCreateSession) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *MsgCreateSession) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *MsgCreateSession) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MsgCreateSessionResponse struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateSessionResponse) Reset()         { *m = MsgCreateSessionResponse{} }
func (m *MsgCreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSessionResponse) ProtoMessage()    {}
func (*MsgCreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{29}
}
func (m *MsgCreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateSessionResponse.Unmarshal(m, b)
}
func (m *MsgCreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSessionResponse.Merge(m, src)
}
func (m *MsgCreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateSessionResponse.Size(m)
}
func (m *MsgCreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSessionResponse proto.InternalMessageInfo

func (m *MsgCreateSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

// MsgRevokeSession
type MsgRevokeSession struct {
	UserAddress          string   `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevokeSession) Reset()         { *m = MsgRevokeSession{} }
func (m *MsgRevokeSession) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeSession) ProtoMessage()    {}
func (*MsgRevokeSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{30}
}
func (m *MsgRevokeSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevokeSession.Unmarshal(m, b)
}
func (m *MsgRevokeSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevokeSession.Marshal(b, m, deterministic)
}
func (m *MsgRevokeSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeSession.Merge(m, src)
}
func (m *MsgRevokeSession) XXX_Size() int {
	return xxx_messageInfo_MsgRevokeSession.Size(m)
}
func (m *MsgRevokeSession) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeSession.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeSession proto.InternalMessageInfo

func (m *MsgRevokeSession) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *MsgRevokeSession) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type MsgRevokeSessionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevokeSessionResponse) Reset()         { *m = MsgRevokeSessionResponse{} }
func (m *MsgRevokeSessionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeSessionResponse) ProtoMessage()    {}
func (*MsgRevokeSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0817cb4e425ce128, []int{31}
}
func (m *MsgRevokeSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevokeSessionResponse.Unmarshal(m, b)
}
func (m *MsgRevokeSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevokeSessionResponse.Marshal(b, m, deterministic)
}
func (m *MsgRevokeSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeSessionResponse.Merge(m, src)
}
func (m *MsgRevokeSessionResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRevokeSessionResponse.Size(m)
}
func (m *MsgRevokeSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeSessionResponse proto.InternalMessageInfo

func (m *MsgRevokeSessionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MsgCreateRole)(nil), "aura.auth.v1beta1.MsgCreateRole")
	proto.RegisterType((*MsgCreateRoleResponse)(nil), "aura.auth.v1beta1.MsgCreateRoleResponse")
	proto.RegisterType((*MsgAssignRole)(nil), "aura.auth.v1beta1.MsgAssignRole")
	proto.RegisterType((*MsgAssignRoleResponse)(nil), "aura.auth.v1beta1.MsgAssignRoleResponse")
	proto.RegisterType((*MsgRevokeRole)(nil), "aura.auth.v1beta1.MsgRevokeRole")
	proto.RegisterType((*MsgRevokeRoleResponse)(nil), "aura.auth.v1beta1.MsgRevokeRoleResponse")
	proto.RegisterType((*MsgCreateMultisigWallet)(nil), "aura.auth.v1beta1.MsgCreateMultisigWallet")
	proto.RegisterType((*MsgCreateMultisigWalletResponse)(nil), "aura.auth.v1beta1.MsgCreateMultisigWalletResponse")
	proto.RegisterType((*MsgCreateMultisigProposal)(nil), "aura.auth.v1beta1.MsgCreateMultisigProposal")
	proto.RegisterType((*MsgCreateMultisigProposalResponse)(nil), "aura.auth.v1beta1.MsgCreateMultisigProposalResponse")
	proto.RegisterType((*MsgSignMultisigProposal)(nil), "aura.auth.v1beta1.MsgSignMultisigProposal")
	proto.RegisterType((*MsgSignMultisigProposalResponse)(nil), "aura.auth.v1beta1.MsgSignMultisigProposalResponse")
	proto.RegisterType((*MsgExecuteMultisigProposal)(nil), "aura.auth.v1beta1.MsgExecuteMultisigProposal")
	proto.RegisterType((*MsgExecuteMultisigProposalResponse)(nil), "aura.auth.v1beta1.MsgExecuteMultisigProposalResponse")
	proto.RegisterType((*MsgProposeTimeLockedAction)(nil), "aura.auth.v1beta1.MsgProposeTimeLockedAction")
	proto.RegisterType((*MsgProposeTimeLockedActionResponse)(nil), "aura.auth.v1beta1.MsgProposeTimeLockedActionResponse")
	proto.RegisterType((*MsgExecuteTimeLockedAction)(nil), "aura.auth.v1beta1.MsgExecuteTimeLockedAction")
	proto.RegisterType((*MsgExecuteTimeLockedActionResponse)(nil), "aura.auth.v1beta1.MsgExecuteTimeLockedActionResponse")
	proto.RegisterType((*MsgCancelTimeLockedAction)(nil), "aura.auth.v1beta1.MsgCancelTimeLockedAction")
	proto.RegisterType((*MsgCancelTimeLockedActionResponse)(nil), "aura.auth.v1beta1.MsgCancelTimeLockedActionResponse")
	proto.RegisterType((*MsgActivateEmergencyAdmin)(nil), "aura.auth.v1beta1.MsgActivateEmergencyAdmin")
	proto.RegisterType((*MsgActivateEmergencyAdminResponse)(nil), "aura.auth.v1beta1.MsgActivateEmergencyAdminResponse")
	proto.RegisterType((*MsgDeactivateEmergencyAdmin)(nil), "aura.auth.v1beta1.MsgDeactivateEmergencyAdmin")
	proto.RegisterType((*MsgDeactivateEmergencyAdminResponse)(nil), "aura.auth.v1beta1.MsgDeactivateEmergencyAdminResponse")
	proto.RegisterType((*MsgInitiateValidatorKeyRotation)(nil), "aura.auth.v1beta1.MsgInitiateValidatorKeyRotation")
	proto.RegisterType((*MsgInitiateValidatorKeyRotationResponse)(nil), "aura.auth.v1beta1.MsgInitiateValidatorKeyRotationResponse")
	proto.RegisterType((*MsgCompleteValidatorKeyRotation)(nil), "aura.auth.v1beta1.MsgCompleteValidatorKeyRotation")
	proto.RegisterType((*MsgCompleteValidatorKeyRotationResponse)(nil), "aura.auth.v1beta1.MsgCompleteValidatorKeyRotationResponse")
	proto.RegisterType((*MsgCreateSession)(nil), "aura.auth.v1beta1.MsgCreateSession")
	proto.RegisterMapType((map[string]string)(nil), "aura.auth.v1beta1.MsgCreateSession.MetadataEntry")
	proto.RegisterType((*MsgCreateSessionResponse)(nil), "aura.auth.v1beta1.MsgCreateSessionResponse")
	proto.RegisterType((*MsgRevokeSession)(nil), "aura.auth.v1beta1.MsgRevokeSession")
	proto.RegisterType((*MsgRevokeSessionResponse)(nil), "aura.auth.v1beta1.MsgRevokeSessionResponse")
}

func init() { proto.RegisterFile("aura/auth/v1beta1/tx.proto", fileDescriptor_0817cb4e425ce128) }

var fileDescriptor_0817cb4e425ce128 = []byte{
	// 1376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0xea, 0x34, 0x8d, 0x8f, 0x93, 0x22, 0x15, 0xb2, 0xd6, 0x53, 0xd3, 0x35, 0x55, 0x2e,
	0x1a, 0xac, 0x9d, 0xdd, 0x78, 0xdd, 0x5f, 0x8b, 0xb5, 0xf0, 0xd2, 0x5e, 0x04, 0x9b, 0x87, 0x42,
	0xcd, 0xba, 0xac, 0x28, 0xe0, 0x31, 0x12, 0xa1, 0x10, 0x91, 0x25, 0x4d, 0x94, 0x9d, 0x18, 0x28,
	0x30, 0x6c, 0x0f, 0x30, 0xec, 0x72, 0x57, 0x7b, 0x81, 0xed, 0x71, 0xf6, 0x00, 0x7b, 0x81, 0xbd,
	0xc3, 0x40, 0x52, 0xa4, 0x64, 0x5b, 0x94, 0xed, 0x61, 0x77, 0xe6, 0xf9, 0xe3, 0xf7, 0x9d, 0x73,
	0x48, 0x1e, 0x19, 0x2c, 0x34, 0x4c, 0x50, 0x1b, 0x0d, 0xd3, 0xd3, 0xf6, 0x68, 0xff, 0x04, 0xa7,
	0x68, 0xbf, 0x9d, 0x5e, 0xb4, 0xe2, 0x24, 0x4a, 0x23, 0xf3, 0x1a, 0xd3, 0xb5, 0x98, 0xae, 0x95,
	0xe9, 0xac, 0x2d, 0x3f, 0xf2, 0x23, 0xae, 0x6d, 0xb3, 0x5f, 0xc2, 0xd0, 0xda, 0x9e, 0x0d, 0xc2,
	0xbd, 0xb8, 0xd6, 0xfe, 0xc9, 0x80, 0x8d, 0x1e, 0xf5, 0x0f, 0x12, 0x8c, 0x52, 0xec, 0x44, 0x01,
	0x36, 0x9b, 0x70, 0xc5, 0x65, 0xab, 0x28, 0x69, 0x1a, 0x3b, 0xc6, 0x5e, 0xdd, 0x91, 0x4b, 0xd3,
	0x84, 0x95, 0x10, 0x0d, 0x70, 0xf3, 0x12, 0x17, 0xf3, 0xdf, 0xe6, 0x0e, 0x34, 0x62, 0x9c, 0x0c,
	0x08, 0xa5, 0x24, 0x0a, 0x69, 0xb3, 0xb6, 0x53, 0xdb, 0xab, 0x3b, 0x45, 0x11, 0xb3, 0xf0, 0x30,
	0x75, 0x13, 0x12, 0xa7, 0x24, 0x0a, 0x9b, 0x2b, 0xdc, 0xb9, 0x28, 0xb2, 0x9f, 0xc1, 0x3b, 0x13,
	0x10, 0x1c, 0x4c, 0xe3, 0x28, 0xa4, 0xd8, 0xbc, 0x07, 0x2b, 0x49, 0x14, 0x60, 0x8e, 0xa3, 0xd1,
	0xb9, 0xd1, 0x9a, 0xa1, 0xdc, 0xe2, 0xe6, 0xdc, 0xc8, 0xfe, 0x55, 0x30, 0xe9, 0x52, 0x4a, 0xfc,
	0x90, 0x33, 0xb1, 0x60, 0x0d, 0xf1, 0x15, 0x96, 0x54, 0xd4, 0x9a, 0xb1, 0x44, 0x9e, 0x97, 0x60,
	0x4a, 0x33, 0x3a, 0x72, 0x69, 0xde, 0x84, 0x3a, 0x8b, 0xd7, 0xe7, 0x54, 0x6b, 0xc2, 0x8d, 0x09,
	0xbe, 0x66, 0x74, 0xef, 0x83, 0x89, 0x2f, 0x62, 0x92, 0x60, 0xda, 0x27, 0x61, 0x9f, 0x62, 0x37,
	0x0a, 0x3d, 0xca, 0x39, 0xd5, 0x9c, 0xcd, 0x4c, 0x73, 0x18, 0xbe, 0x14, 0x72, 0xfb, 0x35, 0x27,
	0x96, 0x23, 0x52, 0xc4, 0xba, 0x00, 0x02, 0xc9, 0x00, 0x87, 0x69, 0x46, 0xef, 0x8e, 0x86, 0x5e,
	0x57, 0x19, 0x3a, 0x05, 0x27, 0xfb, 0x7b, 0xce, 0xd6, 0xc1, 0xa3, 0xe8, 0x4c, 0xd5, 0x2d, 0xe1,
	0x2b, 0x55, 0xb7, 0x6c, 0xf9, 0x1f, 0xb9, 0xda, 0xfb, 0x1c, 0x7d, 0xbe, 0x83, 0x42, 0xdf, 0x84,
	0x2b, 0x74, 0xe8, 0xba, 0x2c, 0x1e, 0xdb, 0x69, 0xcd, 0x91, 0x4b, 0xfb, 0x0f, 0x03, 0x6e, 0xa8,
	0x52, 0xf6, 0x86, 0x41, 0x4a, 0x28, 0xf1, 0xbf, 0x45, 0x41, 0x80, 0xd3, 0x8a, 0xbe, 0x62, 0xf1,
	0x78, 0x55, 0x18, 0x3e, 0xd6, 0x3f, 0x72, 0x69, 0x6e, 0x43, 0x3d, 0x3d, 0x4d, 0x30, 0x3d, 0x8d,
	0x02, 0x8f, 0xe3, 0xdb, 0x70, 0x72, 0x81, 0xf9, 0x04, 0x1a, 0xe7, 0x3c, 0x76, 0x3f, 0x1d, 0xc7,
	0x98, 0x57, 0xe1, 0x6a, 0xe7, 0x56, 0x49, 0x1a, 0x05, 0x82, 0xa3, 0x71, 0x8c, 0x1d, 0x38, 0x57,
	0xbf, 0xed, 0x37, 0x70, 0x5b, 0x03, 0x56, 0x51, 0xfd, 0x0c, 0x56, 0x85, 0x43, 0x45, 0x91, 0xa6,
	0x5c, 0x33, 0x07, 0xfb, 0x2f, 0x03, 0xde, 0x9d, 0x09, 0xff, 0x22, 0x89, 0xe2, 0x88, 0xa2, 0x80,
	0xf5, 0x66, 0xcc, 0x7f, 0xe7, 0xbd, 0x29, 0xd7, 0xac, 0x2a, 0x19, 0x2f, 0xe2, 0x65, 0x15, 0x5b,
	0x13, 0x82, 0x43, 0xcf, 0xdc, 0x82, 0xcb, 0x29, 0x49, 0x03, 0x59, 0x2e, 0xb1, 0x98, 0x7f, 0xc8,
	0x58, 0x92, 0x63, 0x34, 0x0e, 0x22, 0xe4, 0x35, 0x2f, 0xef, 0x18, 0x7b, 0xeb, 0x8e, 0x5c, 0x6a,
	0x7a, 0x7a, 0x55, 0xd3, 0xd3, 0x1e, 0xdc, 0xd1, 0xb2, 0x52, 0x69, 0x7b, 0x2a, 0xd9, 0xa1, 0x20,
	0x4b, 0xdc, 0x6e, 0x45, 0xe2, 0x94, 0xbb, 0x72, 0xb2, 0x1d, 0xde, 0x47, 0x2f, 0x89, 0x1f, 0xce,
	0x64, 0xee, 0x3a, 0xac, 0x4e, 0x9c, 0xe9, 0x6c, 0x65, 0xde, 0x86, 0x86, 0x74, 0xcf, 0xf3, 0x06,
	0x52, 0x74, 0xe8, 0xd9, 0x27, 0xbc, 0xdc, 0x65, 0x31, 0xff, 0x3f, 0xdc, 0xdf, 0x81, 0xd5, 0xa3,
	0xfe, 0xf3, 0x0b, 0xec, 0x0e, 0xcb, 0x8b, 0x8e, 0xb9, 0x4a, 0x9d, 0x01, 0xb5, 0x9e, 0x0f, 0xff,
	0x09, 0xd8, 0xfa, 0xd0, 0x0b, 0x9c, 0xcd, 0xdf, 0x0c, 0x8e, 0x4d, 0x78, 0xe0, 0x23, 0x32, 0xc0,
	0x5f, 0x45, 0xee, 0x19, 0xf6, 0xba, 0x2e, 0xef, 0x8f, 0xaa, 0x86, 0xbc, 0x0d, 0x0d, 0xc4, 0xad,
	0xc4, 0x41, 0xcb, 0xb0, 0x09, 0x11, 0x3b, 0x49, 0xc5, 0xe6, 0xaa, 0x4d, 0x36, 0xd7, 0x2e, 0x6c,
	0x78, 0x38, 0x40, 0xe3, 0x89, 0xbb, 0x72, 0xc5, 0x59, 0xe7, 0x42, 0xd9, 0x53, 0x88, 0x53, 0xd3,
	0x20, 0x53, 0xd4, 0x1e, 0xc3, 0xaa, 0xd8, 0xb2, 0xa2, 0x34, 0x33, 0xce, 0x99, 0x8b, 0xfd, 0x4d,
	0xb1, 0x30, 0x65, 0xe4, 0xb5, 0x85, 0xb9, 0x09, 0xf5, 0x8c, 0x7c, 0x7e, 0x1a, 0x85, 0x60, 0xba,
	0x28, 0x5a, 0xe4, 0xfa, 0xa2, 0xbc, 0x12, 0x77, 0x04, 0x0a, 0x5d, 0x1c, 0xcc, 0xa0, 0xda, 0x86,
	0xba, 0xcb, 0x35, 0x81, 0xaa, 0x49, 0x2e, 0xa8, 0xc6, 0xf5, 0xb9, 0x38, 0xa5, 0xa5, 0x71, 0x17,
	0x80, 0xf5, 0xa7, 0xb8, 0xbb, 0x98, 0xfd, 0x08, 0xa5, 0xf8, 0xf9, 0x00, 0x27, 0x3e, 0x0e, 0xdd,
	0x71, 0xd7, 0x1b, 0x10, 0x8e, 0x0b, 0x09, 0x8d, 0x4a, 0x57, 0x2e, 0x60, 0x15, 0x47, 0xcc, 0xac,
	0x3f, 0xf9, 0xe6, 0xac, 0x73, 0x61, 0x37, 0x7b, 0x78, 0xde, 0x03, 0x88, 0x13, 0x32, 0x22, 0x01,
	0xf6, 0xb1, 0x9c, 0x1a, 0x0a, 0x92, 0x25, 0xdf, 0xd9, 0x37, 0x9c, 0x6d, 0x39, 0x5a, 0xc5, 0xf6,
	0x13, 0xb8, 0xcc, 0x21, 0x54, 0xdc, 0xe4, 0x53, 0x9e, 0xc2, 0xde, 0xf6, 0xe0, 0x66, 0x8f, 0xfa,
	0xcf, 0x30, 0x2a, 0xcf, 0x06, 0xbf, 0x7a, 0xa7, 0xf3, 0x51, 0x14, 0x2d, 0x94, 0x11, 0xfb, 0x29,
	0xec, 0x56, 0xec, 0xb2, 0x40, 0xcd, 0x7e, 0x37, 0xf8, 0xfd, 0x76, 0x18, 0x92, 0x94, 0xa0, 0x14,
	0xbf, 0x42, 0x01, 0xf1, 0xd8, 0xf6, 0x5f, 0xe2, 0xb1, 0x13, 0xa5, 0x48, 0x76, 0x14, 0x11, 0xfa,
	0xbc, 0x72, 0x4a, 0x60, 0xde, 0x83, 0x6b, 0x23, 0xe9, 0x35, 0x85, 0x75, 0x53, 0x29, 0x64, 0x05,
	0x1f, 0xc0, 0x56, 0x88, 0xcf, 0xfb, 0x2e, 0x43, 0x15, 0xd2, 0x21, 0xed, 0xc7, 0xc3, 0x93, 0x33,
	0x3c, 0xce, 0x9e, 0x25, 0x33, 0xc4, 0xe7, 0x07, 0x52, 0xf5, 0x82, 0x6b, 0xec, 0x10, 0xee, 0xce,
	0xc1, 0xa7, 0x58, 0x1e, 0xc0, 0x5a, 0x92, 0xc9, 0xb2, 0x72, 0xdd, 0x2d, 0x29, 0x57, 0x69, 0x08,
	0xe5, 0x68, 0x07, 0xe2, 0x79, 0x8f, 0x06, 0x71, 0x80, 0xf5, 0xf9, 0x70, 0x33, 0x7d, 0x7e, 0xc2,
	0xa4, 0x60, 0xa9, 0x7c, 0xd8, 0x07, 0x9c, 0x5d, 0xd5, 0x6e, 0x0b, 0xd4, 0xf0, 0x6f, 0x03, 0x36,
	0xd5, 0xeb, 0xfa, 0x12, 0xf3, 0x09, 0xda, 0xbc, 0x03, 0xeb, 0x43, 0x8a, 0x73, 0x04, 0x59, 0x87,
	0x31, 0x99, 0x2c, 0xc6, 0x2d, 0x00, 0x12, 0x4f, 0x41, 0xac, 0x93, 0x58, 0xaa, 0x7b, 0xb0, 0x36,
	0xc0, 0x29, 0xf2, 0x50, 0x8a, 0xf8, 0x59, 0x6b, 0x74, 0xf6, 0xcb, 0x9e, 0xb5, 0xa9, 0x8d, 0x5b,
	0xbd, 0xcc, 0xe7, 0x79, 0x98, 0x26, 0x63, 0x47, 0x85, 0xb0, 0x1e, 0xc3, 0xc6, 0x84, 0xca, 0xdc,
	0x84, 0x1a, 0x2b, 0xbd, 0x00, 0xc6, 0x7e, 0xb2, 0x29, 0x65, 0x84, 0x82, 0xa1, 0x7c, 0x2b, 0xc4,
	0xe2, 0xd1, 0xa5, 0x4f, 0x0d, 0xfb, 0x05, 0x34, 0xa7, 0x37, 0x52, 0x89, 0x79, 0x08, 0x57, 0xa8,
	0x10, 0x65, 0x55, 0xb7, 0x4a, 0x60, 0x4a, 0x27, 0x69, 0x6a, 0x1f, 0xf1, 0x9c, 0x89, 0x39, 0x75,
	0xb9, 0x9c, 0x65, 0x11, 0xf2, 0x0b, 0xb4, 0x9e, 0x49, 0x0e, 0x3d, 0xfb, 0x21, 0xc7, 0x39, 0x11,
	0x75, 0x7e, 0x01, 0x3b, 0xff, 0x5c, 0x85, 0x5a, 0x8f, 0xfa, 0xe6, 0x31, 0x40, 0xe1, 0x93, 0x6a,
	0xa7, 0x2a, 0xdb, 0xcc, 0xc2, 0xda, 0x9b, 0x67, 0xa1, 0xf6, 0x3e, 0x06, 0x28, 0x7c, 0xe2, 0x68,
	0x22, 0xe7, 0x16, 0xba, 0xc8, 0x25, 0x1f, 0x25, 0xc7, 0x00, 0x85, 0xcf, 0x09, 0x4d, 0xe4, 0xdc,
	0x42, 0x17, 0xb9, 0xe4, 0x83, 0x61, 0x04, 0x5b, 0xa5, 0x9f, 0x04, 0xef, 0x57, 0xb1, 0x9e, 0xb4,
	0xb5, 0x3a, 0x8b, 0xdb, 0xaa, 0x7d, 0xdf, 0xc2, 0x75, 0xcd, 0xf8, 0x7d, 0x7f, 0x91, 0x68, 0xd2,
	0xda, 0x7a, 0xb8, 0x8c, 0x75, 0x91, 0x75, 0xe9, 0x00, 0xab, 0x61, 0x5d, 0x66, 0xab, 0x63, 0x5d,
	0x39, 0xc4, 0xfe, 0x08, 0x37, 0x74, 0x03, 0xe8, 0x07, 0xe5, 0xe1, 0x34, 0xe6, 0xd6, 0x47, 0x4b,
	0x99, 0x17, 0x01, 0xe8, 0xa6, 0x4c, 0x0d, 0x00, 0x8d, 0xb9, 0x0e, 0xc0, 0xbc, 0x49, 0x31, 0xcf,
	0xc0, 0xa2, 0x00, 0x34, 0xe6, 0x73, 0x32, 0xa0, 0x05, 0xc0, 0x1a, 0xaf, 0x7c, 0xa6, 0xd3, 0x35,
	0x5e, 0xa9, 0xb5, 0xb6, 0xf1, 0xaa, 0xe7, 0xba, 0xb7, 0x70, 0x5d, 0x33, 0xb9, 0x69, 0x76, 0x2f,
	0xb7, 0xd6, 0xed, 0x3e, 0x67, 0xce, 0xfa, 0xd9, 0x80, 0xa6, 0x76, 0x58, 0x6a, 0x95, 0x87, 0xd4,
	0xd9, 0x5b, 0x1f, 0x2f, 0x67, 0xaf, 0x40, 0xfc, 0x62, 0xc0, 0x76, 0xe5, 0x24, 0xa4, 0x39, 0x58,
	0x55, 0x3e, 0xd6, 0xa3, 0xe5, 0x7d, 0x26, 0x00, 0x55, 0x8e, 0x22, 0xba, 0xfb, 0xad, 0xc2, 0x47,
	0x07, 0x68, 0xa1, 0x21, 0x04, 0xc1, 0xc6, 0xe4, 0x98, 0xb1, 0xbb, 0xc0, 0x48, 0x60, 0xdd, 0x5b,
	0xc0, 0xa8, 0xb8, 0xc5, 0xe4, 0xab, 0xbc, 0x5b, 0xf5, 0x62, 0xcc, 0xd9, 0xa2, 0xf4, 0x25, 0xfe,
	0xa2, 0xf3, 0xfa, 0x81, 0x4f, 0xd2, 0xd3, 0xe1, 0x49, 0xcb, 0x8d, 0x06, 0x6d, 0x84, 0x7f, 0x18,
	0x92, 0x14, 0xd1, 0x36, 0xff, 0xcb, 0x53, 0xfc, 0x13, 0x3a, 0xf3, 0xef, 0xe7, 0xc9, 0x2a, 0x57,
	0x7c, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x75, 0x3d, 0xd8, 0x5e, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateRole creates a new role
	CreateRole(ctx context.Context, in *MsgCreateRole, opts ...grpc.CallOption) (*MsgCreateRoleResponse, error)
	// AssignRole assigns a role to an address
	AssignRole(ctx context.Context, in *MsgAssignRole, opts ...grpc.CallOption) (*MsgAssignRoleResponse, error)
	// RevokeRole revokes a role from an address
	RevokeRole(ctx context.Context, in *MsgRevokeRole, opts ...grpc.CallOption) (*MsgRevokeRoleResponse, error)
	// CreateMultisigWallet creates a new multisig wallet
	CreateMultisigWallet(ctx context.Context, in *MsgCreateMultisigWallet, opts ...grpc.CallOption) (*MsgCreateMultisigWalletResponse, error)
	// CreateMultisigProposal creates a new multisig proposal
	CreateMultisigProposal(ctx context.Context, in *MsgCreateMultisigProposal, opts ...grpc.CallOption) (*MsgCreateMultisigProposalResponse, error)
	// SignMultisigProposal signs a multisig proposal
	SignMultisigProposal(ctx context.Context, in *MsgSignMultisigProposal, opts ...grpc.CallOption) (*MsgSignMultisigProposalResponse, error)
	// ExecuteMultisigProposal executes an approved multisig proposal
	ExecuteMultisigProposal(ctx context.Context, in *MsgExecuteMultisigProposal, opts ...grpc.CallOption) (*MsgExecuteMultisigProposalResponse, error)
	// ProposeTimeLockedAction proposes a time-locked admin action
	ProposeTimeLockedAction(ctx context.Context, in *MsgProposeTimeLockedAction, opts ...grpc.CallOption) (*MsgProposeTimeLockedActionResponse, error)
	// ExecuteTimeLockedAction executes a ready time-locked action
	ExecuteTimeLockedAction(ctx context.Context, in *MsgExecuteTimeLockedAction, opts ...grpc.CallOption) (*MsgExecuteTimeLockedActionResponse, error)
	// CancelTimeLockedAction cancels a pending time-locked action
	CancelTimeLockedAction(ctx context.Context, in *MsgCancelTimeLockedAction, opts ...grpc.CallOption) (*MsgCancelTimeLockedActionResponse, error)
	// ActivateEmergencyAdmin activates an emergency admin
	ActivateEmergencyAdmin(ctx context.Context, in *MsgActivateEmergencyAdmin, opts ...grpc.CallOption) (*MsgActivateEmergencyAdminResponse, error)
	// DeactivateEmergencyAdmin deactivates an emergency admin
	DeactivateEmergencyAdmin(ctx context.Context, in *MsgDeactivateEmergencyAdmin, opts ...grpc.CallOption) (*MsgDeactivateEmergencyAdminResponse, error)
	// InitiateValidatorKeyRotation initiates validator key rotation
	InitiateValidatorKeyRotation(ctx context.Context, in *MsgInitiateValidatorKeyRotation, opts ...grpc.CallOption) (*MsgInitiateValidatorKeyRotationResponse, error)
	// CompleteValidatorKeyRotation completes validator key rotation
	CompleteValidatorKeyRotation(ctx context.Context, in *MsgCompleteValidatorKeyRotation, opts ...grpc.CallOption) (*MsgCompleteValidatorKeyRotationResponse, error)
	// CreateSession creates a new API session
	CreateSession(ctx context.Context, in *MsgCreateSession, opts ...grpc.CallOption) (*MsgCreateSessionResponse, error)
	// RevokeSession revokes an active session
	RevokeSession(ctx context.Context, in *MsgRevokeSession, opts ...grpc.CallOption) (*MsgRevokeSessionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateRole(ctx context.Context, in *MsgCreateRole, opts ...grpc.CallOption) (*MsgCreateRoleResponse, error) {
	out := new(MsgCreateRoleResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AssignRole(ctx context.Context, in *MsgAssignRole, opts ...grpc.CallOption) (*MsgAssignRoleResponse, error) {
	out := new(MsgAssignRoleResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/AssignRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeRole(ctx context.Context, in *MsgRevokeRole, opts ...grpc.CallOption) (*MsgRevokeRoleResponse, error) {
	out := new(MsgRevokeRoleResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/RevokeRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateMultisigWallet(ctx context.Context, in *MsgCreateMultisigWallet, opts ...grpc.CallOption) (*MsgCreateMultisigWalletResponse, error) {
	out := new(MsgCreateMultisigWalletResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CreateMultisigWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateMultisigProposal(ctx context.Context, in *MsgCreateMultisigProposal, opts ...grpc.CallOption) (*MsgCreateMultisigProposalResponse, error) {
	out := new(MsgCreateMultisigProposalResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CreateMultisigProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SignMultisigProposal(ctx context.Context, in *MsgSignMultisigProposal, opts ...grpc.CallOption) (*MsgSignMultisigProposalResponse, error) {
	out := new(MsgSignMultisigProposalResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/SignMultisigProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteMultisigProposal(ctx context.Context, in *MsgExecuteMultisigProposal, opts ...grpc.CallOption) (*MsgExecuteMultisigProposalResponse, error) {
	out := new(MsgExecuteMultisigProposalResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/ExecuteMultisigProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProposeTimeLockedAction(ctx context.Context, in *MsgProposeTimeLockedAction, opts ...grpc.CallOption) (*MsgProposeTimeLockedActionResponse, error) {
	out := new(MsgProposeTimeLockedActionResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/ProposeTimeLockedAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteTimeLockedAction(ctx context.Context, in *MsgExecuteTimeLockedAction, opts ...grpc.CallOption) (*MsgExecuteTimeLockedActionResponse, error) {
	out := new(MsgExecuteTimeLockedActionResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/ExecuteTimeLockedAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelTimeLockedAction(ctx context.Context, in *MsgCancelTimeLockedAction, opts ...grpc.CallOption) (*MsgCancelTimeLockedActionResponse, error) {
	out := new(MsgCancelTimeLockedActionResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CancelTimeLockedAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ActivateEmergencyAdmin(ctx context.Context, in *MsgActivateEmergencyAdmin, opts ...grpc.CallOption) (*MsgActivateEmergencyAdminResponse, error) {
	out := new(MsgActivateEmergencyAdminResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/ActivateEmergencyAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeactivateEmergencyAdmin(ctx context.Context, in *MsgDeactivateEmergencyAdmin, opts ...grpc.CallOption) (*MsgDeactivateEmergencyAdminResponse, error) {
	out := new(MsgDeactivateEmergencyAdminResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/DeactivateEmergencyAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitiateValidatorKeyRotation(ctx context.Context, in *MsgInitiateValidatorKeyRotation, opts ...grpc.CallOption) (*MsgInitiateValidatorKeyRotationResponse, error) {
	out := new(MsgInitiateValidatorKeyRotationResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/InitiateValidatorKeyRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CompleteValidatorKeyRotation(ctx context.Context, in *MsgCompleteValidatorKeyRotation, opts ...grpc.CallOption) (*MsgCompleteValidatorKeyRotationResponse, error) {
	out := new(MsgCompleteValidatorKeyRotationResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CompleteValidatorKeyRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSession(ctx context.Context, in *MsgCreateSession, opts ...grpc.CallOption) (*MsgCreateSessionResponse, error) {
	out := new(MsgCreateSessionResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeSession(ctx context.Context, in *MsgRevokeSession, opts ...grpc.CallOption) (*MsgRevokeSessionResponse, error) {
	out := new(MsgRevokeSessionResponse)
	err := c.cc.Invoke(ctx, "/aura.auth.v1beta1.Msg/RevokeSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateRole creates a new role
	CreateRole(context.Context, *MsgCreateRole) (*MsgCreateRoleResponse, error)
	// AssignRole assigns a role to an address
	AssignRole(context.Context, *MsgAssignRole) (*MsgAssignRoleResponse, error)
	// RevokeRole revokes a role from an address
	RevokeRole(context.Context, *MsgRevokeRole) (*MsgRevokeRoleResponse, error)
	// CreateMultisigWallet creates a new multisig wallet
	CreateMultisigWallet(context.Context, *MsgCreateMultisigWallet) (*MsgCreateMultisigWalletResponse, error)
	// CreateMultisigProposal creates a new multisig proposal
	CreateMultisigProposal(context.Context, *MsgCreateMultisigProposal) (*MsgCreateMultisigProposalResponse, error)
	// SignMultisigProposal signs a multisig proposal
	SignMultisigProposal(context.Context, *MsgSignMultisigProposal) (*MsgSignMultisigProposalResponse, error)
	// ExecuteMultisigProposal executes an approved multisig proposal
	ExecuteMultisigProposal(context.Context, *MsgExecuteMultisigProposal) (*MsgExecuteMultisigProposalResponse, error)
	// ProposeTimeLockedAction proposes a time-locked admin action
	ProposeTimeLockedAction(context.Context, *MsgProposeTimeLockedAction) (*MsgProposeTimeLockedActionResponse, error)
	// ExecuteTimeLockedAction executes a ready time-locked action
	ExecuteTimeLockedAction(context.Context, *MsgExecuteTimeLockedAction) (*MsgExecuteTimeLockedActionResponse, error)
	// CancelTimeLockedAction cancels a pending time-locked action
	CancelTimeLockedAction(context.Context, *MsgCancelTimeLockedAction) (*MsgCancelTimeLockedActionResponse, error)
	// ActivateEmergencyAdmin activates an emergency admin
	ActivateEmergencyAdmin(context.Context, *MsgActivateEmergencyAdmin) (*MsgActivateEmergencyAdminResponse, error)
	// DeactivateEmergencyAdmin deactivates an emergency admin
	DeactivateEmergencyAdmin(context.Context, *MsgDeactivateEmergencyAdmin) (*MsgDeactivateEmergencyAdminResponse, error)
	// InitiateValidatorKeyRotation initiates validator key rotation
	InitiateValidatorKeyRotation(context.Context, *MsgInitiateValidatorKeyRotation) (*MsgInitiateValidatorKeyRotationResponse, error)
	// CompleteValidatorKeyRotation completes validator key rotation
	CompleteValidatorKeyRotation(context.Context, *MsgCompleteValidatorKeyRotation) (*MsgCompleteValidatorKeyRotationResponse, error)
	// CreateSession creates a new API session
	CreateSession(context.Context, *MsgCreateSession) (*MsgCreateSessionResponse, error)
	// RevokeSession revokes an active session
	RevokeSession(context.Context, *MsgRevokeSession) (*MsgRevokeSessionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateRole(ctx context.Context, req *MsgCreateRole) (*MsgCreateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedMsgServer) AssignRole(ctx context.Context, req *MsgAssignRole) (*MsgAssignRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRole not implemented")
}
func (*UnimplementedMsgServer) RevokeRole(ctx context.Context, req *MsgRevokeRole) (*MsgRevokeRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeRole not implemented")
}
func (*UnimplementedMsgServer) CreateMultisigWallet(ctx context.Context, req *MsgCreateMultisigWallet) (*MsgCreateMultisigWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultisigWallet not implemented")
}
func (*UnimplementedMsgServer) CreateMultisigProposal(ctx context.Context, req *MsgCreateMultisigProposal) (*MsgCreateMultisigProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultisigProposal not implemented")
}
func (*UnimplementedMsgServer) SignMultisigProposal(ctx context.Context, req *MsgSignMultisigProposal) (*MsgSignMultisigProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMultisigProposal not implemented")
}
func (*UnimplementedMsgServer) ExecuteMultisigProposal(ctx context.Context, req *MsgExecuteMultisigProposal) (*MsgExecuteMultisigProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteMultisigProposal not implemented")
}
func (*UnimplementedMsgServer) ProposeTimeLockedAction(ctx context.Context, req *MsgProposeTimeLockedAction) (*MsgProposeTimeLockedActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeTimeLockedAction not implemented")
}
func (*UnimplementedMsgServer) ExecuteTimeLockedAction(ctx context.Context, req *MsgExecuteTimeLockedAction) (*MsgExecuteTimeLockedActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTimeLockedAction not implemented")
}
func (*UnimplementedMsgServer) CancelTimeLockedAction(ctx context.Context, req *MsgCancelTimeLockedAction) (*MsgCancelTimeLockedActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTimeLockedAction not implemented")
}
func (*UnimplementedMsgServer) ActivateEmergencyAdmin(ctx context.Context, req *MsgActivateEmergencyAdmin) (*MsgActivateEmergencyAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateEmergencyAdmin not implemented")
}
func (*UnimplementedMsgServer) DeactivateEmergencyAdmin(ctx context.Context, req *MsgDeactivateEmergencyAdmin) (*MsgDeactivateEmergencyAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateEmergencyAdmin not implemented")
}
func (*UnimplementedMsgServer) InitiateValidatorKeyRotation(ctx context.Context, req *MsgInitiateValidatorKeyRotation) (*MsgInitiateValidatorKeyRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateValidatorKeyRotation not implemented")
}
func (*UnimplementedMsgServer) CompleteValidatorKeyRotation(ctx context.Context, req *MsgCompleteValidatorKeyRotation) (*MsgCompleteValidatorKeyRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteValidatorKeyRotation not implemented")
}
func (*UnimplementedMsgServer) CreateSession(ctx context.Context, req *MsgCreateSession) (*MsgCreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (*UnimplementedMsgServer) RevokeSession(ctx context.Context, req *MsgRevokeSession) (*MsgRevokeSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSession not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRole)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRole(ctx, req.(*MsgCreateRole))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAssignRole)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/AssignRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AssignRole(ctx, req.(*MsgAssignRole))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeRole)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/RevokeRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeRole(ctx, req.(*MsgRevokeRole))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateMultisigWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateMultisigWallet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateMultisigWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CreateMultisigWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateMultisigWallet(ctx, req.(*MsgCreateMultisigWallet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateMultisigProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateMultisigProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateMultisigProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CreateMultisigProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateMultisigProposal(ctx, req.(*MsgCreateMultisigProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SignMultisigProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignMultisigProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SignMultisigProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/SignMultisigProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SignMultisigProposal(ctx, req.(*MsgSignMultisigProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteMultisigProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteMultisigProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteMultisigProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/ExecuteMultisigProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteMultisigProposal(ctx, req.(*MsgExecuteMultisigProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProposeTimeLockedAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeTimeLockedAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeTimeLockedAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/ProposeTimeLockedAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeTimeLockedAction(ctx, req.(*MsgProposeTimeLockedAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteTimeLockedAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteTimeLockedAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteTimeLockedAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/ExecuteTimeLockedAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteTimeLockedAction(ctx, req.(*MsgExecuteTimeLockedAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelTimeLockedAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelTimeLockedAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelTimeLockedAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CancelTimeLockedAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelTimeLockedAction(ctx, req.(*MsgCancelTimeLockedAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ActivateEmergencyAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgActivateEmergencyAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ActivateEmergencyAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/ActivateEmergencyAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ActivateEmergencyAdmin(ctx, req.(*MsgActivateEmergencyAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeactivateEmergencyAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeactivateEmergencyAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeactivateEmergencyAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/DeactivateEmergencyAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeactivateEmergencyAdmin(ctx, req.(*MsgDeactivateEmergencyAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitiateValidatorKeyRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateValidatorKeyRotation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateValidatorKeyRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/InitiateValidatorKeyRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateValidatorKeyRotation(ctx, req.(*MsgInitiateValidatorKeyRotation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CompleteValidatorKeyRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCompleteValidatorKeyRotation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CompleteValidatorKeyRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CompleteValidatorKeyRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CompleteValidatorKeyRotation(ctx, req.(*MsgCompleteValidatorKeyRotation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSession(ctx, req.(*MsgCreateSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aura.auth.v1beta1.Msg/RevokeSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeSession(ctx, req.(*MsgRevokeSession))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aura.auth.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _Msg_CreateRole_Handler,
		},
		{
			MethodName: "AssignRole",
			Handler:    _Msg_AssignRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _Msg_RevokeRole_Handler,
		},
		{
			MethodName: "CreateMultisigWallet",
			Handler:    _Msg_CreateMultisigWallet_Handler,
		},
		{
			MethodName: "CreateMultisigProposal",
			Handler:    _Msg_CreateMultisigProposal_Handler,
		},
		{
			MethodName: "SignMultisigProposal",
			Handler:    _Msg_SignMultisigProposal_Handler,
		},
		{
			MethodName: "ExecuteMultisigProposal",
			Handler:    _Msg_ExecuteMultisigProposal_Handler,
		},
		{
			MethodName: "ProposeTimeLockedAction",
			Handler:    _Msg_ProposeTimeLockedAction_Handler,
		},
		{
			MethodName: "ExecuteTimeLockedAction",
			Handler:    _Msg_ExecuteTimeLockedAction_Handler,
		},
		{
			MethodName: "CancelTimeLockedAction",
			Handler:    _Msg_CancelTimeLockedAction_Handler,
		},
		{
			MethodName: "ActivateEmergencyAdmin",
			Handler:    _Msg_ActivateEmergencyAdmin_Handler,
		},
		{
			MethodName: "DeactivateEmergencyAdmin",
			Handler:    _Msg_DeactivateEmergencyAdmin_Handler,
		},
		{
			MethodName: "InitiateValidatorKeyRotation",
			Handler:    _Msg_InitiateValidatorKeyRotation_Handler,
		},
		{
			MethodName: "CompleteValidatorKeyRotation",
			Handler:    _Msg_CompleteValidatorKeyRotation_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Msg_CreateSession_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _Msg_RevokeSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aura/auth/v1beta1/tx.proto",
}
