// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aura/identitychange/v1beta1/identity_change.proto

package identitychangepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RequestIdentityChange_FullMethodName  = "/aura.identitychange.v1beta1.Msg/RequestIdentityChange"
	Msg_SubmitAssistantProof_FullMethodName   = "/aura.identitychange.v1beta1.Msg/SubmitAssistantProof"
	Msg_ApplyIdentityChange_FullMethodName    = "/aura.identitychange.v1beta1.Msg/ApplyIdentityChange"
	Msg_RejectIdentityChange_FullMethodName   = "/aura.identitychange.v1beta1.Msg/RejectIdentityChange"
	Msg_SuspendIdentityChanges_FullMethodName = "/aura.identitychange.v1beta1.Msg/SuspendIdentityChanges"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	RequestIdentityChange(ctx context.Context, in *MsgRequestIdentityChange, opts ...grpc.CallOption) (*MsgRequestIdentityChangeResponse, error)
	SubmitAssistantProof(ctx context.Context, in *MsgSubmitAssistantProof, opts ...grpc.CallOption) (*MsgSubmitAssistantProofResponse, error)
	ApplyIdentityChange(ctx context.Context, in *MsgApplyIdentityChange, opts ...grpc.CallOption) (*MsgApplyIdentityChangeResponse, error)
	RejectIdentityChange(ctx context.Context, in *MsgRejectIdentityChange, opts ...grpc.CallOption) (*MsgRejectIdentityChangeResponse, error)
	SuspendIdentityChanges(ctx context.Context, in *MsgSuspendIdentityChanges, opts ...grpc.CallOption) (*MsgSuspendIdentityChangesResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RequestIdentityChange(ctx context.Context, in *MsgRequestIdentityChange, opts ...grpc.CallOption) (*MsgRequestIdentityChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRequestIdentityChangeResponse)
	err := c.cc.Invoke(ctx, Msg_RequestIdentityChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitAssistantProof(ctx context.Context, in *MsgSubmitAssistantProof, opts ...grpc.CallOption) (*MsgSubmitAssistantProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitAssistantProofResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitAssistantProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApplyIdentityChange(ctx context.Context, in *MsgApplyIdentityChange, opts ...grpc.CallOption) (*MsgApplyIdentityChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgApplyIdentityChangeResponse)
	err := c.cc.Invoke(ctx, Msg_ApplyIdentityChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectIdentityChange(ctx context.Context, in *MsgRejectIdentityChange, opts ...grpc.CallOption) (*MsgRejectIdentityChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRejectIdentityChangeResponse)
	err := c.cc.Invoke(ctx, Msg_RejectIdentityChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SuspendIdentityChanges(ctx context.Context, in *MsgSuspendIdentityChanges, opts ...grpc.CallOption) (*MsgSuspendIdentityChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSuspendIdentityChangesResponse)
	err := c.cc.Invoke(ctx, Msg_SuspendIdentityChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	RequestIdentityChange(context.Context, *MsgRequestIdentityChange) (*MsgRequestIdentityChangeResponse, error)
	SubmitAssistantProof(context.Context, *MsgSubmitAssistantProof) (*MsgSubmitAssistantProofResponse, error)
	ApplyIdentityChange(context.Context, *MsgApplyIdentityChange) (*MsgApplyIdentityChangeResponse, error)
	RejectIdentityChange(context.Context, *MsgRejectIdentityChange) (*MsgRejectIdentityChangeResponse, error)
	SuspendIdentityChanges(context.Context, *MsgSuspendIdentityChanges) (*MsgSuspendIdentityChangesResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RequestIdentityChange(context.Context, *MsgRequestIdentityChange) (*MsgRequestIdentityChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestIdentityChange not implemented")
}
func (UnimplementedMsgServer) SubmitAssistantProof(context.Context, *MsgSubmitAssistantProof) (*MsgSubmitAssistantProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAssistantProof not implemented")
}
func (UnimplementedMsgServer) ApplyIdentityChange(context.Context, *MsgApplyIdentityChange) (*MsgApplyIdentityChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyIdentityChange not implemented")
}
func (UnimplementedMsgServer) RejectIdentityChange(context.Context, *MsgRejectIdentityChange) (*MsgRejectIdentityChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectIdentityChange not implemented")
}
func (UnimplementedMsgServer) SuspendIdentityChanges(context.Context, *MsgSuspendIdentityChanges) (*MsgSuspendIdentityChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendIdentityChanges not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RequestIdentityChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestIdentityChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestIdentityChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RequestIdentityChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestIdentityChange(ctx, req.(*MsgRequestIdentityChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitAssistantProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitAssistantProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitAssistantProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitAssistantProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitAssistantProof(ctx, req.(*MsgSubmitAssistantProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApplyIdentityChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApplyIdentityChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApplyIdentityChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ApplyIdentityChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApplyIdentityChange(ctx, req.(*MsgApplyIdentityChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectIdentityChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectIdentityChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectIdentityChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RejectIdentityChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectIdentityChange(ctx, req.(*MsgRejectIdentityChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SuspendIdentityChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSuspendIdentityChanges)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SuspendIdentityChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SuspendIdentityChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SuspendIdentityChanges(ctx, req.(*MsgSuspendIdentityChanges))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aura.identitychange.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestIdentityChange",
			Handler:    _Msg_RequestIdentityChange_Handler,
		},
		{
			MethodName: "SubmitAssistantProof",
			Handler:    _Msg_SubmitAssistantProof_Handler,
		},
		{
			MethodName: "ApplyIdentityChange",
			Handler:    _Msg_ApplyIdentityChange_Handler,
		},
		{
			MethodName: "RejectIdentityChange",
			Handler:    _Msg_RejectIdentityChange_Handler,
		},
		{
			MethodName: "SuspendIdentityChanges",
			Handler:    _Msg_SuspendIdentityChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aura/identitychange/v1beta1/identity_change.proto",
}

const (
	Query_IdentityRecord_FullMethodName        = "/aura.identitychange.v1beta1.Query/IdentityRecord"
	Query_IdentityChangeRequest_FullMethodName = "/aura.identitychange.v1beta1.Query/IdentityChangeRequest"
	Query_IdentityChangeHistory_FullMethodName = "/aura.identitychange.v1beta1.Query/IdentityChangeHistory"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	IdentityRecord(ctx context.Context, in *QueryIdentityRecordRequest, opts ...grpc.CallOption) (*QueryIdentityRecordResponse, error)
	IdentityChangeRequest(ctx context.Context, in *QueryIdentityChangeRequestRequest, opts ...grpc.CallOption) (*QueryIdentityChangeRequestResponse, error)
	IdentityChangeHistory(ctx context.Context, in *QueryIdentityChangeHistoryRequest, opts ...grpc.CallOption) (*QueryIdentityChangeHistoryResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) IdentityRecord(ctx context.Context, in *QueryIdentityRecordRequest, opts ...grpc.CallOption) (*QueryIdentityRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIdentityRecordResponse)
	err := c.cc.Invoke(ctx, Query_IdentityRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityChangeRequest(ctx context.Context, in *QueryIdentityChangeRequestRequest, opts ...grpc.CallOption) (*QueryIdentityChangeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIdentityChangeRequestResponse)
	err := c.cc.Invoke(ctx, Query_IdentityChangeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityChangeHistory(ctx context.Context, in *QueryIdentityChangeHistoryRequest, opts ...grpc.CallOption) (*QueryIdentityChangeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIdentityChangeHistoryResponse)
	err := c.cc.Invoke(ctx, Query_IdentityChangeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	IdentityRecord(context.Context, *QueryIdentityRecordRequest) (*QueryIdentityRecordResponse, error)
	IdentityChangeRequest(context.Context, *QueryIdentityChangeRequestRequest) (*QueryIdentityChangeRequestResponse, error)
	IdentityChangeHistory(context.Context, *QueryIdentityChangeHistoryRequest) (*QueryIdentityChangeHistoryResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) IdentityRecord(context.Context, *QueryIdentityRecordRequest) (*QueryIdentityRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityRecord not implemented")
}
func (UnimplementedQueryServer) IdentityChangeRequest(context.Context, *QueryIdentityChangeRequestRequest) (*QueryIdentityChangeRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityChangeRequest not implemented")
}
func (UnimplementedQueryServer) IdentityChangeHistory(context.Context, *QueryIdentityChangeHistoryRequest) (*QueryIdentityChangeHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityChangeHistory not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_IdentityRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityRecord(ctx, req.(*QueryIdentityRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityChangeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityChangeRequest(ctx, req.(*QueryIdentityChangeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityChangeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityChangeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityChangeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityChangeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityChangeHistory(ctx, req.(*QueryIdentityChangeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aura.identitychange.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IdentityRecord",
			Handler:    _Query_IdentityRecord_Handler,
		},
		{
			MethodName: "IdentityChangeRequest",
			Handler:    _Query_IdentityChangeRequest_Handler,
		},
		{
			MethodName: "IdentityChangeHistory",
			Handler:    _Query_IdentityChangeHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aura/identitychange/v1beta1/identity_change.proto",
}
