// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cosmos/base/query/v1beta1/pagination.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	CountTotal    bool                   `protobuf:"varint,4,opt,name=count_total,json=countTotal,proto3" json:"count_total,omitempty"`
	Reverse       bool                   `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_cosmos_base_query_v1beta1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_query_v1beta1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_cosmos_base_query_v1beta1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PageRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PageRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetCountTotal() bool {
	if x != nil {
		return x.CountTotal
	}
	return false
}

func (x *PageRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextKey       []byte                 `protobuf:"bytes,1,opt,name=next_key,json=nextKey,proto3" json:"next_key,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_cosmos_base_query_v1beta1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_query_v1beta1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_cosmos_base_query_v1beta1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextKey() []byte {
	if x != nil {
		return x.NextKey
	}
	return nil
}

func (x *PageResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_cosmos_base_query_v1beta1_pagination_proto protoreflect.FileDescriptor

const file_cosmos_base_query_v1beta1_pagination_proto_rawDesc = "" +
	"\n" +
	"*cosmos/base/query/v1beta1/pagination.proto\x12\x19cosmos.base.query.v1beta1\"\x88\x01\n" +
	"\vPageRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x1f\n" +
	"\vcount_total\x18\x04 \x01(\bR\n" +
	"countTotal\x12\x18\n" +
	"\areverse\x18\x05 \x01(\bR\areverse\"?\n" +
	"\fPageResponse\x12\x19\n" +
	"\bnext_key\x18\x01 \x01(\fR\anextKey\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05totalB*Z(github.com/cosmos/cosmos-sdk/types/queryb\x06proto3"

var (
	file_cosmos_base_query_v1beta1_pagination_proto_rawDescOnce sync.Once
	file_cosmos_base_query_v1beta1_pagination_proto_rawDescData []byte
)

func file_cosmos_base_query_v1beta1_pagination_proto_rawDescGZIP() []byte {
	file_cosmos_base_query_v1beta1_pagination_proto_rawDescOnce.Do(func() {
		file_cosmos_base_query_v1beta1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosmos_base_query_v1beta1_pagination_proto_rawDesc), len(file_cosmos_base_query_v1beta1_pagination_proto_rawDesc)))
	})
	return file_cosmos_base_query_v1beta1_pagination_proto_rawDescData
}

var file_cosmos_base_query_v1beta1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cosmos_base_query_v1beta1_pagination_proto_goTypes = []any{
	(*PageRequest)(nil),  // 0: cosmos.base.query.v1beta1.PageRequest
	(*PageResponse)(nil), // 1: cosmos.base.query.v1beta1.PageResponse
}
var file_cosmos_base_query_v1beta1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_base_query_v1beta1_pagination_proto_init() }
func file_cosmos_base_query_v1beta1_pagination_proto_init() {
	if File_cosmos_base_query_v1beta1_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosmos_base_query_v1beta1_pagination_proto_rawDesc), len(file_cosmos_base_query_v1beta1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_base_query_v1beta1_pagination_proto_goTypes,
		DependencyIndexes: file_cosmos_base_query_v1beta1_pagination_proto_depIdxs,
		MessageInfos:      file_cosmos_base_query_v1beta1_pagination_proto_msgTypes,
	}.Build()
	File_cosmos_base_query_v1beta1_pagination_proto = out.File
	file_cosmos_base_query_v1beta1_pagination_proto_goTypes = nil
	file_cosmos_base_query_v1beta1_pagination_proto_depIdxs = nil
}
