// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: aura/incidentresponse/v1beta1/query.proto

package incidentresponsev1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_GetIncident_FullMethodName        = "/aura.incidentresponse.v1beta1.Query/GetIncident"
	Query_GetChainPauseState_FullMethodName = "/aura.incidentresponse.v1beta1.Query/GetChainPauseState"
	Query_CheckWalletLimit_FullMethodName   = "/aura.incidentresponse.v1beta1.Query/CheckWalletLimit"
	Query_GetParams_FullMethodName          = "/aura.incidentresponse.v1beta1.Query/GetParams"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the incidentresponse module
type QueryClient interface {
	// GetIncident returns incident details
	GetIncident(ctx context.Context, in *QueryGetIncidentRequest, opts ...grpc.CallOption) (*QueryGetIncidentResponse, error)
	// GetChainPauseState returns current chain pause state
	GetChainPauseState(ctx context.Context, in *QueryGetChainPauseStateRequest, opts ...grpc.CallOption) (*QueryGetChainPauseStateResponse, error)
	// CheckWalletLimit checks if an amount is within wallet limits
	CheckWalletLimit(ctx context.Context, in *QueryCheckWalletLimitRequest, opts ...grpc.CallOption) (*QueryCheckWalletLimitResponse, error)
	// GetParams returns module parameters
	GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetIncident(ctx context.Context, in *QueryGetIncidentRequest, opts ...grpc.CallOption) (*QueryGetIncidentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetIncidentResponse)
	err := c.cc.Invoke(ctx, Query_GetIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetChainPauseState(ctx context.Context, in *QueryGetChainPauseStateRequest, opts ...grpc.CallOption) (*QueryGetChainPauseStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetChainPauseStateResponse)
	err := c.cc.Invoke(ctx, Query_GetChainPauseState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CheckWalletLimit(ctx context.Context, in *QueryCheckWalletLimitRequest, opts ...grpc.CallOption) (*QueryCheckWalletLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCheckWalletLimitResponse)
	err := c.cc.Invoke(ctx, Query_CheckWalletLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetParamsResponse)
	err := c.cc.Invoke(ctx, Query_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the incidentresponse module
type QueryServer interface {
	// GetIncident returns incident details
	GetIncident(context.Context, *QueryGetIncidentRequest) (*QueryGetIncidentResponse, error)
	// GetChainPauseState returns current chain pause state
	GetChainPauseState(context.Context, *QueryGetChainPauseStateRequest) (*QueryGetChainPauseStateResponse, error)
	// CheckWalletLimit checks if an amount is within wallet limits
	CheckWalletLimit(context.Context, *QueryCheckWalletLimitRequest) (*QueryCheckWalletLimitResponse, error)
	// GetParams returns module parameters
	GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) GetIncident(context.Context, *QueryGetIncidentRequest) (*QueryGetIncidentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncident not implemented")
}
func (UnimplementedQueryServer) GetChainPauseState(context.Context, *QueryGetChainPauseStateRequest) (*QueryGetChainPauseStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChainPauseState not implemented")
}
func (UnimplementedQueryServer) CheckWalletLimit(context.Context, *QueryCheckWalletLimitRequest) (*QueryCheckWalletLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckWalletLimit not implemented")
}
func (UnimplementedQueryServer) GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetIncident(ctx, req.(*QueryGetIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetChainPauseState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetChainPauseStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetChainPauseState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetChainPauseState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetChainPauseState(ctx, req.(*QueryGetChainPauseStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CheckWalletLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCheckWalletLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CheckWalletLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CheckWalletLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CheckWalletLimit(ctx, req.(*QueryCheckWalletLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParams(ctx, req.(*QueryGetParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aura.incidentresponse.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIncident",
			Handler:    _Query_GetIncident_Handler,
		},
		{
			MethodName: "GetChainPauseState",
			Handler:    _Query_GetChainPauseState_Handler,
		},
		{
			MethodName: "CheckWalletLimit",
			Handler:    _Query_CheckWalletLimit_Handler,
		},
		{
			MethodName: "GetParams",
			Handler:    _Query_GetParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aura/incidentresponse/v1beta1/query.proto",
}
