apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-node
spec:
  template:
    spec:
      initContainers:
        - name: init-config
          env:
            - name: CHAIN_ID
              value: "aura-mvp-1"
      containers:
        - name: aura
          image: aequitas/aura:testnet
